---
# Monitoring role defaults

# Component versions
node_exporter_version: "1.8.2"
prometheus_version: "2.53.1"
alertmanager_version: "0.27.0"

# Prometheus settings
prometheus_retention: "15d"
prometheus_memory_limit: "3G"
