#!/usr/bin/env python3
"""MathWorld (Wolfram) mathematics reference scraper.

Covers:
  - Algebra, Analysis, Calculus, Discrete Mathematics
  - Foundations, Geometry, Number Theory
  - Probability & Statistics, Topology, Applied Math
"""
import re
import time
import html as html_mod
from scraper_base import BaseScraper


class MathWorldScraper(BaseScraper):
    """Scrape MathWorld mathematical encyclopedia from mathworld.wolfram.com."""

    SOURCES = {
        "algebra": {
            "pages": {
                "https://mathworld.wolfram.com/Algebra.html": "Algebra",
                "https://mathworld.wolfram.com/LinearAlgebra.html": "Linear Algebra",
                "https://mathworld.wolfram.com/Matrix.html": "Matrix",
                "https://mathworld.wolfram.com/Determinant.html": "Determinant",
                "https://mathworld.wolfram.com/Eigenvalue.html": "Eigenvalue",
                "https://mathworld.wolfram.com/Eigenvector.html": "Eigenvector",
                "https://mathworld.wolfram.com/InverseMatrix.html": "Inverse Matrix",
                "https://mathworld.wolfram.com/Transpose.html": "Transpose",
                "https://mathworld.wolfram.com/IdentityMatrix.html": "Identity Matrix",
                "https://mathworld.wolfram.com/OrthogonalMatrix.html": "Orthogonal Matrix",
                "https://mathworld.wolfram.com/SymmetricMatrix.html": "Symmetric Matrix",
                "https://mathworld.wolfram.com/DiagonalMatrix.html": "Diagonal Matrix",
                "https://mathworld.wolfram.com/HermitianMatrix.html": "Hermitian Matrix",
                "https://mathworld.wolfram.com/UnitaryMatrix.html": "Unitary Matrix",
                "https://mathworld.wolfram.com/SingularValueDecomposition.html": "Singular Value Decomposition",
                "https://mathworld.wolfram.com/QRDecomposition.html": "QR Decomposition",
                "https://mathworld.wolfram.com/LUDecomposition.html": "LU Decomposition",
                "https://mathworld.wolfram.com/CholeskyDecomposition.html": "Cholesky Decomposition",
                "https://mathworld.wolfram.com/VectorSpace.html": "Vector Space",
                "https://mathworld.wolfram.com/InnerProduct.html": "Inner Product",
                "https://mathworld.wolfram.com/CrossProduct.html": "Cross Product",
                "https://mathworld.wolfram.com/DotProduct.html": "Dot Product",
                "https://mathworld.wolfram.com/Norm.html": "Norm",
                "https://mathworld.wolfram.com/LinearIndependence.html": "Linear Independence",
                "https://mathworld.wolfram.com/Basis.html": "Basis",
                "https://mathworld.wolfram.com/Dimension.html": "Dimension",
                "https://mathworld.wolfram.com/Rank.html": "Rank",
                "https://mathworld.wolfram.com/NullSpace.html": "Null Space",
                "https://mathworld.wolfram.com/ColumnSpace.html": "Column Space",
                "https://mathworld.wolfram.com/LinearTransformation.html": "Linear Transformation",
                "https://mathworld.wolfram.com/Group.html": "Group",
                "https://mathworld.wolfram.com/Ring.html": "Ring",
                "https://mathworld.wolfram.com/Field.html": "Field",
                "https://mathworld.wolfram.com/AbelianGroup.html": "Abelian Group",
                "https://mathworld.wolfram.com/CyclicGroup.html": "Cyclic Group",
                "https://mathworld.wolfram.com/SymmetricGroup.html": "Symmetric Group",
                "https://mathworld.wolfram.com/Permutation.html": "Permutation",
                "https://mathworld.wolfram.com/Polynomial.html": "Polynomial",
                "https://mathworld.wolfram.com/QuadraticEquation.html": "Quadratic Equation",
                "https://mathworld.wolfram.com/CubicFormula.html": "Cubic Formula",
                "https://mathworld.wolfram.com/QuarticEquation.html": "Quartic Equation",
                "https://mathworld.wolfram.com/FundamentalTheoremofAlgebra.html": "Fundamental Theorem of Algebra",
                "https://mathworld.wolfram.com/ComplexNumber.html": "Complex Number",
                "https://mathworld.wolfram.com/Quaternion.html": "Quaternion",
                "https://mathworld.wolfram.com/Tensor.html": "Tensor",
                "https://mathworld.wolfram.com/BooleanAlgebra.html": "Boolean Algebra",
                "https://mathworld.wolfram.com/Lattice.html": "Lattice",
                "https://mathworld.wolfram.com/Ideal.html": "Ideal",
                "https://mathworld.wolfram.com/Homomorphism.html": "Homomorphism",
                "https://mathworld.wolfram.com/Isomorphism.html": "Isomorphism",
                "https://mathworld.wolfram.com/Subgroup.html": "Subgroup",
                "https://mathworld.wolfram.com/Coset.html": "Coset",
                "https://mathworld.wolfram.com/NormalSubgroup.html": "Normal Subgroup",
                "https://mathworld.wolfram.com/QuotientGroup.html": "Quotient Group",
                "https://mathworld.wolfram.com/GaloisTheory.html": "Galois Theory",
                "https://mathworld.wolfram.com/ModularArithmetic.html": "Modular Arithmetic",
                "https://mathworld.wolfram.com/Congruence.html": "Congruence",
                "https://mathworld.wolfram.com/ChineseRemainderTheorem.html": "Chinese Remainder Theorem",
                "https://mathworld.wolfram.com/CayleyHamiltonTheorem.html": "Cayley-Hamilton Theorem",
                "https://mathworld.wolfram.com/JordanNormalForm.html": "Jordan Normal Form",
                "https://mathworld.wolfram.com/CharacteristicPolynomial.html": "Characteristic Polynomial",
                "https://mathworld.wolfram.com/MinimalPolynomial.html": "Minimal Polynomial",
                "https://mathworld.wolfram.com/Trace.html": "Trace",
                "https://mathworld.wolfram.com/MatrixExponential.html": "Matrix Exponential",
                "https://mathworld.wolfram.com/KroneckerProduct.html": "Kronecker Product",
                "https://mathworld.wolfram.com/HadamardProduct.html": "Hadamard Product",
                "https://mathworld.wolfram.com/PositiveDefiniteMatrix.html": "Positive Definite Matrix",
                "https://mathworld.wolfram.com/Diagonalization.html": "Diagonalization",
                "https://mathworld.wolfram.com/SpectralTheorem.html": "Spectral Theorem",
                "https://mathworld.wolfram.com/SparseMatrix.html": "Sparse Matrix",
                "https://mathworld.wolfram.com/TridiagonalMatrix.html": "Tridiagonal Matrix",
                "https://mathworld.wolfram.com/ToeplitzMatrix.html": "Toeplitz Matrix",
                "https://mathworld.wolfram.com/CirculantMatrix.html": "Circulant Matrix",
                "https://mathworld.wolfram.com/VandermondeDeterminant.html": "Vandermonde Determinant",
                "https://mathworld.wolfram.com/MatrixNorm.html": "Matrix Norm",
                "https://mathworld.wolfram.com/Endomorphism.html": "Endomorphism",
                "https://mathworld.wolfram.com/Automorphism.html": "Automorphism",
                "https://mathworld.wolfram.com/DirectProduct.html": "Direct Product",
                "https://mathworld.wolfram.com/FreeGroup.html": "Free Group",
                "https://mathworld.wolfram.com/GroupAction.html": "Group Action",
                "https://mathworld.wolfram.com/SylowTheorems.html": "Sylow Theorems",
                "https://mathworld.wolfram.com/LagrangesTheorem.html": "Lagrange's Theorem",
                "https://mathworld.wolfram.com/GroupRepresentation.html": "Group Representation",
                "https://mathworld.wolfram.com/LieGroup.html": "Lie Group",
                "https://mathworld.wolfram.com/LieAlgebra.html": "Lie Algebra",
                "https://mathworld.wolfram.com/Octonion.html": "Octonion",
                "https://mathworld.wolfram.com/GrassmannAlgebra.html": "Grassmann Algebra",
                "https://mathworld.wolfram.com/CliffordAlgebra.html": "Clifford Algebra",
                "https://mathworld.wolfram.com/Module.html": "Module",
                "https://mathworld.wolfram.com/PrincipalIdealDomain.html": "Principal Ideal Domain",
                "https://mathworld.wolfram.com/UniqueFactorizationDomain.html": "Unique Factorization Domain",
                "https://mathworld.wolfram.com/EuclideanDomain.html": "Euclidean Domain",
                "https://mathworld.wolfram.com/PolynomialRing.html": "Polynomial Ring",
                "https://mathworld.wolfram.com/IrreduciblePolynomial.html": "Irreducible Polynomial",
                "https://mathworld.wolfram.com/FieldExtension.html": "Field Extension",
                "https://mathworld.wolfram.com/SplittingField.html": "Splitting Field",
                "https://mathworld.wolfram.com/GaloisGroup.html": "Galois Group",
                "https://mathworld.wolfram.com/MatrixDecomposition.html": "Matrix Decomposition",
                "https://mathworld.wolfram.com/SchurDecomposition.html": "Schur Decomposition",
                "https://mathworld.wolfram.com/PolarDecomposition.html": "Polar Decomposition",
                "https://mathworld.wolfram.com/BlockMatrix.html": "Block Matrix",
                "https://mathworld.wolfram.com/PermutationMatrix.html": "Permutation Matrix",
                "https://mathworld.wolfram.com/StochasticMatrix.html": "Stochastic Matrix",
                "https://mathworld.wolfram.com/NilpotentMatrix.html": "Nilpotent Matrix",
                "https://mathworld.wolfram.com/ProjectionMatrix.html": "Projection Matrix",
                "https://mathworld.wolfram.com/AdjointMatrix.html": "Adjoint Matrix",
            },
        },
        "analysis": {
            "pages": {
                "https://mathworld.wolfram.com/Analysis.html": "Analysis",
                "https://mathworld.wolfram.com/RealAnalysis.html": "Real Analysis",
                "https://mathworld.wolfram.com/ComplexAnalysis.html": "Complex Analysis",
                "https://mathworld.wolfram.com/FunctionalAnalysis.html": "Functional Analysis",
                "https://mathworld.wolfram.com/Limit.html": "Limit",
                "https://mathworld.wolfram.com/Continuity.html": "Continuity",
                "https://mathworld.wolfram.com/UniformContinuity.html": "Uniform Continuity",
                "https://mathworld.wolfram.com/Convergence.html": "Convergence",
                "https://mathworld.wolfram.com/UniformConvergence.html": "Uniform Convergence",
                "https://mathworld.wolfram.com/PointwiseConvergence.html": "Pointwise Convergence",
                "https://mathworld.wolfram.com/Series.html": "Series",
                "https://mathworld.wolfram.com/PowerSeries.html": "Power Series",
                "https://mathworld.wolfram.com/TaylorSeries.html": "Taylor Series",
                "https://mathworld.wolfram.com/MaclaurinSeries.html": "Maclaurin Series",
                "https://mathworld.wolfram.com/LaurentSeries.html": "Laurent Series",
                "https://mathworld.wolfram.com/FourierSeries.html": "Fourier Series",
                "https://mathworld.wolfram.com/FourierTransform.html": "Fourier Transform",
                "https://mathworld.wolfram.com/LaplaceTransform.html": "Laplace Transform",
                "https://mathworld.wolfram.com/ZTransform.html": "Z-Transform",
                "https://mathworld.wolfram.com/Sequence.html": "Sequence",
                "https://mathworld.wolfram.com/CauchySequence.html": "Cauchy Sequence",
                "https://mathworld.wolfram.com/BolzanoWeierstrassTheorem.html": "Bolzano-Weierstrass Theorem",
                "https://mathworld.wolfram.com/HeineBorelTheorem.html": "Heine-Borel Theorem",
                "https://mathworld.wolfram.com/CompactSet.html": "Compact Set",
                "https://mathworld.wolfram.com/OpenSet.html": "Open Set",
                "https://mathworld.wolfram.com/ClosedSet.html": "Closed Set",
                "https://mathworld.wolfram.com/MetricSpace.html": "Metric Space",
                "https://mathworld.wolfram.com/BanachSpace.html": "Banach Space",
                "https://mathworld.wolfram.com/HilbertSpace.html": "Hilbert Space",
                "https://mathworld.wolfram.com/LpSpace.html": "Lp Space",
                "https://mathworld.wolfram.com/MeasureTheory.html": "Measure Theory",
                "https://mathworld.wolfram.com/LebesgueIntegral.html": "Lebesgue Integral",
                "https://mathworld.wolfram.com/LebesgueMeasure.html": "Lebesgue Measure",
                "https://mathworld.wolfram.com/SigmaAlgebra.html": "Sigma-Algebra",
                "https://mathworld.wolfram.com/BorelSet.html": "Borel Set",
                "https://mathworld.wolfram.com/MeasurableFunction.html": "Measurable Function",
                "https://mathworld.wolfram.com/DominatedConvergenceTheorem.html": "Dominated Convergence Theorem",
                "https://mathworld.wolfram.com/MonotoneConvergenceTheorem.html": "Monotone Convergence Theorem",
                "https://mathworld.wolfram.com/FubinisTheorem.html": "Fubini's Theorem",
                "https://mathworld.wolfram.com/AnalyticFunction.html": "Analytic Function",
                "https://mathworld.wolfram.com/HolomorphicFunction.html": "Holomorphic Function",
                "https://mathworld.wolfram.com/MeromorphicFunction.html": "Meromorphic Function",
                "https://mathworld.wolfram.com/Singularity.html": "Singularity",
                "https://mathworld.wolfram.com/Pole.html": "Pole",
                "https://mathworld.wolfram.com/Residue.html": "Residue",
                "https://mathworld.wolfram.com/ResidueTheorem.html": "Residue Theorem",
                "https://mathworld.wolfram.com/CauchyIntegralFormula.html": "Cauchy Integral Formula",
                "https://mathworld.wolfram.com/CauchyIntegralTheorem.html": "Cauchy Integral Theorem",
                "https://mathworld.wolfram.com/ConformalMapping.html": "Conformal Mapping",
                "https://mathworld.wolfram.com/RiemannMappingTheorem.html": "Riemann Mapping Theorem",
                "https://mathworld.wolfram.com/MaximumModulusPrinciple.html": "Maximum Modulus Principle",
                "https://mathworld.wolfram.com/LiouvillesTheorem.html": "Liouville's Theorem",
                "https://mathworld.wolfram.com/PicardTheorem.html": "Picard Theorem",
                "https://mathworld.wolfram.com/RiemannZetaFunction.html": "Riemann Zeta Function",
                "https://mathworld.wolfram.com/GammaFunction.html": "Gamma Function",
                "https://mathworld.wolfram.com/BetaFunction.html": "Beta Function",
                "https://mathworld.wolfram.com/BesselFunction.html": "Bessel Function",
                "https://mathworld.wolfram.com/HypergeometricFunction.html": "Hypergeometric Function",
                "https://mathworld.wolfram.com/EllipticFunction.html": "Elliptic Function",
                "https://mathworld.wolfram.com/EllipticIntegral.html": "Elliptic Integral",
                "https://mathworld.wolfram.com/DiracDeltaFunction.html": "Dirac Delta Function",
                "https://mathworld.wolfram.com/DistributionTheory.html": "Distribution Theory",
                "https://mathworld.wolfram.com/AbsoluteConvergence.html": "Absolute Convergence",
                "https://mathworld.wolfram.com/ConditionalConvergence.html": "Conditional Convergence",
                "https://mathworld.wolfram.com/RadiusofConvergence.html": "Radius of Convergence",
                "https://mathworld.wolfram.com/RatioTest.html": "Ratio Test",
                "https://mathworld.wolfram.com/RootTest.html": "Root Test",
                "https://mathworld.wolfram.com/ComparisonTest.html": "Comparison Test",
                "https://mathworld.wolfram.com/IntegralTest.html": "Integral Test",
                "https://mathworld.wolfram.com/AlternatingSeriesTest.html": "Alternating Series Test",
                "https://mathworld.wolfram.com/AbelSummation.html": "Abel Summation",
                "https://mathworld.wolfram.com/CesaroSum.html": "Cesaro Sum",
                "https://mathworld.wolfram.com/WeierstrassApproximationTheorem.html": "Weierstrass Approximation Theorem",
                "https://mathworld.wolfram.com/StoneWeierstrassTheorem.html": "Stone-Weierstrass Theorem",
                "https://mathworld.wolfram.com/ArzelaAscoliTheorem.html": "Arzela-Ascoli Theorem",
                "https://mathworld.wolfram.com/BanachFixedPointTheorem.html": "Banach Fixed Point Theorem",
                "https://mathworld.wolfram.com/HahnBanachTheorem.html": "Hahn-Banach Theorem",
                "https://mathworld.wolfram.com/OpenMappingTheorem.html": "Open Mapping Theorem",
                "https://mathworld.wolfram.com/ClosedGraphTheorem.html": "Closed Graph Theorem",
                "https://mathworld.wolfram.com/RieszRepresentationTheorem.html": "Riesz Representation Theorem",
                "https://mathworld.wolfram.com/SpectralTheory.html": "Spectral Theory",
                "https://mathworld.wolfram.com/Operator.html": "Operator",
                "https://mathworld.wolfram.com/CompactOperator.html": "Compact Operator",
                "https://mathworld.wolfram.com/SelfAdjointOperator.html": "Self-Adjoint Operator",
                "https://mathworld.wolfram.com/AiryFunction.html": "Airy Function",
                "https://mathworld.wolfram.com/LegendrePolynomial.html": "Legendre Polynomial",
                "https://mathworld.wolfram.com/HermitePolynomial.html": "Hermite Polynomial",
                "https://mathworld.wolfram.com/LaguerrePolynomial.html": "Laguerre Polynomial",
                "https://mathworld.wolfram.com/ChebyshevPolynomial.html": "Chebyshev Polynomial",
                "https://mathworld.wolfram.com/OrthogonalPolynomials.html": "Orthogonal Polynomials",
                "https://mathworld.wolfram.com/SphericalHarmonic.html": "Spherical Harmonic",
                "https://mathworld.wolfram.com/JacobiPolynomial.html": "Jacobi Polynomial",
                "https://mathworld.wolfram.com/DigammaFunction.html": "Digamma Function",
                "https://mathworld.wolfram.com/PolylogarithmFunction.html": "Polylogarithm Function",
                "https://mathworld.wolfram.com/MittagLefflerFunction.html": "Mittag-Leffler Function",
                "https://mathworld.wolfram.com/WeierstrassFunction.html": "Weierstrass Function",
            },
        },
        "calculus": {
            "pages": {
                "https://mathworld.wolfram.com/Calculus.html": "Calculus",
                "https://mathworld.wolfram.com/Derivative.html": "Derivative",
                "https://mathworld.wolfram.com/PartialDerivative.html": "Partial Derivative",
                "https://mathworld.wolfram.com/ChainRule.html": "Chain Rule",
                "https://mathworld.wolfram.com/ProductRule.html": "Product Rule",
                "https://mathworld.wolfram.com/QuotientRule.html": "Quotient Rule",
                "https://mathworld.wolfram.com/LHopitalsRule.html": "L'Hopital's Rule",
                "https://mathworld.wolfram.com/MeanValueTheorem.html": "Mean Value Theorem",
                "https://mathworld.wolfram.com/RollesTheorem.html": "Rolle's Theorem",
                "https://mathworld.wolfram.com/IntermediateValueTheorem.html": "Intermediate Value Theorem",
                "https://mathworld.wolfram.com/ExtremeValueTheorem.html": "Extreme Value Theorem",
                "https://mathworld.wolfram.com/ImplicitDifferentiation.html": "Implicit Differentiation",
                "https://mathworld.wolfram.com/Gradient.html": "Gradient",
                "https://mathworld.wolfram.com/Divergence.html": "Divergence",
                "https://mathworld.wolfram.com/Curl.html": "Curl",
                "https://mathworld.wolfram.com/Laplacian.html": "Laplacian",
                "https://mathworld.wolfram.com/Jacobian.html": "Jacobian",
                "https://mathworld.wolfram.com/Hessian.html": "Hessian",
                "https://mathworld.wolfram.com/DirectionalDerivative.html": "Directional Derivative",
                "https://mathworld.wolfram.com/Integral.html": "Integral",
                "https://mathworld.wolfram.com/DefiniteIntegral.html": "Definite Integral",
                "https://mathworld.wolfram.com/IndefiniteIntegral.html": "Indefinite Integral",
                "https://mathworld.wolfram.com/ImproperIntegral.html": "Improper Integral",
                "https://mathworld.wolfram.com/IntegrationbyParts.html": "Integration by Parts",
                "https://mathworld.wolfram.com/IntegrationbySubstitution.html": "Integration by Substitution",
                "https://mathworld.wolfram.com/PartialFractions.html": "Partial Fractions",
                "https://mathworld.wolfram.com/TrigonometricSubstitution.html": "Trigonometric Substitution",
                "https://mathworld.wolfram.com/FundamentalTheoremofCalculus.html": "Fundamental Theorem of Calculus",
                "https://mathworld.wolfram.com/DoubleIntegral.html": "Double Integral",
                "https://mathworld.wolfram.com/TripleIntegral.html": "Triple Integral",
                "https://mathworld.wolfram.com/LineIntegral.html": "Line Integral",
                "https://mathworld.wolfram.com/SurfaceIntegral.html": "Surface Integral",
                "https://mathworld.wolfram.com/GreensTheorem.html": "Green's Theorem",
                "https://mathworld.wolfram.com/StokesTheorem.html": "Stokes' Theorem",
                "https://mathworld.wolfram.com/DivergenceTheorem.html": "Divergence Theorem",
                "https://mathworld.wolfram.com/OrdinaryDifferentialEquation.html": "Ordinary Differential Equation",
                "https://mathworld.wolfram.com/PartialDifferentialEquation.html": "Partial Differential Equation",
                "https://mathworld.wolfram.com/LinearDifferentialEquation.html": "Linear Differential Equation",
                "https://mathworld.wolfram.com/SeparableEquation.html": "Separable Equation",
                "https://mathworld.wolfram.com/ExactEquation.html": "Exact Equation",
                "https://mathworld.wolfram.com/BernoulliDifferentialEquation.html": "Bernoulli Differential Equation",
                "https://mathworld.wolfram.com/EulersEquation.html": "Euler's Equation",
                "https://mathworld.wolfram.com/LaplaceEquation.html": "Laplace Equation",
                "https://mathworld.wolfram.com/HeatEquation.html": "Heat Equation",
                "https://mathworld.wolfram.com/WaveEquation.html": "Wave Equation",
                "https://mathworld.wolfram.com/PoissonEquation.html": "Poisson Equation",
                "https://mathworld.wolfram.com/SchrodingerEquation.html": "Schrodinger Equation",
                "https://mathworld.wolfram.com/NavierStokesEquations.html": "Navier-Stokes Equations",
                "https://mathworld.wolfram.com/CalculusofVariations.html": "Calculus of Variations",
                "https://mathworld.wolfram.com/EulerLagrangeEquation.html": "Euler-Lagrange Equation",
                "https://mathworld.wolfram.com/LagrangeMultiplier.html": "Lagrange Multiplier",
                "https://mathworld.wolfram.com/StationaryPoint.html": "Stationary Point",
                "https://mathworld.wolfram.com/CriticalPoint.html": "Critical Point",
                "https://mathworld.wolfram.com/Inflection.html": "Inflection",
                "https://mathworld.wolfram.com/Asymptote.html": "Asymptote",
                "https://mathworld.wolfram.com/Curvature.html": "Curvature",
                "https://mathworld.wolfram.com/ArcLength.html": "Arc Length",
                "https://mathworld.wolfram.com/SurfaceArea.html": "Surface Area",
                "https://mathworld.wolfram.com/Volume.html": "Volume",
                "https://mathworld.wolfram.com/ParametricCurve.html": "Parametric Curve",
                "https://mathworld.wolfram.com/PolarCoordinates.html": "Polar Coordinates",
                "https://mathworld.wolfram.com/CylindricalCoordinates.html": "Cylindrical Coordinates",
                "https://mathworld.wolfram.com/SphericalCoordinates.html": "Spherical Coordinates",
                "https://mathworld.wolfram.com/VectorField.html": "Vector Field",
                "https://mathworld.wolfram.com/ScalarField.html": "Scalar Field",
                "https://mathworld.wolfram.com/ConservativeField.html": "Conservative Field",
                "https://mathworld.wolfram.com/PotentialFunction.html": "Potential Function",
                "https://mathworld.wolfram.com/GreensFunction.html": "Green's Function",
                "https://mathworld.wolfram.com/BoundaryValueProblem.html": "Boundary Value Problem",
                "https://mathworld.wolfram.com/InitialValueProblem.html": "Initial Value Problem",
                "https://mathworld.wolfram.com/SturmLiouvilleTheory.html": "Sturm-Liouville Theory",
                "https://mathworld.wolfram.com/RiemannSum.html": "Riemann Sum",
                "https://mathworld.wolfram.com/RiemannIntegral.html": "Riemann Integral",
                "https://mathworld.wolfram.com/StieltjesIntegral.html": "Stieltjes Integral",
                "https://mathworld.wolfram.com/PathIntegral.html": "Path Integral",
                "https://mathworld.wolfram.com/ContourIntegral.html": "Contour Integral",
                "https://mathworld.wolfram.com/MultivariableCalculus.html": "Multivariable Calculus",
                "https://mathworld.wolfram.com/TotalDifferential.html": "Total Differential",
                "https://mathworld.wolfram.com/DifferentialForm.html": "Differential Form",
                "https://mathworld.wolfram.com/ExteriorDerivative.html": "Exterior Derivative",
                "https://mathworld.wolfram.com/WronskianDeterminant.html": "Wronskian Determinant",
                "https://mathworld.wolfram.com/PowerSeriesMethod.html": "Power Series Method",
                "https://mathworld.wolfram.com/FrobeniusMethod.html": "Frobenius Method",
                "https://mathworld.wolfram.com/VariationofParameters.html": "Variation of Parameters",
                "https://mathworld.wolfram.com/AdomianDecomposition.html": "Adomian Decomposition",
                "https://mathworld.wolfram.com/HamiltonianSystem.html": "Hamiltonian System",
            },
        },
        "discrete-math": {
            "pages": {
                "https://mathworld.wolfram.com/DiscreteMathematics.html": "Discrete Mathematics",
                "https://mathworld.wolfram.com/GraphTheory.html": "Graph Theory",
                "https://mathworld.wolfram.com/Graph.html": "Graph",
                "https://mathworld.wolfram.com/Tree.html": "Tree",
                "https://mathworld.wolfram.com/SpanningTree.html": "Spanning Tree",
                "https://mathworld.wolfram.com/BipartiteGraph.html": "Bipartite Graph",
                "https://mathworld.wolfram.com/CompleteGraph.html": "Complete Graph",
                "https://mathworld.wolfram.com/PlanarGraph.html": "Planar Graph",
                "https://mathworld.wolfram.com/EulerianPath.html": "Eulerian Path",
                "https://mathworld.wolfram.com/HamiltonianPath.html": "Hamiltonian Path",
                "https://mathworld.wolfram.com/HamiltonianCycle.html": "Hamiltonian Cycle",
                "https://mathworld.wolfram.com/GraphColoring.html": "Graph Coloring",
                "https://mathworld.wolfram.com/ChromaticNumber.html": "Chromatic Number",
                "https://mathworld.wolfram.com/Clique.html": "Clique",
                "https://mathworld.wolfram.com/IndependentSet.html": "Independent Set",
                "https://mathworld.wolfram.com/VertexCover.html": "Vertex Cover",
                "https://mathworld.wolfram.com/Matching.html": "Matching",
                "https://mathworld.wolfram.com/MaximumFlow.html": "Maximum Flow",
                "https://mathworld.wolfram.com/MinimumCut.html": "Minimum Cut",
                "https://mathworld.wolfram.com/ShortestPath.html": "Shortest Path",
                "https://mathworld.wolfram.com/AdjacencyMatrix.html": "Adjacency Matrix",
                "https://mathworld.wolfram.com/Combinatorics.html": "Combinatorics",
                "https://mathworld.wolfram.com/BinomialCoefficient.html": "Binomial Coefficient",
                "https://mathworld.wolfram.com/BinomialTheorem.html": "Binomial Theorem",
                "https://mathworld.wolfram.com/MultinomialCoefficient.html": "Multinomial Coefficient",
                "https://mathworld.wolfram.com/PascalsTriangle.html": "Pascal's Triangle",
                "https://mathworld.wolfram.com/Combination.html": "Combination",
                "https://mathworld.wolfram.com/PigeonholePrinciple.html": "Pigeonhole Principle",
                "https://mathworld.wolfram.com/InclusionExclusionPrinciple.html": "Inclusion-Exclusion Principle",
                "https://mathworld.wolfram.com/GeneratingFunction.html": "Generating Function",
                "https://mathworld.wolfram.com/RecurrenceRelation.html": "Recurrence Relation",
                "https://mathworld.wolfram.com/FibonacciNumber.html": "Fibonacci Number",
                "https://mathworld.wolfram.com/CatalanNumber.html": "Catalan Number",
                "https://mathworld.wolfram.com/StirlingNumber.html": "Stirling Number",
                "https://mathworld.wolfram.com/BellNumber.html": "Bell Number",
                "https://mathworld.wolfram.com/PartitionFunction.html": "Partition Function",
                "https://mathworld.wolfram.com/RamseyTheory.html": "Ramsey Theory",
                "https://mathworld.wolfram.com/Automaton.html": "Automaton",
                "https://mathworld.wolfram.com/TuringMachine.html": "Turing Machine",
                "https://mathworld.wolfram.com/RegularLanguage.html": "Regular Language",
                "https://mathworld.wolfram.com/ContextFreeGrammar.html": "Context-Free Grammar",
                "https://mathworld.wolfram.com/NPComplete.html": "NP-Complete",
                "https://mathworld.wolfram.com/PvsNP.html": "P vs NP",
                "https://mathworld.wolfram.com/Algorithm.html": "Algorithm",
                "https://mathworld.wolfram.com/BigONotation.html": "Big-O Notation",
                "https://mathworld.wolfram.com/SortingAlgorithm.html": "Sorting Algorithm",
                "https://mathworld.wolfram.com/BooleanFunction.html": "Boolean Function",
                "https://mathworld.wolfram.com/PropositionalLogic.html": "Propositional Logic",
                "https://mathworld.wolfram.com/PredicateLogic.html": "Predicate Logic",
                "https://mathworld.wolfram.com/Set.html": "Set",
                "https://mathworld.wolfram.com/Subset.html": "Subset",
                "https://mathworld.wolfram.com/Union.html": "Union",
                "https://mathworld.wolfram.com/Intersection.html": "Intersection",
                "https://mathworld.wolfram.com/CartesianProduct.html": "Cartesian Product",
                "https://mathworld.wolfram.com/PowerSet.html": "Power Set",
                "https://mathworld.wolfram.com/Relation.html": "Relation",
                "https://mathworld.wolfram.com/EquivalenceRelation.html": "Equivalence Relation",
                "https://mathworld.wolfram.com/PartialOrder.html": "Partial Order",
                "https://mathworld.wolfram.com/Bijection.html": "Bijection",
                "https://mathworld.wolfram.com/Injection.html": "Injection",
                "https://mathworld.wolfram.com/Surjection.html": "Surjection",
                "https://mathworld.wolfram.com/Function.html": "Function",
                "https://mathworld.wolfram.com/CountableSet.html": "Countable Set",
                "https://mathworld.wolfram.com/UncountableSet.html": "Uncountable Set",
                "https://mathworld.wolfram.com/CantorsTheorem.html": "Cantor's Theorem",
                "https://mathworld.wolfram.com/Cardinality.html": "Cardinality",
                "https://mathworld.wolfram.com/DirectedGraph.html": "Directed Graph",
                "https://mathworld.wolfram.com/WeightedGraph.html": "Weighted Graph",
                "https://mathworld.wolfram.com/ConnectedGraph.html": "Connected Graph",
                "https://mathworld.wolfram.com/StronglyConnectedComponent.html": "Strongly Connected Component",
                "https://mathworld.wolfram.com/TopologicalSort.html": "Topological Sort",
                "https://mathworld.wolfram.com/GraphIsomorphism.html": "Graph Isomorphism",
                "https://mathworld.wolfram.com/ChromaticPolynomial.html": "Chromatic Polynomial",
                "https://mathworld.wolfram.com/DegreeSequence.html": "Degree Sequence",
                "https://mathworld.wolfram.com/GraphDiameter.html": "Graph Diameter",
                "https://mathworld.wolfram.com/MinimumSpanningTree.html": "Minimum Spanning Tree",
                "https://mathworld.wolfram.com/NetworkFlow.html": "Network Flow",
                "https://mathworld.wolfram.com/Hypergraph.html": "Hypergraph",
                "https://mathworld.wolfram.com/PetersenGraph.html": "Petersen Graph",
                "https://mathworld.wolfram.com/RegularGraph.html": "Regular Graph",
                "https://mathworld.wolfram.com/Derangement.html": "Derangement",
                "https://mathworld.wolfram.com/DoubleFactorial.html": "Double Factorial",
                "https://mathworld.wolfram.com/EulerianNumber.html": "Eulerian Number",
                "https://mathworld.wolfram.com/Subfactorial.html": "Subfactorial",
                "https://mathworld.wolfram.com/BurnsidesLemma.html": "Burnside's Lemma",
                "https://mathworld.wolfram.com/PolyaEnumerationTheorem.html": "Polya Enumeration Theorem",
                "https://mathworld.wolfram.com/LatinSquare.html": "Latin Square",
                "https://mathworld.wolfram.com/Matroid.html": "Matroid",
                "https://mathworld.wolfram.com/Lattice.html": "Lattice",
                "https://mathworld.wolfram.com/Poset.html": "Poset",
                "https://mathworld.wolfram.com/TotalOrder.html": "Total Order",
                "https://mathworld.wolfram.com/WellOrder.html": "Well Order",
                "https://mathworld.wolfram.com/VennDiagram.html": "Venn Diagram",
                "https://mathworld.wolfram.com/DeMorgansLaws.html": "De Morgan's Laws",
                "https://mathworld.wolfram.com/TruthTable.html": "Truth Table",
                "https://mathworld.wolfram.com/Tautology.html": "Tautology",
                "https://mathworld.wolfram.com/Contradiction.html": "Contradiction",
                "https://mathworld.wolfram.com/Quantifier.html": "Quantifier",
            },
        },
        "foundations": {
            "pages": {
                "https://mathworld.wolfram.com/Foundations.html": "Foundations",
                "https://mathworld.wolfram.com/SetTheory.html": "Set Theory",
                "https://mathworld.wolfram.com/ZermeloFraenkelAxioms.html": "Zermelo-Fraenkel Axioms",
                "https://mathworld.wolfram.com/AxiomofChoice.html": "Axiom of Choice",
                "https://mathworld.wolfram.com/WellOrderingPrinciple.html": "Well-Ordering Principle",
                "https://mathworld.wolfram.com/ZornsLemma.html": "Zorn's Lemma",
                "https://mathworld.wolfram.com/ContinuumHypothesis.html": "Continuum Hypothesis",
                "https://mathworld.wolfram.com/OrdinalNumber.html": "Ordinal Number",
                "https://mathworld.wolfram.com/CardinalNumber.html": "Cardinal Number",
                "https://mathworld.wolfram.com/TransfiniteNumber.html": "Transfinite Number",
                "https://mathworld.wolfram.com/MathematicalInduction.html": "Mathematical Induction",
                "https://mathworld.wolfram.com/StrongInduction.html": "Strong Induction",
                "https://mathworld.wolfram.com/TransfiniteInduction.html": "Transfinite Induction",
                "https://mathworld.wolfram.com/GoedelsIncompletenessTheorem.html": "Goedel's Incompleteness Theorem",
                "https://mathworld.wolfram.com/Decidability.html": "Decidability",
                "https://mathworld.wolfram.com/Computability.html": "Computability",
                "https://mathworld.wolfram.com/ChurchTuringThesis.html": "Church-Turing Thesis",
                "https://mathworld.wolfram.com/HaltingProblem.html": "Halting Problem",
                "https://mathworld.wolfram.com/LambdaCalculus.html": "Lambda Calculus",
                "https://mathworld.wolfram.com/Proof.html": "Proof",
                "https://mathworld.wolfram.com/ProofbyContradiction.html": "Proof by Contradiction",
                "https://mathworld.wolfram.com/DirectProof.html": "Direct Proof",
                "https://mathworld.wolfram.com/Contrapositive.html": "Contrapositive",
                "https://mathworld.wolfram.com/Axiom.html": "Axiom",
                "https://mathworld.wolfram.com/Theorem.html": "Theorem",
                "https://mathworld.wolfram.com/Lemma.html": "Lemma",
                "https://mathworld.wolfram.com/Corollary.html": "Corollary",
                "https://mathworld.wolfram.com/Conjecture.html": "Conjecture",
                "https://mathworld.wolfram.com/CategoryTheory.html": "Category Theory",
                "https://mathworld.wolfram.com/Functor.html": "Functor",
                "https://mathworld.wolfram.com/NaturalTransformation.html": "Natural Transformation",
                "https://mathworld.wolfram.com/Monad.html": "Monad",
                "https://mathworld.wolfram.com/PeanoAxioms.html": "Peano Axioms",
                "https://mathworld.wolfram.com/Consistency.html": "Consistency",
                "https://mathworld.wolfram.com/Completeness.html": "Completeness",
                "https://mathworld.wolfram.com/Soundness.html": "Soundness",
                "https://mathworld.wolfram.com/ModelTheory.html": "Model Theory",
                "https://mathworld.wolfram.com/ProofTheory.html": "Proof Theory",
                "https://mathworld.wolfram.com/RecursionTheory.html": "Recursion Theory",
                "https://mathworld.wolfram.com/RecursiveFunction.html": "Recursive Function",
                "https://mathworld.wolfram.com/ComputableFunction.html": "Computable Function",
                "https://mathworld.wolfram.com/Aleph.html": "Aleph",
                "https://mathworld.wolfram.com/Beth.html": "Beth",
                "https://mathworld.wolfram.com/ConstructibleUniverse.html": "Constructible Universe",
                "https://mathworld.wolfram.com/ForcingMethod.html": "Forcing Method",
                "https://mathworld.wolfram.com/LargeCardinal.html": "Large Cardinal",
                "https://mathworld.wolfram.com/NaiveSetTheory.html": "Naive Set Theory",
                "https://mathworld.wolfram.com/RussellsParadox.html": "Russell's Paradox",
                "https://mathworld.wolfram.com/Adjunction.html": "Adjunction",
                "https://mathworld.wolfram.com/Topos.html": "Topos",
                "https://mathworld.wolfram.com/YonedaLemma.html": "Yoneda Lemma",
                "https://mathworld.wolfram.com/Morphism.html": "Morphism",
                "https://mathworld.wolfram.com/Product.html": "Product",
                "https://mathworld.wolfram.com/Coproduct.html": "Coproduct",
                "https://mathworld.wolfram.com/Limit.html": "Limit (Category Theory)",
                "https://mathworld.wolfram.com/Colimit.html": "Colimit",
            },
        },
        "geometry": {
            "pages": {
                "https://mathworld.wolfram.com/Geometry.html": "Geometry",
                "https://mathworld.wolfram.com/EuclideanGeometry.html": "Euclidean Geometry",
                "https://mathworld.wolfram.com/Triangle.html": "Triangle",
                "https://mathworld.wolfram.com/Circle.html": "Circle",
                "https://mathworld.wolfram.com/Polygon.html": "Polygon",
                "https://mathworld.wolfram.com/Square.html": "Square",
                "https://mathworld.wolfram.com/Rectangle.html": "Rectangle",
                "https://mathworld.wolfram.com/Parallelogram.html": "Parallelogram",
                "https://mathworld.wolfram.com/Trapezoid.html": "Trapezoid",
                "https://mathworld.wolfram.com/Rhombus.html": "Rhombus",
                "https://mathworld.wolfram.com/RegularPolygon.html": "Regular Polygon",
                "https://mathworld.wolfram.com/Pentagon.html": "Pentagon",
                "https://mathworld.wolfram.com/Hexagon.html": "Hexagon",
                "https://mathworld.wolfram.com/Ellipse.html": "Ellipse",
                "https://mathworld.wolfram.com/Parabola.html": "Parabola",
                "https://mathworld.wolfram.com/Hyperbola.html": "Hyperbola",
                "https://mathworld.wolfram.com/ConicSection.html": "Conic Section",
                "https://mathworld.wolfram.com/Sphere.html": "Sphere",
                "https://mathworld.wolfram.com/Cylinder.html": "Cylinder",
                "https://mathworld.wolfram.com/Cone.html": "Cone",
                "https://mathworld.wolfram.com/Torus.html": "Torus",
                "https://mathworld.wolfram.com/Polyhedron.html": "Polyhedron",
                "https://mathworld.wolfram.com/Tetrahedron.html": "Tetrahedron",
                "https://mathworld.wolfram.com/Cube.html": "Cube",
                "https://mathworld.wolfram.com/Octahedron.html": "Octahedron",
                "https://mathworld.wolfram.com/Dodecahedron.html": "Dodecahedron",
                "https://mathworld.wolfram.com/Icosahedron.html": "Icosahedron",
                "https://mathworld.wolfram.com/PlatonicSolid.html": "Platonic Solid",
                "https://mathworld.wolfram.com/PythagoreanTheorem.html": "Pythagorean Theorem",
                "https://mathworld.wolfram.com/Trigonometry.html": "Trigonometry",
                "https://mathworld.wolfram.com/Sine.html": "Sine",
                "https://mathworld.wolfram.com/Cosine.html": "Cosine",
                "https://mathworld.wolfram.com/Tangent.html": "Tangent",
                "https://mathworld.wolfram.com/InverseTrigonometricFunctions.html": "Inverse Trigonometric Functions",
                "https://mathworld.wolfram.com/HyperbolicFunctions.html": "Hyperbolic Functions",
                "https://mathworld.wolfram.com/Angle.html": "Angle",
                "https://mathworld.wolfram.com/Area.html": "Area",
                "https://mathworld.wolfram.com/Perimeter.html": "Perimeter",
                "https://mathworld.wolfram.com/Centroid.html": "Centroid",
                "https://mathworld.wolfram.com/Circumscribed.html": "Circumscribed",
                "https://mathworld.wolfram.com/Inscribed.html": "Inscribed",
                "https://mathworld.wolfram.com/Bisector.html": "Bisector",
                "https://mathworld.wolfram.com/Median.html": "Median",
                "https://mathworld.wolfram.com/Altitude.html": "Altitude",
                "https://mathworld.wolfram.com/Similarity.html": "Similarity",
                "https://mathworld.wolfram.com/Transformation.html": "Transformation",
                "https://mathworld.wolfram.com/Rotation.html": "Rotation",
                "https://mathworld.wolfram.com/Reflection.html": "Reflection",
                "https://mathworld.wolfram.com/Translation.html": "Translation",
                "https://mathworld.wolfram.com/Dilation.html": "Dilation",
                "https://mathworld.wolfram.com/AffineTransformation.html": "Affine Transformation",
                "https://mathworld.wolfram.com/ProjectiveGeometry.html": "Projective Geometry",
                "https://mathworld.wolfram.com/DifferentialGeometry.html": "Differential Geometry",
                "https://mathworld.wolfram.com/RiemannianGeometry.html": "Riemannian Geometry",
                "https://mathworld.wolfram.com/GaussianCurvature.html": "Gaussian Curvature",
                "https://mathworld.wolfram.com/GeodesicCurvature.html": "Geodesic Curvature",
                "https://mathworld.wolfram.com/Manifold.html": "Manifold",
                "https://mathworld.wolfram.com/TangentSpace.html": "Tangent Space",
                "https://mathworld.wolfram.com/FractalGeometry.html": "Fractal Geometry",
                "https://mathworld.wolfram.com/MandelbrotSet.html": "Mandelbrot Set",
                "https://mathworld.wolfram.com/JuliaSet.html": "Julia Set",
                "https://mathworld.wolfram.com/SierpinskiTriangle.html": "Sierpinski Triangle",
                "https://mathworld.wolfram.com/KochSnowflake.html": "Koch Snowflake",
                "https://mathworld.wolfram.com/FractalDimension.html": "Fractal Dimension",
                "https://mathworld.wolfram.com/HyperbolicGeometry.html": "Hyperbolic Geometry",
                "https://mathworld.wolfram.com/NonEuclideanGeometry.html": "Non-Euclidean Geometry",
                "https://mathworld.wolfram.com/SphericalGeometry.html": "Spherical Geometry",
                "https://mathworld.wolfram.com/Circumcircle.html": "Circumcircle",
                "https://mathworld.wolfram.com/Incircle.html": "Incircle",
                "https://mathworld.wolfram.com/Orthocenter.html": "Orthocenter",
                "https://mathworld.wolfram.com/Circumcenter.html": "Circumcenter",
                "https://mathworld.wolfram.com/EulerLine.html": "Euler Line",
                "https://mathworld.wolfram.com/NinePointCircle.html": "Nine-Point Circle",
                "https://mathworld.wolfram.com/CevasTheorem.html": "Ceva's Theorem",
                "https://mathworld.wolfram.com/MenelausTheorem.html": "Menelaus' Theorem",
                "https://mathworld.wolfram.com/StewartsTheorem.html": "Stewart's Theorem",
                "https://mathworld.wolfram.com/HeronsFormula.html": "Heron's Formula",
                "https://mathworld.wolfram.com/LawofCosines.html": "Law of Cosines",
                "https://mathworld.wolfram.com/LawofSines.html": "Law of Sines",
                "https://mathworld.wolfram.com/Quadrilateral.html": "Quadrilateral",
                "https://mathworld.wolfram.com/ConvexHull.html": "Convex Hull",
                "https://mathworld.wolfram.com/Convexity.html": "Convexity",
                "https://mathworld.wolfram.com/VoronoiDiagram.html": "Voronoi Diagram",
                "https://mathworld.wolfram.com/DelaunayTriangulation.html": "Delaunay Triangulation",
                "https://mathworld.wolfram.com/GeodesicLine.html": "Geodesic Line",
                "https://mathworld.wolfram.com/MinimalSurface.html": "Minimal Surface",
                "https://mathworld.wolfram.com/RiemannSurface.html": "Riemann Surface",
                "https://mathworld.wolfram.com/GaussBonnetTheorem.html": "Gauss-Bonnet Theorem",
                "https://mathworld.wolfram.com/ParallelTransport.html": "Parallel Transport",
                "https://mathworld.wolfram.com/ChristoffelSymbol.html": "Christoffel Symbol",
                "https://mathworld.wolfram.com/RiemannianMetric.html": "Riemannian Metric",
                "https://mathworld.wolfram.com/ArchimedeanSolid.html": "Archimedean Solid",
                "https://mathworld.wolfram.com/Prism.html": "Prism",
                "https://mathworld.wolfram.com/Antiprism.html": "Antiprism",
                "https://mathworld.wolfram.com/Frustum.html": "Frustum",
                "https://mathworld.wolfram.com/GreatCircle.html": "Great Circle",
                "https://mathworld.wolfram.com/Stereographic.html": "Stereographic Projection",
                "https://mathworld.wolfram.com/Isometry.html": "Isometry",
                "https://mathworld.wolfram.com/SymmetryGroup.html": "Symmetry Group",
                "https://mathworld.wolfram.com/WallpaperGroup.html": "Wallpaper Group",
                "https://mathworld.wolfram.com/Frieze.html": "Frieze Group",
                "https://mathworld.wolfram.com/PointGroup.html": "Point Group",
            },
        },
        "number-theory": {
            "pages": {
                "https://mathworld.wolfram.com/NumberTheory.html": "Number Theory",
                "https://mathworld.wolfram.com/PrimeNumber.html": "Prime Number",
                "https://mathworld.wolfram.com/FundamentalTheoremofArithmetic.html": "Fundamental Theorem of Arithmetic",
                "https://mathworld.wolfram.com/SieveofEratosthenes.html": "Sieve of Eratosthenes",
                "https://mathworld.wolfram.com/PrimeCountingFunction.html": "Prime Counting Function",
                "https://mathworld.wolfram.com/PrimeNumberTheorem.html": "Prime Number Theorem",
                "https://mathworld.wolfram.com/TwinPrime.html": "Twin Prime",
                "https://mathworld.wolfram.com/MersennePrime.html": "Mersenne Prime",
                "https://mathworld.wolfram.com/GoldbachsConjecture.html": "Goldbach's Conjecture",
                "https://mathworld.wolfram.com/RiemannHypothesis.html": "Riemann Hypothesis",
                "https://mathworld.wolfram.com/EulersTotientFunction.html": "Euler's Totient Function",
                "https://mathworld.wolfram.com/FermatsLittleTheorem.html": "Fermat's Little Theorem",
                "https://mathworld.wolfram.com/EulersTheorem.html": "Euler's Theorem",
                "https://mathworld.wolfram.com/WilsonsTheorem.html": "Wilson's Theorem",
                "https://mathworld.wolfram.com/GreatestCommonDivisor.html": "Greatest Common Divisor",
                "https://mathworld.wolfram.com/LeastCommonMultiple.html": "Least Common Multiple",
                "https://mathworld.wolfram.com/EuclideanAlgorithm.html": "Euclidean Algorithm",
                "https://mathworld.wolfram.com/Divisor.html": "Divisor",
                "https://mathworld.wolfram.com/DivisorFunction.html": "Divisor Function",
                "https://mathworld.wolfram.com/PerfectNumber.html": "Perfect Number",
                "https://mathworld.wolfram.com/AmicableNumbers.html": "Amicable Numbers",
                "https://mathworld.wolfram.com/PrimitiveRoot.html": "Primitive Root",
                "https://mathworld.wolfram.com/QuadraticResidue.html": "Quadratic Residue",
                "https://mathworld.wolfram.com/LegendreSymbol.html": "Legendre Symbol",
                "https://mathworld.wolfram.com/QuadraticReciprocity.html": "Quadratic Reciprocity",
                "https://mathworld.wolfram.com/ContinuedFraction.html": "Continued Fraction",
                "https://mathworld.wolfram.com/PellEquation.html": "Pell Equation",
                "https://mathworld.wolfram.com/DiophantineEquation.html": "Diophantine Equation",
                "https://mathworld.wolfram.com/FermatsLastTheorem.html": "Fermat's Last Theorem",
                "https://mathworld.wolfram.com/PythagoreanTriple.html": "Pythagorean Triple",
                "https://mathworld.wolfram.com/MobiusFunction.html": "Mobius Function",
                "https://mathworld.wolfram.com/MobiusInversionFormula.html": "Mobius Inversion Formula",
                "https://mathworld.wolfram.com/ArithmeticFunction.html": "Arithmetic Function",
                "https://mathworld.wolfram.com/MultiplicativeFunction.html": "Multiplicative Function",
                "https://mathworld.wolfram.com/LiouvilleFunction.html": "Liouville Function",
                "https://mathworld.wolfram.com/VonMangoldtFunction.html": "Von Mangoldt Function",
                "https://mathworld.wolfram.com/AlgebraicNumber.html": "Algebraic Number",
                "https://mathworld.wolfram.com/TranscendentalNumber.html": "Transcendental Number",
                "https://mathworld.wolfram.com/Pi.html": "Pi",
                "https://mathworld.wolfram.com/e.html": "e (Euler's Number)",
                "https://mathworld.wolfram.com/GoldenRatio.html": "Golden Ratio",
                "https://mathworld.wolfram.com/IrrationalNumber.html": "Irrational Number",
                "https://mathworld.wolfram.com/RationalNumber.html": "Rational Number",
                "https://mathworld.wolfram.com/Integer.html": "Integer",
                "https://mathworld.wolfram.com/NaturalNumber.html": "Natural Number",
                "https://mathworld.wolfram.com/RealNumber.html": "Real Number",
                "https://mathworld.wolfram.com/pAdicNumber.html": "p-Adic Number",
                "https://mathworld.wolfram.com/AlgebraicNumberField.html": "Algebraic Number Field",
                "https://mathworld.wolfram.com/Factorization.html": "Factorization",
                "https://mathworld.wolfram.com/RSAEncryption.html": "RSA Encryption",
                "https://mathworld.wolfram.com/AbundantNumber.html": "Abundant Number",
                "https://mathworld.wolfram.com/DeficientNumber.html": "Deficient Number",
                "https://mathworld.wolfram.com/HighlyCompositeNumber.html": "Highly Composite Number",
                "https://mathworld.wolfram.com/SmoothNumber.html": "Smooth Number",
                "https://mathworld.wolfram.com/SquarefreeNumber.html": "Squarefree Number",
                "https://mathworld.wolfram.com/PrimorialPrime.html": "Primorial Prime",
                "https://mathworld.wolfram.com/SophieGermainPrime.html": "Sophie Germain Prime",
                "https://mathworld.wolfram.com/SafePrime.html": "Safe Prime",
                "https://mathworld.wolfram.com/FermatNumber.html": "Fermat Number",
                "https://mathworld.wolfram.com/LucasNumber.html": "Lucas Number",
                "https://mathworld.wolfram.com/TriangularNumber.html": "Triangular Number",
                "https://mathworld.wolfram.com/SquareNumber.html": "Square Number",
                "https://mathworld.wolfram.com/PentagonalNumber.html": "Pentagonal Number",
                "https://mathworld.wolfram.com/Factorial.html": "Factorial",
                "https://mathworld.wolfram.com/BernoulliNumber.html": "Bernoulli Number",
                "https://mathworld.wolfram.com/EulerNumber.html": "Euler Number",
                "https://mathworld.wolfram.com/HarmonicNumber.html": "Harmonic Number",
                "https://mathworld.wolfram.com/HarmonicSeries.html": "Harmonic Series",
                "https://mathworld.wolfram.com/DirichletSeries.html": "Dirichlet Series",
                "https://mathworld.wolfram.com/DirichletCharacter.html": "Dirichlet Character",
                "https://mathworld.wolfram.com/DirichletLFunction.html": "Dirichlet L-Function",
                "https://mathworld.wolfram.com/DirichletsTheorem.html": "Dirichlet's Theorem",
                "https://mathworld.wolfram.com/MillerRabinTest.html": "Miller-Rabin Test",
                "https://mathworld.wolfram.com/SumofDivisorsFunction.html": "Sum of Divisors Function",
                "https://mathworld.wolfram.com/JacobiSymbol.html": "Jacobi Symbol",
                "https://mathworld.wolfram.com/KroneckerSymbol.html": "Kronecker Symbol",
                "https://mathworld.wolfram.com/GaussianInteger.html": "Gaussian Integer",
                "https://mathworld.wolfram.com/EisensteinInteger.html": "Eisenstein Integer",
                "https://mathworld.wolfram.com/Norm.html": "Norm (Number Theory)",
                "https://mathworld.wolfram.com/IdealClass.html": "Ideal Class",
                "https://mathworld.wolfram.com/ClassNumber.html": "Class Number",
                "https://mathworld.wolfram.com/Discriminant.html": "Discriminant",
                "https://mathworld.wolfram.com/MinkowskiBound.html": "Minkowski Bound",
            },
        },
        "probability-statistics": {
            "pages": {
                "https://mathworld.wolfram.com/Probability.html": "Probability",
                "https://mathworld.wolfram.com/Statistics.html": "Statistics",
                "https://mathworld.wolfram.com/ProbabilityDistribution.html": "Probability Distribution",
                "https://mathworld.wolfram.com/NormalDistribution.html": "Normal Distribution",
                "https://mathworld.wolfram.com/StandardNormalDistribution.html": "Standard Normal Distribution",
                "https://mathworld.wolfram.com/BinomialDistribution.html": "Binomial Distribution",
                "https://mathworld.wolfram.com/PoissonDistribution.html": "Poisson Distribution",
                "https://mathworld.wolfram.com/ExponentialDistribution.html": "Exponential Distribution",
                "https://mathworld.wolfram.com/UniformDistribution.html": "Uniform Distribution",
                "https://mathworld.wolfram.com/GeometricDistribution.html": "Geometric Distribution",
                "https://mathworld.wolfram.com/BernoulliDistribution.html": "Bernoulli Distribution",
                "https://mathworld.wolfram.com/ChiSquaredDistribution.html": "Chi-Squared Distribution",
                "https://mathworld.wolfram.com/StudentstDistribution.html": "Student's t-Distribution",
                "https://mathworld.wolfram.com/FDistribution.html": "F-Distribution",
                "https://mathworld.wolfram.com/GammaDistribution.html": "Gamma Distribution",
                "https://mathworld.wolfram.com/BetaDistribution.html": "Beta Distribution",
                "https://mathworld.wolfram.com/WeibullDistribution.html": "Weibull Distribution",
                "https://mathworld.wolfram.com/LogNormalDistribution.html": "Log-Normal Distribution",
                "https://mathworld.wolfram.com/MultivariateNormalDistribution.html": "Multivariate Normal Distribution",
                "https://mathworld.wolfram.com/CauchyDistribution.html": "Cauchy Distribution",
                "https://mathworld.wolfram.com/DirichletDistribution.html": "Dirichlet Distribution",
                "https://mathworld.wolfram.com/HypergeometricDistribution.html": "Hypergeometric Distribution",
                "https://mathworld.wolfram.com/NegativeBinomialDistribution.html": "Negative Binomial Distribution",
                "https://mathworld.wolfram.com/MultinomialDistribution.html": "Multinomial Distribution",
                "https://mathworld.wolfram.com/Mean.html": "Mean",
                "https://mathworld.wolfram.com/Variance.html": "Variance",
                "https://mathworld.wolfram.com/StandardDeviation.html": "Standard Deviation",
                "https://mathworld.wolfram.com/Covariance.html": "Covariance",
                "https://mathworld.wolfram.com/Correlation.html": "Correlation",
                "https://mathworld.wolfram.com/ExpectedValue.html": "Expected Value",
                "https://mathworld.wolfram.com/Mode.html": "Mode",
                "https://mathworld.wolfram.com/Skewness.html": "Skewness",
                "https://mathworld.wolfram.com/Kurtosis.html": "Kurtosis",
                "https://mathworld.wolfram.com/MomentGeneratingFunction.html": "Moment Generating Function",
                "https://mathworld.wolfram.com/CharacteristicFunction.html": "Characteristic Function",
                "https://mathworld.wolfram.com/CentralLimitTheorem.html": "Central Limit Theorem",
                "https://mathworld.wolfram.com/LawofLargeNumbers.html": "Law of Large Numbers",
                "https://mathworld.wolfram.com/BayesTheorem.html": "Bayes' Theorem",
                "https://mathworld.wolfram.com/ConditionalProbability.html": "Conditional Probability",
                "https://mathworld.wolfram.com/JointDistribution.html": "Joint Distribution",
                "https://mathworld.wolfram.com/MarginalDistribution.html": "Marginal Distribution",
                "https://mathworld.wolfram.com/MaximumLikelihood.html": "Maximum Likelihood",
                "https://mathworld.wolfram.com/Estimator.html": "Estimator",
                "https://mathworld.wolfram.com/ConfidenceInterval.html": "Confidence Interval",
                "https://mathworld.wolfram.com/HypothesisTest.html": "Hypothesis Test",
                "https://mathworld.wolfram.com/pValue.html": "p-Value",
                "https://mathworld.wolfram.com/ChiSquaredTest.html": "Chi-Squared Test",
                "https://mathworld.wolfram.com/tTest.html": "t-Test",
                "https://mathworld.wolfram.com/ANOVA.html": "ANOVA",
                "https://mathworld.wolfram.com/LinearRegression.html": "Linear Regression",
                "https://mathworld.wolfram.com/LeastSquares.html": "Least Squares",
                "https://mathworld.wolfram.com/Regression.html": "Regression",
                "https://mathworld.wolfram.com/PrincipalComponentAnalysis.html": "Principal Component Analysis",
                "https://mathworld.wolfram.com/RandomVariable.html": "Random Variable",
                "https://mathworld.wolfram.com/RandomWalk.html": "Random Walk",
                "https://mathworld.wolfram.com/MarkovChain.html": "Markov Chain",
                "https://mathworld.wolfram.com/StochasticProcess.html": "Stochastic Process",
                "https://mathworld.wolfram.com/BrownianMotion.html": "Brownian Motion",
                "https://mathworld.wolfram.com/PoissonProcess.html": "Poisson Process",
                "https://mathworld.wolfram.com/MonteCarlo.html": "Monte Carlo",
                "https://mathworld.wolfram.com/Entropy.html": "Entropy",
                "https://mathworld.wolfram.com/InformationTheory.html": "Information Theory",
                "https://mathworld.wolfram.com/Percentile.html": "Percentile",
                "https://mathworld.wolfram.com/Quartile.html": "Quartile",
                "https://mathworld.wolfram.com/BoxPlot.html": "Box Plot",
                "https://mathworld.wolfram.com/SampleSpace.html": "Sample Space",
                "https://mathworld.wolfram.com/CumulativeDistributionFunction.html": "Cumulative Distribution Function",
                "https://mathworld.wolfram.com/ProbabilityDensityFunction.html": "Probability Density Function",
                "https://mathworld.wolfram.com/ProbabilityMassFunction.html": "Probability Mass Function",
                "https://mathworld.wolfram.com/Moment.html": "Moment",
                "https://mathworld.wolfram.com/CentralMoment.html": "Central Moment",
                "https://mathworld.wolfram.com/Cumulant.html": "Cumulant",
                "https://mathworld.wolfram.com/SufficientStatistic.html": "Sufficient Statistic",
                "https://mathworld.wolfram.com/FisherInformation.html": "Fisher Information",
                "https://mathworld.wolfram.com/CramerRaoInequality.html": "Cramer-Rao Inequality",
                "https://mathworld.wolfram.com/RaoBlackwellTheorem.html": "Rao-Blackwell Theorem",
                "https://mathworld.wolfram.com/BayesianInference.html": "Bayesian Inference",
                "https://mathworld.wolfram.com/PriorDistribution.html": "Prior Distribution",
                "https://mathworld.wolfram.com/PosteriorDistribution.html": "Posterior Distribution",
                "https://mathworld.wolfram.com/ConjugatePrior.html": "Conjugate Prior",
                "https://mathworld.wolfram.com/KolmogorovSmirnovTest.html": "Kolmogorov-Smirnov Test",
                "https://mathworld.wolfram.com/MannWhitneyTest.html": "Mann-Whitney Test",
                "https://mathworld.wolfram.com/SignTest.html": "Sign Test",
                "https://mathworld.wolfram.com/BootstrapMethod.html": "Bootstrap Method",
                "https://mathworld.wolfram.com/Jackknife.html": "Jackknife",
                "https://mathworld.wolfram.com/WienerProcess.html": "Wiener Process",
                "https://mathworld.wolfram.com/MartingaleTheory.html": "Martingale Theory",
                "https://mathworld.wolfram.com/StochasticDifferentialEquation.html": "Stochastic Differential Equation",
                "https://mathworld.wolfram.com/ErgodicTheory.html": "Ergodic Theory",
                "https://mathworld.wolfram.com/KullbackLeiblerDivergence.html": "Kullback-Leibler Divergence",
                "https://mathworld.wolfram.com/MutualInformation.html": "Mutual Information",
                "https://mathworld.wolfram.com/Copula.html": "Copula",
                "https://mathworld.wolfram.com/OrderStatistic.html": "Order Statistic",
                "https://mathworld.wolfram.com/ExtremeValueDistribution.html": "Extreme Value Distribution",
                "https://mathworld.wolfram.com/ParettoDistribution.html": "Pareto Distribution",
                "https://mathworld.wolfram.com/StableDistribution.html": "Stable Distribution",
            },
        },
        "topology": {
            "pages": {
                "https://mathworld.wolfram.com/Topology.html": "Topology",
                "https://mathworld.wolfram.com/TopologicalSpace.html": "Topological Space",
                "https://mathworld.wolfram.com/Neighborhood.html": "Neighborhood",
                "https://mathworld.wolfram.com/ContinuousFunction.html": "Continuous Function",
                "https://mathworld.wolfram.com/Homeomorphism.html": "Homeomorphism",
                "https://mathworld.wolfram.com/Compactness.html": "Compactness",
                "https://mathworld.wolfram.com/Connectedness.html": "Connectedness",
                "https://mathworld.wolfram.com/PathConnected.html": "Path Connected",
                "https://mathworld.wolfram.com/HausdorffSpace.html": "Hausdorff Space",
                "https://mathworld.wolfram.com/ProductTopology.html": "Product Topology",
                "https://mathworld.wolfram.com/QuotientSpace.html": "Quotient Space",
                "https://mathworld.wolfram.com/SubspaceTopology.html": "Subspace Topology",
                "https://mathworld.wolfram.com/FundamentalGroup.html": "Fundamental Group",
                "https://mathworld.wolfram.com/CoveringSpace.html": "Covering Space",
                "https://mathworld.wolfram.com/HomologyGroup.html": "Homology Group",
                "https://mathworld.wolfram.com/CohomologyGroup.html": "Cohomology Group",
                "https://mathworld.wolfram.com/HomotopyGroup.html": "Homotopy Group",
                "https://mathworld.wolfram.com/EulerCharacteristic.html": "Euler Characteristic",
                "https://mathworld.wolfram.com/KleinBottle.html": "Klein Bottle",
                "https://mathworld.wolfram.com/MoebiusStrip.html": "Moebius Strip",
                "https://mathworld.wolfram.com/RealProjectivePlane.html": "Real Projective Plane",
                "https://mathworld.wolfram.com/Knot.html": "Knot",
                "https://mathworld.wolfram.com/KnotTheory.html": "Knot Theory",
                "https://mathworld.wolfram.com/BrouwerFixedPointTheorem.html": "Brouwer Fixed Point Theorem",
                "https://mathworld.wolfram.com/BorsukUlamTheorem.html": "Borsuk-Ulam Theorem",
                "https://mathworld.wolfram.com/TychonoffsTheorem.html": "Tychonoff's Theorem",
                "https://mathworld.wolfram.com/UrysohnsLemma.html": "Urysohn's Lemma",
                "https://mathworld.wolfram.com/MetrizationTheorem.html": "Metrization Theorem",
                "https://mathworld.wolfram.com/SimplicalComplex.html": "Simplicial Complex",
                "https://mathworld.wolfram.com/CWComplex.html": "CW Complex",
                "https://mathworld.wolfram.com/FiberBundle.html": "Fiber Bundle",
                "https://mathworld.wolfram.com/VectorBundle.html": "Vector Bundle",
                "https://mathworld.wolfram.com/Homotopy.html": "Homotopy",
                "https://mathworld.wolfram.com/HomotopyEquivalence.html": "Homotopy Equivalence",
                "https://mathworld.wolfram.com/Retract.html": "Retract",
                "https://mathworld.wolfram.com/DeformationRetract.html": "Deformation Retract",
                "https://mathworld.wolfram.com/SuspensionSpace.html": "Suspension",
                "https://mathworld.wolfram.com/WedgeSum.html": "Wedge Sum",
                "https://mathworld.wolfram.com/SmashProduct.html": "Smash Product",
                "https://mathworld.wolfram.com/MayerVietorisSequence.html": "Mayer-Vietoris Sequence",
                "https://mathworld.wolfram.com/ExactSequence.html": "Exact Sequence",
                "https://mathworld.wolfram.com/SingularHomology.html": "Singular Homology",
                "https://mathworld.wolfram.com/DeRhamCohomology.html": "De Rham Cohomology",
                "https://mathworld.wolfram.com/Orientability.html": "Orientability",
                "https://mathworld.wolfram.com/Genus.html": "Genus",
                "https://mathworld.wolfram.com/ClassificationofSurfaces.html": "Classification of Surfaces",
                "https://mathworld.wolfram.com/PoincareConjecture.html": "Poincare Conjecture",
                "https://mathworld.wolfram.com/PoincareDuality.html": "Poincare Duality",
                "https://mathworld.wolfram.com/LefschtezFixedPointTheorem.html": "Lefschetz Fixed Point Theorem",
                "https://mathworld.wolfram.com/JonesPolynomial.html": "Jones Polynomial",
                "https://mathworld.wolfram.com/AlexanderPolynomial.html": "Alexander Polynomial",
                "https://mathworld.wolfram.com/BettiNumber.html": "Betti Number",
                "https://mathworld.wolfram.com/TorsionSubgroup.html": "Torsion Subgroup",
                "https://mathworld.wolfram.com/SheafTheory.html": "Sheaf Theory",
                "https://mathworld.wolfram.com/NormalSpace.html": "Normal Space",
                "https://mathworld.wolfram.com/RegularSpace.html": "Regular Space",
                "https://mathworld.wolfram.com/ParacompactSpace.html": "Paracompact Space",
                "https://mathworld.wolfram.com/LocallyCompactSpace.html": "Locally Compact Space",
                "https://mathworld.wolfram.com/SecondCountable.html": "Second Countable",
                "https://mathworld.wolfram.com/SeparableSpace.html": "Separable Space",
            },
        },
        "applied-math": {
            "pages": {
                "https://mathworld.wolfram.com/AppliedMathematics.html": "Applied Mathematics",
                "https://mathworld.wolfram.com/NumericalAnalysis.html": "Numerical Analysis",
                "https://mathworld.wolfram.com/LinearProgramming.html": "Linear Programming",
                "https://mathworld.wolfram.com/Optimization.html": "Optimization",
                "https://mathworld.wolfram.com/ConvexOptimization.html": "Convex Optimization",
                "https://mathworld.wolfram.com/GradientDescent.html": "Gradient Descent",
                "https://mathworld.wolfram.com/NewtonsMethod.html": "Newton's Method",
                "https://mathworld.wolfram.com/BisectionMethod.html": "Bisection Method",
                "https://mathworld.wolfram.com/SecantMethod.html": "Secant Method",
                "https://mathworld.wolfram.com/FixedPointIteration.html": "Fixed Point Iteration",
                "https://mathworld.wolfram.com/GaussianElimination.html": "Gaussian Elimination",
                "https://mathworld.wolfram.com/GaussSeidelMethod.html": "Gauss-Seidel Method",
                "https://mathworld.wolfram.com/JacobiMethod.html": "Jacobi Method",
                "https://mathworld.wolfram.com/ConjugateGradientMethod.html": "Conjugate Gradient Method",
                "https://mathworld.wolfram.com/Interpolation.html": "Interpolation",
                "https://mathworld.wolfram.com/LagrangeInterpolation.html": "Lagrange Interpolation",
                "https://mathworld.wolfram.com/NewtonInterpolation.html": "Newton Interpolation",
                "https://mathworld.wolfram.com/SplineInterpolation.html": "Spline Interpolation",
                "https://mathworld.wolfram.com/NumericalIntegration.html": "Numerical Integration",
                "https://mathworld.wolfram.com/SimpsonRule.html": "Simpson's Rule",
                "https://mathworld.wolfram.com/TrapezoidalRule.html": "Trapezoidal Rule",
                "https://mathworld.wolfram.com/GaussianQuadrature.html": "Gaussian Quadrature",
                "https://mathworld.wolfram.com/RungeKuttaMethod.html": "Runge-Kutta Method",
                "https://mathworld.wolfram.com/EulersMethod.html": "Euler's Method",
                "https://mathworld.wolfram.com/FiniteDifferenceMethod.html": "Finite Difference Method",
                "https://mathworld.wolfram.com/FiniteElementMethod.html": "Finite Element Method",
                "https://mathworld.wolfram.com/FastFourierTransform.html": "Fast Fourier Transform",
                "https://mathworld.wolfram.com/DiscreteFourierTransform.html": "Discrete Fourier Transform",
                "https://mathworld.wolfram.com/Wavelet.html": "Wavelet",
                "https://mathworld.wolfram.com/SignalProcessing.html": "Signal Processing",
                "https://mathworld.wolfram.com/DynamicalSystem.html": "Dynamical System",
                "https://mathworld.wolfram.com/ChaosTheory.html": "Chaos Theory",
                "https://mathworld.wolfram.com/LyapunovExponent.html": "Lyapunov Exponent",
                "https://mathworld.wolfram.com/Attractor.html": "Attractor",
                "https://mathworld.wolfram.com/LorenzAttractor.html": "Lorenz Attractor",
                "https://mathworld.wolfram.com/Bifurcation.html": "Bifurcation",
                "https://mathworld.wolfram.com/LogisticMap.html": "Logistic Map",
                "https://mathworld.wolfram.com/GameTheory.html": "Game Theory",
                "https://mathworld.wolfram.com/NashEquilibrium.html": "Nash Equilibrium",
                "https://mathworld.wolfram.com/PrisonersDilemma.html": "Prisoner's Dilemma",
                "https://mathworld.wolfram.com/ZeroSumGame.html": "Zero-Sum Game",
                "https://mathworld.wolfram.com/CryptographicHashFunction.html": "Cryptographic Hash Function",
                "https://mathworld.wolfram.com/HuffmanCoding.html": "Huffman Coding",
                "https://mathworld.wolfram.com/ErrorCorrectingCode.html": "Error-Correcting Code",
                "https://mathworld.wolfram.com/HammingCode.html": "Hamming Code",
                "https://mathworld.wolfram.com/NeuralNetwork.html": "Neural Network",
                "https://mathworld.wolfram.com/GeneticAlgorithm.html": "Genetic Algorithm",
                "https://mathworld.wolfram.com/SimulatedAnnealing.html": "Simulated Annealing",
                "https://mathworld.wolfram.com/MachineLearning.html": "Machine Learning",
                "https://mathworld.wolfram.com/ConditionNumber.html": "Condition Number",
                "https://mathworld.wolfram.com/RoundoffError.html": "Roundoff Error",
                "https://mathworld.wolfram.com/TruncationError.html": "Truncation Error",
                "https://mathworld.wolfram.com/Stability.html": "Stability",
                "https://mathworld.wolfram.com/StiffEquation.html": "Stiff Equation",
                "https://mathworld.wolfram.com/AdaptiveQuadrature.html": "Adaptive Quadrature",
                "https://mathworld.wolfram.com/RombergIntegration.html": "Romberg Integration",
                "https://mathworld.wolfram.com/RichardsonExtrapolation.html": "Richardson Extrapolation",
                "https://mathworld.wolfram.com/PowerMethod.html": "Power Method",
                "https://mathworld.wolfram.com/QRAlgorithm.html": "QR Algorithm",
                "https://mathworld.wolfram.com/LeastSquaresFitting.html": "Least Squares Fitting",
                "https://mathworld.wolfram.com/CurveFitting.html": "Curve Fitting",
                "https://mathworld.wolfram.com/SimplexMethod.html": "Simplex Method",
                "https://mathworld.wolfram.com/DualityTheory.html": "Duality Theory",
                "https://mathworld.wolfram.com/IntegerProgramming.html": "Integer Programming",
                "https://mathworld.wolfram.com/DynamicProgramming.html": "Dynamic Programming",
                "https://mathworld.wolfram.com/GreedyAlgorithm.html": "Greedy Algorithm",
                "https://mathworld.wolfram.com/BranchAndBound.html": "Branch and Bound",
                "https://mathworld.wolfram.com/ControlTheory.html": "Control Theory",
                "https://mathworld.wolfram.com/FeedbackControl.html": "Feedback Control",
                "https://mathworld.wolfram.com/TransferFunction.html": "Transfer Function",
                "https://mathworld.wolfram.com/StabilityTheory.html": "Stability Theory",
                "https://mathworld.wolfram.com/LimitCycle.html": "Limit Cycle",
                "https://mathworld.wolfram.com/PhasePortrait.html": "Phase Portrait",
                "https://mathworld.wolfram.com/FixedPoint.html": "Fixed Point",
                "https://mathworld.wolfram.com/PoincareBendixsonTheorem.html": "Poincare-Bendixson Theorem",
                "https://mathworld.wolfram.com/FloatingPointArithmetic.html": "Floating Point Arithmetic",
                "https://mathworld.wolfram.com/DiscreteConvolution.html": "Discrete Convolution",
                "https://mathworld.wolfram.com/Convolution.html": "Convolution",
                "https://mathworld.wolfram.com/CrossCorrelation.html": "Cross-Correlation",
                "https://mathworld.wolfram.com/Autocorrelation.html": "Autocorrelation",
                "https://mathworld.wolfram.com/SamplingTheorem.html": "Sampling Theorem",
                "https://mathworld.wolfram.com/NyquistFrequency.html": "Nyquist Frequency",
                "https://mathworld.wolfram.com/WindowFunction.html": "Window Function",
                "https://mathworld.wolfram.com/KalmanFilter.html": "Kalman Filter",
                "https://mathworld.wolfram.com/ParticleFilter.html": "Particle Filter",
            },
        },
        "recreational-math": {
            "pages": {
                "https://mathworld.wolfram.com/RecreationalMathematics.html": "Recreational Mathematics",
                "https://mathworld.wolfram.com/MagicSquare.html": "Magic Square",
                "https://mathworld.wolfram.com/Sudoku.html": "Sudoku",
                "https://mathworld.wolfram.com/Puzzle.html": "Puzzle",
                "https://mathworld.wolfram.com/TowersofHanoi.html": "Towers of Hanoi",
                "https://mathworld.wolfram.com/KnightsTour.html": "Knight's Tour",
                "https://mathworld.wolfram.com/RubiksCube.html": "Rubik's Cube",
                "https://mathworld.wolfram.com/Pentomino.html": "Pentomino",
                "https://mathworld.wolfram.com/Polyomino.html": "Polyomino",
                "https://mathworld.wolfram.com/Tangram.html": "Tangram",
                "https://mathworld.wolfram.com/Paradox.html": "Paradox",
                "https://mathworld.wolfram.com/ZenosParadoxes.html": "Zeno's Paradoxes",
                "https://mathworld.wolfram.com/BanachTarskiParadox.html": "Banach-Tarski Paradox",
                "https://mathworld.wolfram.com/BirthdayProblem.html": "Birthday Problem",
                "https://mathworld.wolfram.com/MontyHallProblem.html": "Monty Hall Problem",
                "https://mathworld.wolfram.com/GameofLife.html": "Game of Life",
                "https://mathworld.wolfram.com/CellularAutomaton.html": "Cellular Automaton",
                "https://mathworld.wolfram.com/CollatzProblem.html": "Collatz Problem",
                "https://mathworld.wolfram.com/Tessellation.html": "Tessellation",
                "https://mathworld.wolfram.com/PenroseTiling.html": "Penrose Tiling",
                "https://mathworld.wolfram.com/Fibonacci.html": "Fibonacci",
                "https://mathworld.wolfram.com/Palindrome.html": "Palindrome",
                "https://mathworld.wolfram.com/FourColorTheorem.html": "Four Color Theorem",
                "https://mathworld.wolfram.com/KoenigsbergBridgeProblem.html": "Koenigsberg Bridge Problem",
                "https://mathworld.wolfram.com/HappyNumber.html": "Happy Number",
                "https://mathworld.wolfram.com/NarcissisticNumber.html": "Narcissistic Number",
                "https://mathworld.wolfram.com/KaprekarNumber.html": "Kaprekar Number",
                "https://mathworld.wolfram.com/PalindromicNumber.html": "Palindromic Number",
                "https://mathworld.wolfram.com/Repunit.html": "Repunit",
                "https://mathworld.wolfram.com/SmithNumber.html": "Smith Number",
                "https://mathworld.wolfram.com/MathematicalGames.html": "Mathematical Games",
                "https://mathworld.wolfram.com/Nim.html": "Nim",
                "https://mathworld.wolfram.com/SpraguGrundyTheorem.html": "Sprague-Grundy Theorem",
                "https://mathworld.wolfram.com/Cryptarithmetic.html": "Cryptarithmetic",
                "https://mathworld.wolfram.com/FifteenPuzzle.html": "Fifteen Puzzle",
                "https://mathworld.wolfram.com/EightQueensProblem.html": "Eight Queens Problem",
                "https://mathworld.wolfram.com/Labyrinth.html": "Labyrinth",
                "https://mathworld.wolfram.com/Dissection.html": "Dissection",
                "https://mathworld.wolfram.com/Rep-Tile.html": "Rep-Tile",
                "https://mathworld.wolfram.com/Flexagon.html": "Flexagon",
                "https://mathworld.wolfram.com/SomasCube.html": "Soma Cube",
                "https://mathworld.wolfram.com/Origami.html": "Origami",
                "https://mathworld.wolfram.com/SquareRoot.html": "Square Root",
                "https://mathworld.wolfram.com/CubeRoot.html": "Cube Root",
                "https://mathworld.wolfram.com/Logarithm.html": "Logarithm",
                "https://mathworld.wolfram.com/NaturalLogarithm.html": "Natural Logarithm",
                "https://mathworld.wolfram.com/Exponent.html": "Exponent",
                "https://mathworld.wolfram.com/ScientificNotation.html": "Scientific Notation",
                "https://mathworld.wolfram.com/AbsoluteValue.html": "Absolute Value",
                "https://mathworld.wolfram.com/Floor.html": "Floor Function",
                "https://mathworld.wolfram.com/Ceiling.html": "Ceiling Function",
            },
        },
    }

    def __init__(self, base_dir, source_key=None):
        name = f"mathworld-{source_key}" if source_key else "mathworld"
        super().__init__(name, base_dir, interval_seconds=3600)
        self.source_key = source_key

    def _strip_html(self, html_content):
        """Remove HTML tags, scripts, styles and normalize whitespace."""
        text = html_content
        text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
        text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL)
        text = re.sub(r'<nav[^>]*>.*?</nav>', '', text, flags=re.DOTALL)
        text = re.sub(r'<footer[^>]*>.*?</footer>', '', text, flags=re.DOTALL)
        text = re.sub(r'<[^>]+>', ' ', text)
        text = html_mod.unescape(text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    def _extract_title(self, html_content, fallback):
        """Extract page title from HTML."""
        match = re.search(r'<title>([^<]+)</title>', html_content, re.IGNORECASE)
        if match:
            title = match.group(1).strip()
            for suffix in [' -- from Wolfram MathWorld', ' - Wolfram MathWorld', ' | Wolfram MathWorld']:
                if title.endswith(suffix):
                    title = title[:-len(suffix)].strip()
            return title
        return fallback

    def _scrape_source(self, source_key, config):
        """Scrape all pages for a given source section."""
        count = 0
        pages = config.get("pages", {})
        for url, title in pages.items():
            if not self.running:
                break
            item_id = self.make_id(url)
            content = self.fetch_url(url)
            if content and len(content) > 500:
                text = self._strip_html(content)
                if len(text) > 100:
                    page_title = self._extract_title(content, title)
                    if self.save_item(item_id, {
                        "title": page_title,
                        "content": text[:50000],
                        "url": url,
                        "category": f"mathworld-{source_key}",
                        "type": "documentation",
                    }):
                        count += 1
                        self.log.info(f"  {source_key}: {title}")
            time.sleep(2.0)
        return count

    def scrape(self):
        """Run scrape across all or a specific source."""
        total = 0
        if self.source_key:
            if self.source_key not in self.SOURCES:
                self.log.error(f"Unknown source key: {self.source_key}. Available: {list(self.SOURCES.keys())}")
                return 0
            sources = {self.source_key: self.SOURCES[self.source_key]}
        else:
            sources = self.SOURCES
        for key, config in sources.items():
            if not self.running:
                break
            self.log.info(f"=== Scraping mathworld/{key} ===")
            total += self._scrape_source(key, config)
        return total


if __name__ == "__main__":
    import os
    import sys
    base = os.path.expanduser("~")
    source_key = sys.argv[1] if len(sys.argv) > 1 else None
    MathWorldScraper(base, source_key).run()
