#!/usr/bin/env python3
"""NASA science and space exploration scraper.

Covers:
  - Solar system (planets, moons, asteroids, comets)
  - Universe (stars, galaxies, black holes, exoplanets)
  - Earth science (climate, oceans, atmosphere, natural hazards)
  - Missions (Hubble, JWST, Artemis, rovers, probes)
  - Technology (propulsion, robotics, communications, centers)
"""
import re
import time
import html as html_mod
from scraper_base import BaseScraper


class NASAScraper(BaseScraper):
    """NASA science and space exploration scraper. Solar system, universe, Earth science, missions, and technology."""

    SOURCES = {
        "solar-system": {
            "pages": {
                "https://science.nasa.gov/solar-system/": "Solar System Overview",
                "https://science.nasa.gov/sun/": "The Sun",
                "https://science.nasa.gov/sun/facts/": "Sun Facts",
                "https://science.nasa.gov/sun/solar-cycle/": "Solar Cycle",
                "https://science.nasa.gov/sun/sunspots/": "Sunspots",
                "https://science.nasa.gov/sun/solar-flares/": "Solar Flares",
                "https://science.nasa.gov/sun/coronal-mass-ejections/": "Coronal Mass Ejections",
                "https://science.nasa.gov/sun/solar-wind/": "Solar Wind",
                "https://science.nasa.gov/mercury/": "Mercury",
                "https://science.nasa.gov/mercury/facts/": "Mercury Facts",
                "https://science.nasa.gov/venus/": "Venus",
                "https://science.nasa.gov/venus/facts/": "Venus Facts",
                "https://science.nasa.gov/earth/": "Earth",
                "https://science.nasa.gov/earth/facts/": "Earth Facts",
                "https://science.nasa.gov/moon/": "The Moon",
                "https://science.nasa.gov/moon/facts/": "Moon Facts",
                "https://science.nasa.gov/moon/lunar-phases-eclipses/": "Lunar Phases and Eclipses",
                "https://science.nasa.gov/moon/apollo-missions/": "Apollo Missions",
                "https://science.nasa.gov/moon/in-depth/": "Moon In Depth",
                "https://science.nasa.gov/mars/": "Mars",
                "https://science.nasa.gov/mars/facts/": "Mars Facts",
                "https://science.nasa.gov/mars/mars-exploration/": "Mars Exploration",
                "https://science.nasa.gov/jupiter/": "Jupiter",
                "https://science.nasa.gov/jupiter/facts/": "Jupiter Facts",
                "https://science.nasa.gov/jupiter/jupiter-moons/": "Jupiter's Moons",
                "https://science.nasa.gov/jupiter/io/": "Io",
                "https://science.nasa.gov/jupiter/europa/": "Europa",
                "https://science.nasa.gov/jupiter/ganymede/": "Ganymede",
                "https://science.nasa.gov/jupiter/callisto/": "Callisto",
                "https://science.nasa.gov/saturn/": "Saturn",
                "https://science.nasa.gov/saturn/facts/": "Saturn Facts",
                "https://science.nasa.gov/saturn/saturn-moons/": "Saturn's Moons",
                "https://science.nasa.gov/saturn/titan/": "Titan",
                "https://science.nasa.gov/saturn/enceladus/": "Enceladus",
                "https://science.nasa.gov/saturn/saturn-rings/": "Saturn's Rings",
                "https://science.nasa.gov/uranus/": "Uranus",
                "https://science.nasa.gov/uranus/facts/": "Uranus Facts",
                "https://science.nasa.gov/uranus/uranus-moons/": "Uranus Moons",
                "https://science.nasa.gov/neptune/": "Neptune",
                "https://science.nasa.gov/neptune/facts/": "Neptune Facts",
                "https://science.nasa.gov/neptune/neptune-moons/": "Neptune Moons",
                "https://science.nasa.gov/neptune/triton/": "Triton",
                "https://science.nasa.gov/dwarf-planets/pluto/": "Pluto",
                "https://science.nasa.gov/dwarf-planets/pluto/facts/": "Pluto Facts",
                "https://science.nasa.gov/dwarf-planets/": "Dwarf Planets",
                "https://science.nasa.gov/dwarf-planets/ceres/": "Ceres",
                "https://science.nasa.gov/dwarf-planets/eris/": "Eris",
                "https://science.nasa.gov/dwarf-planets/makemake/": "Makemake",
                "https://science.nasa.gov/dwarf-planets/haumea/": "Haumea",
                "https://science.nasa.gov/asteroids/": "Asteroids",
                "https://science.nasa.gov/asteroids/facts/": "Asteroid Facts",
                "https://science.nasa.gov/asteroids/asteroid-belt/": "Asteroid Belt",
                "https://science.nasa.gov/asteroids/near-earth-asteroids/": "Near-Earth Asteroids",
                "https://science.nasa.gov/asteroids/trojan-asteroids/": "Trojan Asteroids",
                "https://science.nasa.gov/comets/": "Comets",
                "https://science.nasa.gov/comets/facts/": "Comet Facts",
                "https://science.nasa.gov/comets/halleys-comet/": "Halley's Comet",
                "https://science.nasa.gov/solar-system/kuiper-belt/": "Kuiper Belt",
                "https://science.nasa.gov/solar-system/oort-cloud/": "Oort Cloud",
                "https://science.nasa.gov/meteors/": "Meteors and Meteorites",
                "https://science.nasa.gov/meteors/facts/": "Meteor Facts",
                "https://science.nasa.gov/meteors/meteor-showers/": "Meteor Showers",
                "https://science.nasa.gov/solar-system/solar-system-formation/": "Solar System Formation",
                "https://science.nasa.gov/solar-system/planets/": "Planets Overview",
                "https://science.nasa.gov/solar-system/moons/": "Moons Overview",
                "https://science.nasa.gov/solar-system/small-bodies/": "Small Bodies",
                "https://www.nasa.gov/solar-system/": "NASA Solar System Portal",
                "https://www.nasa.gov/solar-system/planets/": "NASA Planets",
                "https://www.nasa.gov/solar-system/moons/": "NASA Moons",
                "https://www.nasa.gov/solar-system/asteroids-comets/": "NASA Asteroids and Comets",
                "https://science.nasa.gov/mars/mars-rovers/": "Mars Rovers",
                "https://science.nasa.gov/mars/mars-atmosphere/": "Mars Atmosphere",
                "https://science.nasa.gov/mars/mars-water/": "Water on Mars",
                "https://science.nasa.gov/venus/venus-atmosphere/": "Venus Atmosphere",
                "https://science.nasa.gov/mercury/mercury-exploration/": "Mercury Exploration",
                "https://science.nasa.gov/earth/earth-atmosphere/": "Earth's Atmosphere",
                "https://science.nasa.gov/earth/earth-magnetosphere/": "Earth's Magnetosphere",
                "https://science.nasa.gov/jupiter/great-red-spot/": "Jupiter's Great Red Spot",
                "https://science.nasa.gov/jupiter/jupiter-atmosphere/": "Jupiter's Atmosphere",
                "https://science.nasa.gov/saturn/saturn-atmosphere/": "Saturn's Atmosphere",
                "https://science.nasa.gov/uranus/uranus-atmosphere/": "Uranus Atmosphere",
                "https://science.nasa.gov/neptune/neptune-atmosphere/": "Neptune Atmosphere",
                "https://science.nasa.gov/solar-system/interstellar-space/": "Interstellar Space",
                "https://science.nasa.gov/solar-system/heliosphere/": "Heliosphere",
                "https://science.nasa.gov/solar-system/magnetospheres/": "Magnetospheres",
                "https://science.nasa.gov/earth/earth-moon-system/": "Earth-Moon System",
                "https://science.nasa.gov/solar-system/solar-system-exploration/": "Solar System Exploration",
                "https://science.nasa.gov/earth/earth-interior/": "Earth's Interior",
                "https://science.nasa.gov/earth/volcanoes/": "Volcanoes from Space",
                "https://science.nasa.gov/earth/earthquakes/": "Earthquakes from Space",
                "https://science.nasa.gov/moon/lunar-exploration/": "Lunar Exploration History",
                "https://science.nasa.gov/moon/moon-rocks/": "Moon Rocks",
                "https://science.nasa.gov/mars/mars-geology/": "Mars Geology",
                "https://science.nasa.gov/saturn/mimas/": "Mimas",
                "https://science.nasa.gov/saturn/rhea/": "Rhea",
                "https://science.nasa.gov/saturn/iapetus/": "Iapetus",
                "https://science.nasa.gov/saturn/dione/": "Dione",
                "https://science.nasa.gov/saturn/tethys/": "Tethys",
                "https://science.nasa.gov/saturn/hyperion/": "Hyperion",
                "https://science.nasa.gov/saturn/phoebe/": "Phoebe",
                "https://science.nasa.gov/jupiter/amalthea/": "Amalthea",
                "https://science.nasa.gov/uranus/miranda/": "Miranda",
                "https://science.nasa.gov/uranus/ariel/": "Ariel",
                "https://science.nasa.gov/uranus/umbriel/": "Umbriel",
                "https://science.nasa.gov/uranus/titania/": "Titania",
                "https://science.nasa.gov/uranus/oberon/": "Oberon",
                "https://science.nasa.gov/dwarf-planets/pluto/charon/": "Charon",
                # Additional planetary features and bodies
                "https://science.nasa.gov/mars/mars-moons/": "Mars Moons",
                "https://science.nasa.gov/mars/phobos/": "Phobos",
                "https://science.nasa.gov/mars/deimos/": "Deimos",
                "https://science.nasa.gov/mars/mars-interior/": "Mars Interior",
                "https://science.nasa.gov/venus/venus-surface/": "Venus Surface",
                "https://science.nasa.gov/venus/venus-exploration/": "Venus Exploration",
                "https://science.nasa.gov/mercury/mercury-surface/": "Mercury Surface",
                "https://science.nasa.gov/mercury/mercury-interior/": "Mercury Interior",
                "https://science.nasa.gov/moon/moon-interior/": "Moon Interior",
                "https://science.nasa.gov/moon/moon-surface/": "Moon Surface",
                "https://science.nasa.gov/moon/lunar-craters/": "Lunar Craters",
                "https://science.nasa.gov/jupiter/jupiter-interior/": "Jupiter Interior",
                "https://science.nasa.gov/jupiter/jupiter-rings/": "Jupiter's Rings",
                "https://science.nasa.gov/saturn/saturn-interior/": "Saturn Interior",
                "https://science.nasa.gov/uranus/uranus-interior/": "Uranus Interior",
                "https://science.nasa.gov/uranus/uranus-rings/": "Uranus Rings",
                "https://science.nasa.gov/neptune/neptune-interior/": "Neptune Interior",
                "https://science.nasa.gov/neptune/neptune-rings/": "Neptune Rings",
                "https://science.nasa.gov/dwarf-planets/pluto/pluto-moons/": "Pluto's Moons",
                "https://science.nasa.gov/dwarf-planets/sedna/": "Sedna",
                "https://science.nasa.gov/comets/comet-neowise/": "Comet NEOWISE",
                "https://science.nasa.gov/earth/aurora/": "Aurora",
                "https://science.nasa.gov/sun/heliophysics/": "Heliophysics",
                "https://science.nasa.gov/sun/space-weather/": "Space Weather",
                "https://science.nasa.gov/sun/corona/": "Solar Corona",
                "https://science.nasa.gov/sun/chromosphere/": "Chromosphere",
                "https://science.nasa.gov/sun/photosphere/": "Photosphere",
            },
        },
        "universe": {
            "pages": {
                "https://science.nasa.gov/universe/": "Universe Overview",
                "https://science.nasa.gov/universe/stars/": "Stars",
                "https://science.nasa.gov/universe/stars/types/": "Types of Stars",
                "https://science.nasa.gov/universe/stars/life-cycle/": "Stellar Life Cycle",
                "https://science.nasa.gov/universe/stars/supernovae/": "Supernovae",
                "https://science.nasa.gov/universe/stars/neutron-stars/": "Neutron Stars",
                "https://science.nasa.gov/universe/stars/white-dwarfs/": "White Dwarfs",
                "https://science.nasa.gov/universe/stars/red-giants/": "Red Giants",
                "https://science.nasa.gov/universe/stars/brown-dwarfs/": "Brown Dwarfs",
                "https://science.nasa.gov/universe/stars/binary-stars/": "Binary Stars",
                "https://science.nasa.gov/universe/stars/pulsars/": "Pulsars",
                "https://science.nasa.gov/universe/stars/variable-stars/": "Variable Stars",
                "https://science.nasa.gov/universe/stars/star-forming-regions/": "Star Forming Regions",
                "https://science.nasa.gov/universe/stars/sun-like-stars/": "Sun-like Stars",
                "https://science.nasa.gov/universe/galaxies/": "Galaxies",
                "https://science.nasa.gov/universe/galaxies/types/": "Types of Galaxies",
                "https://science.nasa.gov/universe/galaxies/milky-way/": "Milky Way",
                "https://science.nasa.gov/universe/galaxies/andromeda/": "Andromeda Galaxy",
                "https://science.nasa.gov/universe/galaxies/elliptical/": "Elliptical Galaxies",
                "https://science.nasa.gov/universe/galaxies/spiral/": "Spiral Galaxies",
                "https://science.nasa.gov/universe/galaxies/irregular/": "Irregular Galaxies",
                "https://science.nasa.gov/universe/galaxies/active-galaxies/": "Active Galaxies",
                "https://science.nasa.gov/universe/galaxies/galaxy-clusters/": "Galaxy Clusters",
                "https://science.nasa.gov/universe/galaxies/galaxy-collisions/": "Galaxy Collisions",
                "https://science.nasa.gov/universe/galaxies/quasars/": "Quasars",
                "https://science.nasa.gov/universe/black-holes/": "Black Holes",
                "https://science.nasa.gov/universe/black-holes/facts/": "Black Hole Facts",
                "https://science.nasa.gov/universe/black-holes/types/": "Types of Black Holes",
                "https://science.nasa.gov/universe/black-holes/supermassive/": "Supermassive Black Holes",
                "https://science.nasa.gov/universe/black-holes/stellar/": "Stellar Black Holes",
                "https://science.nasa.gov/universe/dark-matter/": "Dark Matter",
                "https://science.nasa.gov/universe/dark-energy/": "Dark Energy",
                "https://science.nasa.gov/universe/exoplanets/": "Exoplanets",
                "https://science.nasa.gov/exoplanets/": "Exoplanet Exploration",
                "https://science.nasa.gov/exoplanets/exoplanet-catalog/": "Exoplanet Catalog",
                "https://science.nasa.gov/exoplanets/what-is-an-exoplanet/": "What is an Exoplanet?",
                "https://science.nasa.gov/exoplanets/how-we-find-exoplanets/": "How We Find Exoplanets",
                "https://science.nasa.gov/exoplanets/habitable-zone/": "Habitable Zone",
                "https://science.nasa.gov/exoplanets/types-of-exoplanets/": "Types of Exoplanets",
                "https://science.nasa.gov/exoplanets/gas-giant/": "Gas Giant Exoplanets",
                "https://science.nasa.gov/exoplanets/neptune-like/": "Neptune-like Exoplanets",
                "https://science.nasa.gov/exoplanets/super-earth/": "Super-Earths",
                "https://science.nasa.gov/exoplanets/terrestrial/": "Terrestrial Exoplanets",
                "https://science.nasa.gov/universe/nebulae/": "Nebulae",
                "https://science.nasa.gov/universe/nebulae/types/": "Types of Nebulae",
                "https://science.nasa.gov/universe/nebulae/planetary-nebulae/": "Planetary Nebulae",
                "https://science.nasa.gov/universe/nebulae/emission-nebulae/": "Emission Nebulae",
                "https://science.nasa.gov/universe/nebulae/reflection-nebulae/": "Reflection Nebulae",
                "https://science.nasa.gov/universe/nebulae/dark-nebulae/": "Dark Nebulae",
                "https://science.nasa.gov/universe/nebulae/supernova-remnants/": "Supernova Remnants",
                "https://science.nasa.gov/universe/the-big-bang/": "The Big Bang",
                "https://science.nasa.gov/universe/overview/": "Universe Overview",
                "https://science.nasa.gov/universe/dark-universe/": "The Dark Universe",
                "https://science.nasa.gov/universe/cosmic-microwave-background/": "Cosmic Microwave Background",
                "https://science.nasa.gov/universe/cosmology/": "Cosmology",
                "https://science.nasa.gov/universe/expansion-rate/": "Universe Expansion Rate",
                "https://science.nasa.gov/universe/galaxies/local-group/": "Local Group",
                "https://science.nasa.gov/universe/galaxies/laniakea/": "Laniakea Supercluster",
                "https://science.nasa.gov/universe/gravitational-waves/": "Gravitational Waves",
                "https://science.nasa.gov/universe/gamma-ray-bursts/": "Gamma-Ray Bursts",
                "https://science.nasa.gov/universe/multimessenger-astrophysics/": "Multimessenger Astrophysics",
                "https://www.nasa.gov/universe/": "NASA Universe Portal",
                "https://www.nasa.gov/universe/stars/": "NASA Stars",
                "https://www.nasa.gov/universe/galaxies/": "NASA Galaxies",
                "https://www.nasa.gov/universe/black-holes/": "NASA Black Holes",
                "https://www.nasa.gov/universe/dark-matter-dark-energy/": "NASA Dark Matter and Dark Energy",
                "https://www.nasa.gov/universe/exoplanets/": "NASA Exoplanets",
                "https://www.nasa.gov/universe/nebulae/": "NASA Nebulae",
                # Additional universe topics
                "https://science.nasa.gov/universe/stars/magnetars/": "Magnetars",
                "https://science.nasa.gov/universe/stars/hypergiants/": "Hypergiants",
                "https://science.nasa.gov/universe/stars/wolf-rayet/": "Wolf-Rayet Stars",
                "https://science.nasa.gov/universe/stars/cepheid-variables/": "Cepheid Variables",
                "https://science.nasa.gov/universe/stars/red-dwarfs/": "Red Dwarfs",
                "https://science.nasa.gov/universe/stars/blue-giants/": "Blue Giants",
                "https://science.nasa.gov/universe/stars/globular-clusters/": "Globular Clusters",
                "https://science.nasa.gov/universe/stars/open-clusters/": "Open Clusters",
                "https://science.nasa.gov/universe/black-holes/intermediate/": "Intermediate Black Holes",
                "https://science.nasa.gov/universe/black-holes/primordial/": "Primordial Black Holes",
                "https://science.nasa.gov/universe/black-holes/event-horizon/": "Event Horizons",
                "https://science.nasa.gov/universe/black-holes/accretion-disks/": "Accretion Disks",
                "https://science.nasa.gov/universe/galaxies/dwarf-galaxies/": "Dwarf Galaxies",
                "https://science.nasa.gov/universe/galaxies/starburst/": "Starburst Galaxies",
                "https://science.nasa.gov/universe/galaxies/seyfert/": "Seyfert Galaxies",
                "https://science.nasa.gov/universe/galaxies/blazars/": "Blazars",
                "https://science.nasa.gov/exoplanets/hot-jupiters/": "Hot Jupiters",
                "https://science.nasa.gov/exoplanets/mini-neptunes/": "Mini-Neptunes",
                "https://science.nasa.gov/exoplanets/rogue-planets/": "Rogue Planets",
                "https://science.nasa.gov/exoplanets/water-worlds/": "Water Worlds",
                "https://science.nasa.gov/exoplanets/kepler-discoveries/": "Kepler Discoveries",
                "https://science.nasa.gov/exoplanets/tess-discoveries/": "TESS Discoveries",
                "https://science.nasa.gov/universe/nebulae/supernova-remnants/": "Supernova Remnants",
                "https://science.nasa.gov/universe/cosmic-rays/": "Cosmic Rays",
                "https://science.nasa.gov/universe/intergalactic-medium/": "Intergalactic Medium",
                "https://science.nasa.gov/universe/large-scale-structure/": "Large Scale Structure",
                "https://science.nasa.gov/universe/dark-energy/fate-of-universe/": "Fate of the Universe",
                "https://science.nasa.gov/universe/primordial-nucleosynthesis/": "Primordial Nucleosynthesis",
                "https://science.nasa.gov/universe/cosmic-inflation/": "Cosmic Inflation",
                "https://science.nasa.gov/universe/gravitational-lensing/": "Gravitational Lensing",
            },
        },
        "earth-science": {
            "pages": {
                "https://science.nasa.gov/earth/": "Earth Science Overview",
                "https://science.nasa.gov/earth/climate-change/": "Climate Change",
                "https://science.nasa.gov/earth/climate-change/evidence/": "Climate Change Evidence",
                "https://science.nasa.gov/earth/climate-change/causes/": "Climate Change Causes",
                "https://science.nasa.gov/earth/climate-change/effects/": "Climate Change Effects",
                "https://science.nasa.gov/earth/climate-change/solutions/": "Climate Change Solutions",
                "https://science.nasa.gov/earth/climate-change/scientific-consensus/": "Scientific Consensus on Climate",
                "https://science.nasa.gov/earth/climate-change/vital-signs/": "Earth Vital Signs",
                "https://science.nasa.gov/earth/climate-change/faq/": "Climate Change FAQ",
                "https://science.nasa.gov/earth/atmosphere/": "Earth's Atmosphere",
                "https://science.nasa.gov/earth/atmosphere/layers/": "Atmospheric Layers",
                "https://science.nasa.gov/earth/atmosphere/ozone/": "Ozone Layer",
                "https://science.nasa.gov/earth/atmosphere/greenhouse-effect/": "Greenhouse Effect",
                "https://science.nasa.gov/earth/atmosphere/weather/": "Weather from Space",
                "https://science.nasa.gov/earth/atmosphere/hurricanes/": "Hurricanes from Space",
                "https://science.nasa.gov/earth/atmosphere/clouds/": "Clouds from Space",
                "https://science.nasa.gov/earth/atmosphere/aerosols/": "Aerosols",
                "https://science.nasa.gov/earth/atmosphere/air-quality/": "Air Quality",
                "https://science.nasa.gov/earth/oceans/": "Earth's Oceans",
                "https://science.nasa.gov/earth/oceans/ocean-currents/": "Ocean Currents",
                "https://science.nasa.gov/earth/oceans/sea-level/": "Sea Level",
                "https://science.nasa.gov/earth/oceans/ocean-temperature/": "Ocean Temperature",
                "https://science.nasa.gov/earth/oceans/ocean-color/": "Ocean Color",
                "https://science.nasa.gov/earth/oceans/coral-reefs/": "Coral Reefs",
                "https://science.nasa.gov/earth/oceans/arctic-sea-ice/": "Arctic Sea Ice",
                "https://science.nasa.gov/earth/oceans/antarctic-ice/": "Antarctic Ice",
                "https://science.nasa.gov/earth/land/": "Earth's Land",
                "https://science.nasa.gov/earth/land/forests/": "Forests from Space",
                "https://science.nasa.gov/earth/land/deforestation/": "Deforestation",
                "https://science.nasa.gov/earth/land/agriculture/": "Agriculture from Space",
                "https://science.nasa.gov/earth/land/urbanization/": "Urbanization",
                "https://science.nasa.gov/earth/land/fires/": "Wildfires from Space",
                "https://science.nasa.gov/earth/land/desertification/": "Desertification",
                "https://science.nasa.gov/earth/land/landslides/": "Landslides",
                "https://science.nasa.gov/earth/land/soil/": "Soil",
                "https://science.nasa.gov/earth/ice-cryosphere/": "Ice and Cryosphere",
                "https://science.nasa.gov/earth/ice-cryosphere/glaciers/": "Glaciers",
                "https://science.nasa.gov/earth/ice-cryosphere/ice-sheets/": "Ice Sheets",
                "https://science.nasa.gov/earth/ice-cryosphere/permafrost/": "Permafrost",
                "https://science.nasa.gov/earth/water-cycle/": "Water Cycle",
                "https://science.nasa.gov/earth/freshwater/": "Freshwater",
                "https://science.nasa.gov/earth/gravity/": "Earth's Gravity",
                "https://science.nasa.gov/earth/carbon-cycle/": "Carbon Cycle",
                "https://science.nasa.gov/earth/nitrogen-cycle/": "Nitrogen Cycle",
                "https://science.nasa.gov/earth/biodiversity/": "Biodiversity",
                "https://science.nasa.gov/earth/natural-hazards/": "Natural Hazards",
                "https://science.nasa.gov/earth/natural-hazards/earthquakes/": "Earthquakes",
                "https://science.nasa.gov/earth/natural-hazards/volcanoes/": "Volcanoes",
                "https://science.nasa.gov/earth/natural-hazards/tsunamis/": "Tsunamis",
                "https://science.nasa.gov/earth/natural-hazards/floods/": "Floods",
                "https://science.nasa.gov/earth/natural-hazards/droughts/": "Droughts",
                "https://www.nasa.gov/earth/": "NASA Earth Portal",
                "https://www.nasa.gov/earth/climate-change/": "NASA Climate Change",
                "https://www.nasa.gov/earth/water/": "NASA Water",
                "https://www.nasa.gov/earth/air-quality/": "NASA Air Quality",
                "https://www.nasa.gov/earth/land/": "NASA Land",
                "https://www.nasa.gov/earth/natural-disasters/": "NASA Natural Disasters",
                # Additional earth science topics
                "https://science.nasa.gov/earth/snow-ice/": "Snow and Ice from Space",
                "https://science.nasa.gov/earth/dust-storms/": "Dust Storms",
                "https://science.nasa.gov/earth/el-nino/": "El Nino",
                "https://science.nasa.gov/earth/la-nina/": "La Nina",
                "https://science.nasa.gov/earth/monsoons/": "Monsoons from Space",
                "https://science.nasa.gov/earth/phytoplankton/": "Phytoplankton",
                "https://science.nasa.gov/earth/river-deltas/": "River Deltas",
                "https://science.nasa.gov/earth/wetlands/": "Wetlands",
                "https://science.nasa.gov/earth/lakes/": "Lakes from Space",
                "https://science.nasa.gov/earth/geomorphology/": "Geomorphology",
                "https://science.nasa.gov/earth/coastal-erosion/": "Coastal Erosion",
                "https://science.nasa.gov/earth/air-pollution/": "Air Pollution from Space",
                "https://science.nasa.gov/earth/light-pollution/": "Light Pollution",
                "https://science.nasa.gov/earth/methane/": "Methane Monitoring",
                "https://science.nasa.gov/earth/co2/": "CO2 Monitoring",
                "https://science.nasa.gov/earth/ozone-hole/": "Ozone Hole",
                "https://science.nasa.gov/earth/greenland-ice/": "Greenland Ice Sheet",
                "https://science.nasa.gov/earth/antarctic-ice-sheet/": "Antarctic Ice Sheet",
                "https://science.nasa.gov/earth/sea-ice-extent/": "Sea Ice Extent",
                "https://science.nasa.gov/earth/ocean-acidification/": "Ocean Acidification",
                "https://science.nasa.gov/earth/global-temperature/": "Global Temperature",
                "https://science.nasa.gov/earth/precipitation/": "Precipitation Monitoring",
                "https://science.nasa.gov/earth/soil-moisture/": "Soil Moisture",
                "https://science.nasa.gov/earth/vegetation-index/": "Vegetation Index",
            },
        },
        "missions": {
            "pages": {
                "https://science.nasa.gov/mission/hubble/": "Hubble Space Telescope",
                "https://science.nasa.gov/mission/hubble/overview/": "Hubble Overview",
                "https://science.nasa.gov/mission/hubble/science/": "Hubble Science",
                "https://science.nasa.gov/mission/hubble/hubble-news/": "Hubble News",
                "https://science.nasa.gov/mission/webb/": "James Webb Space Telescope",
                "https://science.nasa.gov/mission/webb/about-overview/": "JWST Overview",
                "https://science.nasa.gov/mission/webb/science/": "JWST Science",
                "https://science.nasa.gov/mission/webb/webb-news/": "JWST News",
                "https://science.nasa.gov/mission/webb/observatory/": "JWST Observatory",
                "https://science.nasa.gov/mission/webb/multimedia/": "JWST Images",
                "https://www.nasa.gov/mission/artemis-i/": "Artemis I",
                "https://www.nasa.gov/mission/artemis-ii/": "Artemis II",
                "https://www.nasa.gov/mission/artemis-iii/": "Artemis III",
                "https://www.nasa.gov/specials/artemis/": "Artemis Program",
                "https://science.nasa.gov/mission/voyager/": "Voyager",
                "https://science.nasa.gov/mission/voyager/voyager-1/": "Voyager 1",
                "https://science.nasa.gov/mission/voyager/voyager-2/": "Voyager 2",
                "https://science.nasa.gov/mission/voyager/science/": "Voyager Science",
                "https://science.nasa.gov/mission/voyager/the-golden-record/": "Voyager Golden Record",
                "https://science.nasa.gov/mission/cassini-huygens/": "Cassini-Huygens",
                "https://science.nasa.gov/mission/cassini-huygens/science/": "Cassini Science",
                "https://science.nasa.gov/mission/curiosity/": "Curiosity Rover",
                "https://science.nasa.gov/mission/curiosity/science/": "Curiosity Science",
                "https://science.nasa.gov/mission/mars-2020-perseverance/": "Perseverance Rover",
                "https://science.nasa.gov/mission/mars-2020-perseverance/science/": "Perseverance Science",
                "https://science.nasa.gov/mission/ingenuity/": "Ingenuity Helicopter",
                "https://www.nasa.gov/international-space-station/": "International Space Station",
                "https://www.nasa.gov/international-space-station/space-station-facts-and-figures/": "ISS Facts",
                "https://www.nasa.gov/international-space-station/space-station-research/": "ISS Research",
                "https://science.nasa.gov/mission/juno/": "Juno",
                "https://science.nasa.gov/mission/juno/science/": "Juno Science",
                "https://science.nasa.gov/mission/new-horizons/": "New Horizons",
                "https://science.nasa.gov/mission/new-horizons/science/": "New Horizons Science",
                "https://science.nasa.gov/mission/dawn/": "Dawn",
                "https://science.nasa.gov/mission/kepler/": "Kepler",
                "https://science.nasa.gov/mission/tess/": "TESS",
                "https://science.nasa.gov/mission/chandra/": "Chandra X-ray Observatory",
                "https://science.nasa.gov/mission/spitzer/": "Spitzer Space Telescope",
                "https://science.nasa.gov/mission/fermi/": "Fermi Gamma-ray Telescope",
                "https://science.nasa.gov/mission/swift/": "Swift",
                "https://science.nasa.gov/mission/nustar/": "NuSTAR",
                "https://science.nasa.gov/mission/ixpe/": "IXPE",
                "https://science.nasa.gov/mission/osiris-rex/": "OSIRIS-REx",
                "https://science.nasa.gov/mission/dart/": "DART",
                "https://science.nasa.gov/mission/lucy/": "Lucy",
                "https://science.nasa.gov/mission/psyche/": "Psyche",
                "https://science.nasa.gov/mission/europa-clipper/": "Europa Clipper",
                "https://science.nasa.gov/mission/dragonfly/": "Dragonfly",
                "https://science.nasa.gov/mission/maven/": "MAVEN",
                "https://science.nasa.gov/mission/insight/": "InSight",
                "https://science.nasa.gov/mission/mro/": "Mars Reconnaissance Orbiter",
                "https://science.nasa.gov/mission/mars-odyssey/": "Mars Odyssey",
                "https://science.nasa.gov/mission/messenger/": "MESSENGER",
                "https://science.nasa.gov/mission/soho/": "SOHO",
                "https://science.nasa.gov/mission/sdo/": "Solar Dynamics Observatory",
                "https://science.nasa.gov/mission/parker-solar-probe/": "Parker Solar Probe",
                "https://science.nasa.gov/mission/solar-orbiter/": "Solar Orbiter",
                "https://science.nasa.gov/mission/stereo/": "STEREO",
                "https://science.nasa.gov/mission/grace-fo/": "GRACE-FO",
                "https://science.nasa.gov/mission/icesat-2/": "ICESat-2",
                "https://science.nasa.gov/mission/landsat/": "Landsat",
                "https://science.nasa.gov/mission/terra/": "Terra",
                "https://science.nasa.gov/mission/aqua/": "Aqua",
                "https://science.nasa.gov/mission/aura/": "Aura",
                "https://science.nasa.gov/mission/gpm/": "GPM",
                "https://science.nasa.gov/mission/suomi-npp/": "Suomi NPP",
                "https://science.nasa.gov/mission/pace/": "PACE",
                "https://science.nasa.gov/mission/nisar/": "NISAR",
                "https://science.nasa.gov/mission/swot/": "SWOT",
                "https://science.nasa.gov/mission/roman/": "Nancy Grace Roman Space Telescope",
                "https://science.nasa.gov/mission/neo-surveyor/": "NEO Surveyor",
                "https://science.nasa.gov/mission/spherex/": "SPHEREx",
                "https://www.nasa.gov/missions/": "NASA Missions Portal",
                "https://www.nasa.gov/mission/apollo/": "Apollo Program",
                "https://www.nasa.gov/mission/apollo-11/": "Apollo 11",
                "https://www.nasa.gov/mission/apollo-13/": "Apollo 13",
                "https://www.nasa.gov/mission/mercury-program/": "Mercury Program",
                "https://www.nasa.gov/mission/gemini-program/": "Gemini Program",
                "https://www.nasa.gov/mission/space-shuttle/": "Space Shuttle",
                "https://www.nasa.gov/mission/skylab/": "Skylab",
                "https://www.nasa.gov/humans-in-space/": "Humans in Space",
                "https://www.nasa.gov/humans-in-space/astronauts/": "Astronauts",
                "https://www.nasa.gov/humans-in-space/commercial-space/": "Commercial Space",
                "https://www.nasa.gov/specials/apollo50th/": "Apollo 50th Anniversary",
                "https://science.nasa.gov/mission/pioneer-10-11/": "Pioneer 10 and 11",
                "https://science.nasa.gov/mission/galileo/": "Galileo Mission",
                "https://science.nasa.gov/mission/magellan/": "Magellan",
                "https://science.nasa.gov/mission/mars-pathfinder/": "Mars Pathfinder",
                "https://science.nasa.gov/mission/spirit/": "Spirit Rover",
                "https://science.nasa.gov/mission/opportunity/": "Opportunity Rover",
                "https://science.nasa.gov/mission/phoenix/": "Phoenix Lander",
                "https://science.nasa.gov/mission/stardust/": "Stardust",
                "https://science.nasa.gov/mission/deep-impact/": "Deep Impact",
                "https://science.nasa.gov/mission/wise-neowise/": "WISE/NEOWISE",
                "https://science.nasa.gov/mission/planck/": "Planck",
                "https://science.nasa.gov/mission/wmap/": "WMAP",
                "https://science.nasa.gov/mission/cobe/": "COBE",
                "https://science.nasa.gov/mission/gaia/": "Gaia",
                "https://science.nasa.gov/mission/hitomi/": "Hitomi",
                "https://science.nasa.gov/mission/sunrise/": "Sunrise",
                "https://science.nasa.gov/missions/": "All NASA Science Missions",
                # Additional missions
                "https://science.nasa.gov/mission/themis/": "THEMIS",
                "https://science.nasa.gov/mission/mms/": "MMS",
                "https://science.nasa.gov/mission/ibex/": "IBEX",
                "https://science.nasa.gov/mission/iris/": "IRIS",
                "https://science.nasa.gov/mission/wind/": "Wind",
                "https://science.nasa.gov/mission/ace/": "ACE",
                "https://science.nasa.gov/mission/rhessi/": "RHESSI",
                "https://science.nasa.gov/mission/ladee/": "LADEE",
                "https://science.nasa.gov/mission/lcross/": "LCROSS",
                "https://science.nasa.gov/mission/lro/": "Lunar Reconnaissance Orbiter",
                "https://science.nasa.gov/mission/grail/": "GRAIL",
                "https://science.nasa.gov/mission/clementine/": "Clementine",
                "https://science.nasa.gov/mission/lunar-prospector/": "Lunar Prospector",
                "https://science.nasa.gov/mission/mars-global-surveyor/": "Mars Global Surveyor",
                "https://science.nasa.gov/mission/mars-express/": "Mars Express",
                "https://science.nasa.gov/mission/mars-orbiter-mission/": "Mars Orbiter Mission",
                "https://science.nasa.gov/mission/exomars-trace-gas-orbiter/": "ExoMars Trace Gas Orbiter",
                "https://www.nasa.gov/mission/sls/": "Space Launch System",
                "https://www.nasa.gov/mission/orion/": "Orion Spacecraft",
                "https://www.nasa.gov/mission/gateway/": "Lunar Gateway",
                "https://www.nasa.gov/mission/commercial-crew/": "Commercial Crew Program",
                "https://www.nasa.gov/mission/spacex-crew/": "SpaceX Crew Missions",
                "https://www.nasa.gov/mission/apollo-7/": "Apollo 7",
                "https://www.nasa.gov/mission/apollo-8/": "Apollo 8",
                "https://www.nasa.gov/mission/apollo-14/": "Apollo 14",
                "https://www.nasa.gov/mission/apollo-15/": "Apollo 15",
                "https://www.nasa.gov/mission/apollo-16/": "Apollo 16",
                "https://www.nasa.gov/mission/apollo-17/": "Apollo 17",
            },
        },
        "technology": {
            "pages": {
                "https://www.nasa.gov/technology/": "NASA Technology",
                "https://www.nasa.gov/directorates/stmd/": "Space Technology Mission Directorate",
                "https://www.nasa.gov/technology/space-tech/": "Space Technology",
                "https://www.nasa.gov/technology/propulsion/": "Propulsion",
                "https://www.nasa.gov/technology/propulsion/ion-propulsion/": "Ion Propulsion",
                "https://www.nasa.gov/technology/propulsion/solar-electric/": "Solar Electric Propulsion",
                "https://www.nasa.gov/technology/propulsion/nuclear-propulsion/": "Nuclear Propulsion",
                "https://www.nasa.gov/technology/propulsion/chemical-propulsion/": "Chemical Propulsion",
                "https://www.nasa.gov/technology/solar-sails/": "Solar Sails",
                "https://www.nasa.gov/technology/space-power/": "Space Power",
                "https://www.nasa.gov/technology/space-power/solar-arrays/": "Solar Arrays",
                "https://www.nasa.gov/technology/space-power/nuclear-power/": "Nuclear Power in Space",
                "https://www.nasa.gov/technology/space-power/batteries/": "Space Batteries",
                "https://www.nasa.gov/technology/robotics/": "Robotics",
                "https://www.nasa.gov/technology/robotics/robonaut/": "Robonaut",
                "https://www.nasa.gov/technology/robotics/autonomous-systems/": "Autonomous Systems",
                "https://www.nasa.gov/technology/communications/": "Space Communications",
                "https://www.nasa.gov/technology/communications/deep-space-network/": "Deep Space Network",
                "https://www.nasa.gov/technology/communications/laser-communications/": "Laser Communications",
                "https://www.nasa.gov/technology/life-support/": "Life Support Systems",
                "https://www.nasa.gov/technology/manufacturing/": "Manufacturing",
                "https://www.nasa.gov/technology/manufacturing/3d-printing-in-space/": "3D Printing in Space",
                "https://www.nasa.gov/technology/materials/": "Advanced Materials",
                "https://www.nasa.gov/technology/spinoffs/": "Spinoff Technologies",
                "https://www.nasa.gov/technology/entry-descent-landing/": "Entry Descent Landing",
                "https://www.nasa.gov/technology/heat-shields/": "Heat Shields",
                "https://www.nasa.gov/technology/supersonic-parachutes/": "Supersonic Parachutes",
                "https://www.nasa.gov/technology/small-spacecraft/": "Small Spacecraft",
                "https://www.nasa.gov/technology/cubesats/": "CubeSats",
                "https://www.nasa.gov/technology/space-suits/": "Space Suits",
                "https://www.nasa.gov/technology/habitation/": "Space Habitation",
                "https://www.nasa.gov/technology/in-situ-resource-utilization/": "In-Situ Resource Utilization",
                "https://www.nasa.gov/technology/technology-transfer/": "Technology Transfer",
                "https://www.nasa.gov/directorates/stmd/game-changing-development/": "Game Changing Development",
                "https://www.nasa.gov/directorates/stmd/small-business-innovation-research-program/": "SBIR Program",
                "https://www.nasa.gov/centers/jpl/": "Jet Propulsion Laboratory",
                "https://www.nasa.gov/centers/goddard/": "Goddard Space Flight Center",
                "https://www.nasa.gov/centers/kennedy/": "Kennedy Space Center",
                "https://www.nasa.gov/centers/johnson/": "Johnson Space Center",
                "https://www.nasa.gov/centers/marshall/": "Marshall Space Flight Center",
                "https://www.nasa.gov/centers/ames/": "Ames Research Center",
                "https://www.nasa.gov/centers/langley/": "Langley Research Center",
                "https://www.nasa.gov/centers/glenn/": "Glenn Research Center",
                "https://www.nasa.gov/centers/stennis/": "Stennis Space Center",
                "https://www.nasa.gov/centers/armstrong/": "Armstrong Flight Research Center",
                "https://www.nasa.gov/general/nasa-history/": "NASA History",
                "https://www.nasa.gov/general/about-nasa/": "About NASA",
                "https://www.nasa.gov/learning-resources/": "NASA Learning Resources",
                "https://www.nasa.gov/stem/": "NASA STEM",
                "https://www.nasa.gov/image-of-the-day/": "NASA Image of the Day",
                # Additional technology and science topics
                "https://www.nasa.gov/technology/space-telescopes/": "Space Telescopes",
                "https://www.nasa.gov/technology/aeronautics/": "Aeronautics",
                "https://www.nasa.gov/technology/aeronautics/x-planes/": "X-Planes",
                "https://www.nasa.gov/technology/aeronautics/supersonic/": "Supersonic Flight",
                "https://www.nasa.gov/technology/aeronautics/electric-flight/": "Electric Flight",
                "https://www.nasa.gov/technology/aeronautics/hypersonic/": "Hypersonic Research",
                "https://www.nasa.gov/technology/human-research/": "Human Research Program",
                "https://www.nasa.gov/technology/human-research/radiation/": "Space Radiation",
                "https://www.nasa.gov/technology/human-research/bone-loss/": "Bone Loss in Space",
                "https://www.nasa.gov/technology/human-research/vision/": "Vision in Space",
                "https://www.nasa.gov/technology/artificial-intelligence/": "AI at NASA",
                "https://www.nasa.gov/technology/earth-observation/": "Earth Observation Technology",
                "https://www.nasa.gov/technology/sensors-instruments/": "Sensors and Instruments",
                "https://www.nasa.gov/technology/navigation/": "Space Navigation",
                "https://www.nasa.gov/technology/docking/": "Docking Systems",
                "https://www.nasa.gov/technology/thermal-protection/": "Thermal Protection",
                "https://www.nasa.gov/technology/cryogenics/": "Cryogenic Technology",
                "https://www.nasa.gov/technology/mars-helicopter/": "Mars Helicopter Technology",
                "https://www.nasa.gov/technology/sampling/": "Sample Collection Technology",
                "https://www.nasa.gov/technology/deployable-structures/": "Deployable Structures",
            },
        },
    }

    def __init__(self, base_dir, source_key=None):
        name = f"nasa-{source_key}" if source_key else "nasa"
        super().__init__(name, base_dir, interval_seconds=3600)
        self.source_key = source_key

    def _strip_html(self, html_content):
        """Remove HTML tags, scripts, styles, nav, header, footer, sidebar and normalize whitespace."""
        text = html_content
        text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
        text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL)
        text = re.sub(r'<nav[^>]*>.*?</nav>', '', text, flags=re.DOTALL)
        text = re.sub(r'<footer[^>]*>.*?</footer>', '', text, flags=re.DOTALL)
        text = re.sub(r'<header[^>]*>.*?</header>', '', text, flags=re.DOTALL)
        text = re.sub(r'<aside[^>]*>.*?</aside>', '', text, flags=re.DOTALL)
        text = re.sub(r'<[^>]+>', ' ', text)
        text = html_mod.unescape(text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    def _extract_title(self, html_content, fallback):
        """Extract page title from HTML."""
        match = re.search(r'<title>([^<]+)</title>', html_content, re.IGNORECASE)
        if match:
            title = match.group(1).strip()
            # Clean common suffixes
            for suffix in [' - NASA Solar System Exploration',
                           ' | NASA Science', ' - NASA Science',
                           ' | NASA', ' - NASA']:
                if title.endswith(suffix):
                    title = title[:-len(suffix)].strip()
            return title
        return fallback

    def _scrape_source(self, source_key, config):
        """Scrape all pages for a given source section."""
        count = 0
        pages = config.get("pages", {})

        for url, title in pages.items():
            if not self.running:
                break

            item_id = self.make_id(url)
            content = self.fetch_url(url)

            if content and len(content) > 500:
                text = self._strip_html(content)
                if len(text) > 100:
                    page_title = self._extract_title(content, title)

                    if self.save_item(item_id, {
                        "title": page_title,
                        "content": text[:50000],
                        "url": url,
                        "category": f"nasa-{source_key}",
                        "type": "documentation",
                    }):
                        count += 1
                        self.log.info(f"  {source_key}: {title}")

            time.sleep(2.0)

        return count

    def scrape(self):
        """Run scrape across all or a specific source."""
        total = 0

        if self.source_key:
            if self.source_key not in self.SOURCES:
                self.log.error(
                    f"Unknown source key: {self.source_key}. "
                    f"Available: {list(self.SOURCES.keys())}"
                )
                return 0
            sources = {self.source_key: self.SOURCES[self.source_key]}
        else:
            sources = self.SOURCES

        for key, config in sources.items():
            if not self.running:
                break
            self.log.info(f"=== Scraping nasa/{key} ===")
            total += self._scrape_source(key, config)

        return total


if __name__ == "__main__":
    import os
    import sys

    base = os.path.expanduser("~")
    source_key = sys.argv[1] if len(sys.argv) > 1 else None
    NASAScraper(base, source_key).run()
