#!/usr/bin/env python3
"""Stanford Encyclopedia of Philosophy scraper.

Covers ~1,700 peer-reviewed articles across:
  - Epistemology, Metaphysics, Ethics, Logic
  - Philosophy of Mind, Science, Language
  - Political Philosophy, Aesthetics, Philosophy of Religion
  - History of Philosophy (Ancient, Medieval, Modern, Continental, Analytic)
"""
import re
import time
import html as html_mod
from scraper_base import BaseScraper


class SEPScraper(BaseScraper):
    """Scrape Stanford Encyclopedia of Philosophy entries."""

    SOURCES = {
        "epistemology": {
            "pages": {
                "https://plato.stanford.edu/entries/knowledge-analysis/": "Analysis of Knowledge",
                "https://plato.stanford.edu/entries/skepticism/": "Skepticism",
                "https://plato.stanford.edu/entries/epistemology/": "Epistemology",
                "https://plato.stanford.edu/entries/a-priori/": "A Priori Justification and Knowledge",
                "https://plato.stanford.edu/entries/empiricism/": "Empiricism",
                "https://plato.stanford.edu/entries/rationalism/": "Rationalism",
                "https://plato.stanford.edu/entries/foundationalism/": "Foundationalism",
                "https://plato.stanford.edu/entries/coherentism/": "Coherentism",
                "https://plato.stanford.edu/entries/reliabilism/": "Reliabilism",
                "https://plato.stanford.edu/entries/internalism-externalism/": "Internalism and Externalism in Epistemology",
                "https://plato.stanford.edu/entries/testimony-episprob/": "Epistemological Problems of Testimony",
                "https://plato.stanford.edu/entries/induction-problem/": "The Problem of Induction",
                "https://plato.stanford.edu/entries/perception-episprob/": "Epistemological Problems of Perception",
                "https://plato.stanford.edu/entries/memory-episprob/": "Epistemological Problems of Memory",
                "https://plato.stanford.edu/entries/justep-foundational/": "Foundationalist Theories of Epistemic Justification",
                "https://plato.stanford.edu/entries/justep-coherentism/": "Coherentist Theories of Epistemic Justification",
                "https://plato.stanford.edu/entries/justep-internalext/": "Internalist vs. Externalist Conceptions of Epistemic Justification",
                "https://plato.stanford.edu/entries/epistemic-closure/": "Epistemic Closure",
                "https://plato.stanford.edu/entries/contextualism-epistemology/": "Epistemic Contextualism",
                "https://plato.stanford.edu/entries/epistemology-bayesian/": "Bayesian Epistemology",
                "https://plato.stanford.edu/entries/epistemology-social/": "Social Epistemology",
                "https://plato.stanford.edu/entries/epistemology-virtue/": "Virtue Epistemology",
                "https://plato.stanford.edu/entries/evidence/": "Evidence",
                "https://plato.stanford.edu/entries/certainty/": "Certainty",
                "https://plato.stanford.edu/entries/skepticism-moral/": "Moral Skepticism",
                "https://plato.stanford.edu/entries/abduction/": "Abduction",
                "https://plato.stanford.edu/entries/epistemic-utility/": "Epistemic Utility Arguments for Probabilism",
                "https://plato.stanford.edu/entries/epistemology-naturalized/": "Naturalized Epistemology",
                "https://plato.stanford.edu/entries/self-knowledge/": "Self-Knowledge",
                "https://plato.stanford.edu/entries/other-minds/": "Other Minds",
                "https://plato.stanford.edu/entries/feminism-epistemology/": "Feminist Epistemology and Philosophy of Science",
                "https://plato.stanford.edu/entries/epistemic-paradoxes/": "Epistemic Paradoxes",
                "https://plato.stanford.edu/entries/knowledge-how/": "Knowledge How",
                "https://plato.stanford.edu/entries/disagreement/": "Epistemology of Disagreement",
                "https://plato.stanford.edu/entries/epistemic-injustice/": "Epistemic Injustice",
                "https://plato.stanford.edu/entries/common-knowledge/": "Common Knowledge",
                "https://plato.stanford.edu/entries/formal-epistemology/": "Formal Epistemology",
                "https://plato.stanford.edu/entries/epistemic-luck/": "Epistemic Luck",
                "https://plato.stanford.edu/entries/gettier-problem/": "The Gettier Problem",
                "https://plato.stanford.edu/entries/belief/": "Belief",
                "https://plato.stanford.edu/entries/justification-epistemic/": "Epistemic Justification",
                "https://plato.stanford.edu/entries/truth/": "Truth",
                "https://plato.stanford.edu/entries/objectivity/": "Scientific Objectivity",
                "https://plato.stanford.edu/entries/relativism/": "Relativism",
                "https://plato.stanford.edu/entries/epistemology-religion/": "Epistemology of Religion",
                "https://plato.stanford.edu/entries/faith/": "Faith",
                "https://plato.stanford.edu/entries/fideism/": "Fideism",
                "https://plato.stanford.edu/entries/reformed-epistemology/": "Reformed Epistemology",
                "https://plato.stanford.edu/entries/religious-experience/": "Religious Experience",
                "https://plato.stanford.edu/entries/pragmatic-belief-god/": "Pragmatic Arguments and Belief in God",
                "https://plato.stanford.edu/entries/problem-of-evil/": "The Problem of Evil",
                "https://plato.stanford.edu/entries/cosmological-argument/": "Cosmological Argument",
                "https://plato.stanford.edu/entries/teleological-arguments/": "Teleological Arguments for God's Existence",
                "https://plato.stanford.edu/entries/ontological-arguments/": "Ontological Arguments",
            },
        },
        "metaphysics": {
            "pages": {
                "https://plato.stanford.edu/entries/metaphysics/": "Metaphysics",
                "https://plato.stanford.edu/entries/substance/": "Substance",
                "https://plato.stanford.edu/entries/properties/": "Properties",
                "https://plato.stanford.edu/entries/universals/": "Universals",
                "https://plato.stanford.edu/entries/universals-medieval/": "Medieval Theories of Universals",
                "https://plato.stanford.edu/entries/tropes/": "Tropes",
                "https://plato.stanford.edu/entries/natural-kinds/": "Natural Kinds",
                "https://plato.stanford.edu/entries/categories/": "Categories",
                "https://plato.stanford.edu/entries/identity/": "Identity",
                "https://plato.stanford.edu/entries/identity-personal/": "Personal Identity",
                "https://plato.stanford.edu/entries/identity-relative/": "Relative Identity",
                "https://plato.stanford.edu/entries/identity-time/": "Identity over Time",
                "https://plato.stanford.edu/entries/persistence/": "Persistence",
                "https://plato.stanford.edu/entries/temporal-parts/": "Temporal Parts",
                "https://plato.stanford.edu/entries/presentism/": "Presentism",
                "https://plato.stanford.edu/entries/eternalism/": "Eternalism",
                "https://plato.stanford.edu/entries/growing-block/": "The Growing Block Theory of the Future",
                "https://plato.stanford.edu/entries/time/": "Time",
                "https://plato.stanford.edu/entries/space-time/": "Space and Time",
                "https://plato.stanford.edu/entries/spacetime-theories/": "Spacetime Theories",
                "https://plato.stanford.edu/entries/causation-metaphysics/": "The Metaphysics of Causation",
                "https://plato.stanford.edu/entries/causation-counterfactual/": "Counterfactual Theories of Causation",
                "https://plato.stanford.edu/entries/causation-probabilistic/": "Probabilistic Causation",
                "https://plato.stanford.edu/entries/determinism-causal/": "Causal Determinism",
                "https://plato.stanford.edu/entries/free-will/": "Free Will",
                "https://plato.stanford.edu/entries/compatibilism/": "Compatibilism",
                "https://plato.stanford.edu/entries/incompatibilism-arguments/": "Arguments for Incompatibilism",
                "https://plato.stanford.edu/entries/libertarianism/": "Libertarianism",
                "https://plato.stanford.edu/entries/fatalism/": "Fatalism",
                "https://plato.stanford.edu/entries/modality-medieval/": "Medieval Theories of Modality",
                "https://plato.stanford.edu/entries/modality-varieties/": "Varieties of Modality",
                "https://plato.stanford.edu/entries/possible-worlds/": "Possible Worlds",
                "https://plato.stanford.edu/entries/possible-objects/": "Possible Objects",
                "https://plato.stanford.edu/entries/actualism/": "Actualism",
                "https://plato.stanford.edu/entries/necessitism-contingentism/": "Necessitism and Contingentism",
                "https://plato.stanford.edu/entries/dispositions/": "Dispositions",
                "https://plato.stanford.edu/entries/laws-of-nature/": "Laws of Nature",
                "https://plato.stanford.edu/entries/chance-randomness/": "Chance and Randomness",
                "https://plato.stanford.edu/entries/mereology/": "Mereology",
                "https://plato.stanford.edu/entries/abstract-objects/": "Abstract Objects",
                "https://plato.stanford.edu/entries/existence/": "Existence",
                "https://plato.stanford.edu/entries/nonexistent-objects/": "Nonexistent Objects",
                "https://plato.stanford.edu/entries/nothingness/": "Nothingness",
                "https://plato.stanford.edu/entries/truthmakers/": "Truthmakers",
                "https://plato.stanford.edu/entries/structural-realism/": "Structural Realism",
                "https://plato.stanford.edu/entries/grounding/": "Grounding",
                "https://plato.stanford.edu/entries/fundamentality/": "Fundamentality",
                "https://plato.stanford.edu/entries/ontological-dependence/": "Ontological Dependence",
                "https://plato.stanford.edu/entries/composition-objects/": "Composition of Objects",
                "https://plato.stanford.edu/entries/vagueness/": "Vagueness",
                "https://plato.stanford.edu/entries/events/": "Events",
                "https://plato.stanford.edu/entries/facts/": "Facts",
                "https://plato.stanford.edu/entries/states-of-affairs/": "States of Affairs",
                "https://plato.stanford.edu/entries/realism/": "Realism",
                "https://plato.stanford.edu/entries/nominalism-metaphysics/": "Nominalism in Metaphysics",
                "https://plato.stanford.edu/entries/platonism/": "Platonism in the Philosophy of Mathematics",
                "https://plato.stanford.edu/entries/idealism/": "Idealism",
                "https://plato.stanford.edu/entries/monism/": "Monism",
                "https://plato.stanford.edu/entries/dualism/": "Dualism",
                "https://plato.stanford.edu/entries/materialism-eliminative/": "Eliminative Materialism",
                "https://plato.stanford.edu/entries/physicalism/": "Physicalism",
            },
        },
        "ethics": {
            "pages": {
                "https://plato.stanford.edu/entries/ethics-virtue/": "Virtue Ethics",
                "https://plato.stanford.edu/entries/ethics-deontological/": "Deontological Ethics",
                "https://plato.stanford.edu/entries/consequentialism/": "Consequentialism",
                "https://plato.stanford.edu/entries/utilitarianism/": "Utilitarianism",
                "https://plato.stanford.edu/entries/utilitarianism-history/": "The History of Utilitarianism",
                "https://plato.stanford.edu/entries/moral-realism/": "Moral Realism",
                "https://plato.stanford.edu/entries/moral-anti-realism/": "Moral Anti-Realism",
                "https://plato.stanford.edu/entries/moral-relativism/": "Moral Relativism",
                "https://plato.stanford.edu/entries/moral-naturalism/": "Moral Naturalism",
                "https://plato.stanford.edu/entries/moral-non-naturalism/": "Moral Non-Naturalism",
                "https://plato.stanford.edu/entries/constructivism-metaethics/": "Constructivism in Metaethics",
                "https://plato.stanford.edu/entries/moral-motivation/": "Moral Motivation",
                "https://plato.stanford.edu/entries/moral-responsibility/": "Moral Responsibility",
                "https://plato.stanford.edu/entries/moral-luck/": "Moral Luck",
                "https://plato.stanford.edu/entries/moral-dilemmas/": "Moral Dilemmas",
                "https://plato.stanford.edu/entries/moral-particularism/": "Moral Particularism",
                "https://plato.stanford.edu/entries/moral-sentimentalism/": "Moral Sentimentalism",
                "https://plato.stanford.edu/entries/moral-psychology-empirical/": "Moral Psychology: Empirical Approaches",
                "https://plato.stanford.edu/entries/altruism/": "Altruism",
                "https://plato.stanford.edu/entries/egoism/": "Egoism",
                "https://plato.stanford.edu/entries/well-being/": "Well-Being",
                "https://plato.stanford.edu/entries/happiness/": "Happiness",
                "https://plato.stanford.edu/entries/hedonism/": "Hedonism",
                "https://plato.stanford.edu/entries/pleasure/": "Pleasure",
                "https://plato.stanford.edu/entries/autonomy-moral/": "Personal Autonomy",
                "https://plato.stanford.edu/entries/double-effect/": "The Doctrine of Double Effect",
                "https://plato.stanford.edu/entries/doing-allowing/": "Doing vs. Allowing Harm",
                "https://plato.stanford.edu/entries/killing-letting-die/": "Killing and Letting Die",
                "https://plato.stanford.edu/entries/supererogation/": "Supererogation",
                "https://plato.stanford.edu/entries/promise/": "Promises",
                "https://plato.stanford.edu/entries/consent/": "Consent",
                "https://plato.stanford.edu/entries/trust/": "Trust",
                "https://plato.stanford.edu/entries/rights/": "Rights",
                "https://plato.stanford.edu/entries/human-rights/": "Human Rights",
                "https://plato.stanford.edu/entries/justice/": "Justice",
                "https://plato.stanford.edu/entries/justice-distributive/": "Distributive Justice",
                "https://plato.stanford.edu/entries/justice-retributive/": "Retributive Justice",
                "https://plato.stanford.edu/entries/justice-global/": "Justice, Global",
                "https://plato.stanford.edu/entries/justice-intergenerational/": "Intergenerational Justice",
                "https://plato.stanford.edu/entries/equality/": "Equality",
                "https://plato.stanford.edu/entries/egalitarianism/": "Egalitarianism",
                "https://plato.stanford.edu/entries/contractarianism/": "Contractarianism",
                "https://plato.stanford.edu/entries/contractualism/": "Contractualism",
                "https://plato.stanford.edu/entries/value-theory/": "Value Theory",
                "https://plato.stanford.edu/entries/value-intrinsic-extrinsic/": "Intrinsic vs. Extrinsic Value",
                "https://plato.stanford.edu/entries/value-pluralism/": "Value Pluralism",
                "https://plato.stanford.edu/entries/thick-ethical-concepts/": "Thick Ethical Concepts",
                "https://plato.stanford.edu/entries/moral-character/": "Moral Character",
                "https://plato.stanford.edu/entries/moral-epistemology-a-priori/": "Moral Epistemology",
                "https://plato.stanford.edu/entries/ethics-environmental/": "Environmental Ethics",
                "https://plato.stanford.edu/entries/ethics-animal/": "The Moral Status of Animals",
                "https://plato.stanford.edu/entries/bioethics/": "Bioethics",
                "https://plato.stanford.edu/entries/informed-consent/": "Informed Consent",
                "https://plato.stanford.edu/entries/euthanasia/": "Euthanasia",
                "https://plato.stanford.edu/entries/death/": "Death",
                "https://plato.stanford.edu/entries/war/": "War",
                "https://plato.stanford.edu/entries/torture/": "Torture",
                "https://plato.stanford.edu/entries/punishment/": "Punishment",
                "https://plato.stanford.edu/entries/forgiveness/": "Forgiveness",
                "https://plato.stanford.edu/entries/love/": "Love",
            },
        },
        "logic": {
            "pages": {
                "https://plato.stanford.edu/entries/logic-classical/": "Classical Logic",
                "https://plato.stanford.edu/entries/logic-intuitionistic/": "Intuitionistic Logic",
                "https://plato.stanford.edu/entries/logic-modal/": "Modal Logic",
                "https://plato.stanford.edu/entries/logic-paraconsistent/": "Paraconsistent Logic",
                "https://plato.stanford.edu/entries/logic-relevance/": "Relevance Logic",
                "https://plato.stanford.edu/entries/logic-fuzzy/": "Fuzzy Logic",
                "https://plato.stanford.edu/entries/logic-many-valued/": "Many-Valued Logic",
                "https://plato.stanford.edu/entries/logic-free/": "Free Logic",
                "https://plato.stanford.edu/entries/logic-higher-order/": "Higher-Order Logic",
                "https://plato.stanford.edu/entries/logic-second-order/": "Second-Order and Higher-Order Logic",
                "https://plato.stanford.edu/entries/logic-temporal/": "Temporal Logic",
                "https://plato.stanford.edu/entries/logic-deontic/": "Deontic Logic",
                "https://plato.stanford.edu/entries/logic-epistemic/": "Epistemic Logic",
                "https://plato.stanford.edu/entries/logic-dynamic/": "Dynamic Logic",
                "https://plato.stanford.edu/entries/logic-linear/": "Linear Logic",
                "https://plato.stanford.edu/entries/logic-substructural/": "Substructural Logics",
                "https://plato.stanford.edu/entries/logic-algebraic-propositional/": "Algebraic Propositional Logic",
                "https://plato.stanford.edu/entries/logic-combinatory/": "Combinatory Logic",
                "https://plato.stanford.edu/entries/logic-conditional/": "The Logic of Conditionals",
                "https://plato.stanford.edu/entries/logic-nonmonotonic/": "Non-Monotonic Logic",
                "https://plato.stanford.edu/entries/logic-informal/": "Informal Logic",
                "https://plato.stanford.edu/entries/logic-inductive/": "Inductive Logic",
                "https://plato.stanford.edu/entries/logical-consequence/": "Logical Consequence",
                "https://plato.stanford.edu/entries/logical-constants/": "Logical Constants",
                "https://plato.stanford.edu/entries/logical-truth/": "Logical Truth",
                "https://plato.stanford.edu/entries/logical-pluralism/": "Logical Pluralism",
                "https://plato.stanford.edu/entries/model-theory/": "Model Theory",
                "https://plato.stanford.edu/entries/proof-theory/": "Proof Theory",
                "https://plato.stanford.edu/entries/set-theory/": "Set Theory",
                "https://plato.stanford.edu/entries/type-theory/": "Type Theory",
                "https://plato.stanford.edu/entries/category-theory/": "Category Theory",
                "https://plato.stanford.edu/entries/computability/": "Computability and Complexity",
                "https://plato.stanford.edu/entries/decidability/": "Decidability",
                "https://plato.stanford.edu/entries/goedel-incompleteness/": "Goedel's Incompleteness Theorems",
                "https://plato.stanford.edu/entries/russell-paradox/": "Russell's Paradox",
                "https://plato.stanford.edu/entries/liar-paradox/": "The Liar Paradox",
                "https://plato.stanford.edu/entries/sorites-paradox/": "The Sorites Paradox",
                "https://plato.stanford.edu/entries/curry-paradox/": "Curry's Paradox",
                "https://plato.stanford.edu/entries/truth-values/": "Truth Values",
                "https://plato.stanford.edu/entries/truth-axiomatic/": "Axiomatic Theories of Truth",
                "https://plato.stanford.edu/entries/truth-coherence/": "The Coherence Theory of Truth",
                "https://plato.stanford.edu/entries/truth-correspondence/": "The Correspondence Theory of Truth",
                "https://plato.stanford.edu/entries/truth-deflationary/": "The Deflationary Theory of Truth",
                "https://plato.stanford.edu/entries/truth-identity/": "The Identity Theory of Truth",
                "https://plato.stanford.edu/entries/truth-pluralist/": "Pluralist Theories of Truth",
                "https://plato.stanford.edu/entries/truth-revision/": "The Revision Theory of Truth",
                "https://plato.stanford.edu/entries/tarski-truth/": "Tarski's Truth Definitions",
                "https://plato.stanford.edu/entries/propositional-attitude-reports/": "Propositional Attitude Reports",
                "https://plato.stanford.edu/entries/quantifiers-substitutional/": "Substitutional Quantifiers",
                "https://plato.stanford.edu/entries/descriptions/": "Descriptions",
                "https://plato.stanford.edu/entries/reference/": "Reference",
                "https://plato.stanford.edu/entries/rigid-designators/": "Rigid Designators",
                "https://plato.stanford.edu/entries/indexicals/": "Indexicals",
                "https://plato.stanford.edu/entries/paradox-skolem/": "Skolem's Paradox",
            },
        },
        "philosophy-of-mind": {
            "pages": {
                "https://plato.stanford.edu/entries/mind-body/": "The Mind-Body Problem",
                "https://plato.stanford.edu/entries/consciousness/": "Consciousness",
                "https://plato.stanford.edu/entries/qualia/": "Qualia",
                "https://plato.stanford.edu/entries/intentionality/": "Intentionality",
                "https://plato.stanford.edu/entries/mental-content/": "Mental Content",
                "https://plato.stanford.edu/entries/mental-representation/": "Mental Representation",
                "https://plato.stanford.edu/entries/mental-causation/": "Mental Causation",
                "https://plato.stanford.edu/entries/functionalism/": "Functionalism",
                "https://plato.stanford.edu/entries/identity-theory/": "The Identity Theory of Mind",
                "https://plato.stanford.edu/entries/behaviorism/": "Behaviorism",
                "https://plato.stanford.edu/entries/dualism/": "Dualism",
                "https://plato.stanford.edu/entries/eliminative-materialism/": "Eliminative Materialism",
                "https://plato.stanford.edu/entries/property-dualism/": "Property Dualism",
                "https://plato.stanford.edu/entries/panpsychism/": "Panpsychism",
                "https://plato.stanford.edu/entries/epiphenomenalism/": "Epiphenomenalism",
                "https://plato.stanford.edu/entries/supervenience/": "Supervenience",
                "https://plato.stanford.edu/entries/multiple-realizability/": "Multiple Realizability",
                "https://plato.stanford.edu/entries/chinese-room/": "The Chinese Room Argument",
                "https://plato.stanford.edu/entries/other-minds/": "Other Minds",
                "https://plato.stanford.edu/entries/zombies/": "Zombies",
                "https://plato.stanford.edu/entries/consciousness-higher/": "Higher-Order Theories of Consciousness",
                "https://plato.stanford.edu/entries/consciousness-representational/": "Representational Theories of Consciousness",
                "https://plato.stanford.edu/entries/consciousness-temporal/": "Temporal Consciousness",
                "https://plato.stanford.edu/entries/self-consciousness/": "Self-Consciousness",
                "https://plato.stanford.edu/entries/perception-contents/": "The Contents of Perception",
                "https://plato.stanford.edu/entries/perception-disjunctive/": "The Disjunctive Theory of Perception",
                "https://plato.stanford.edu/entries/perception-problem/": "The Problem of Perception",
                "https://plato.stanford.edu/entries/color/": "Color",
                "https://plato.stanford.edu/entries/emotion/": "Emotion",
                "https://plato.stanford.edu/entries/imagination/": "Imagination",
                "https://plato.stanford.edu/entries/memory/": "Memory",
                "https://plato.stanford.edu/entries/attention/": "Attention",
                "https://plato.stanford.edu/entries/pain/": "Pain",
                "https://plato.stanford.edu/entries/pleasure/": "Pleasure",
                "https://plato.stanford.edu/entries/desire/": "Desire",
                "https://plato.stanford.edu/entries/belief/": "Belief",
                "https://plato.stanford.edu/entries/concepts/": "Concepts",
                "https://plato.stanford.edu/entries/folk-psychology/": "Folk Psychology",
                "https://plato.stanford.edu/entries/cognitive-science/": "Cognitive Science",
                "https://plato.stanford.edu/entries/computational-mind/": "The Computational Theory of Mind",
                "https://plato.stanford.edu/entries/connectionism/": "Connectionism",
                "https://plato.stanford.edu/entries/embodied-cognition/": "Embodied Cognition",
                "https://plato.stanford.edu/entries/extended-mind/": "The Extended Mind",
                "https://plato.stanford.edu/entries/animal-cognition/": "Animal Cognition",
                "https://plato.stanford.edu/entries/animal-consciousness/": "Animal Consciousness",
                "https://plato.stanford.edu/entries/artificial-intelligence/": "Artificial Intelligence",
                "https://plato.stanford.edu/entries/consciousness-neuroscience/": "The Neuroscience of Consciousness",
                "https://plato.stanford.edu/entries/mental-illness/": "Mental Illness",
                "https://plato.stanford.edu/entries/personal-identity/": "Personal Identity",
                "https://plato.stanford.edu/entries/free-will/": "Free Will",
                "https://plato.stanford.edu/entries/dreams/": "Dreams",
                "https://plato.stanford.edu/entries/unconscious-freud/": "Freud and the Unconscious",
                "https://plato.stanford.edu/entries/mental-imagery/": "Mental Imagery",
                "https://plato.stanford.edu/entries/thought-language/": "The Language of Thought Hypothesis",
                "https://plato.stanford.edu/entries/modularity-mind/": "Modularity of Mind",
            },
        },
        "philosophy-of-science": {
            "pages": {
                "https://plato.stanford.edu/entries/scientific-realism/": "Scientific Realism",
                "https://plato.stanford.edu/entries/scientific-explanation/": "Scientific Explanation",
                "https://plato.stanford.edu/entries/scientific-discovery/": "Scientific Discovery",
                "https://plato.stanford.edu/entries/scientific-progress/": "Scientific Progress",
                "https://plato.stanford.edu/entries/scientific-revolutions/": "Scientific Revolutions",
                "https://plato.stanford.edu/entries/scientific-reduction/": "Scientific Reduction",
                "https://plato.stanford.edu/entries/scientific-objectivity/": "Scientific Objectivity",
                "https://plato.stanford.edu/entries/confirmation/": "Confirmation",
                "https://plato.stanford.edu/entries/induction-problem/": "The Problem of Induction",
                "https://plato.stanford.edu/entries/underdetermination/": "Underdetermination of Scientific Theory",
                "https://plato.stanford.edu/entries/empiricism/": "Empiricism",
                "https://plato.stanford.edu/entries/constructive-empiricism/": "Constructive Empiricism",
                "https://plato.stanford.edu/entries/instrumentalism/": "Instrumentalism",
                "https://plato.stanford.edu/entries/models-science/": "Models in Science",
                "https://plato.stanford.edu/entries/idealization/": "Idealization",
                "https://plato.stanford.edu/entries/thought-experiment/": "Thought Experiments",
                "https://plato.stanford.edu/entries/experiments/": "Experiment in Physics",
                "https://plato.stanford.edu/entries/measurement-science/": "Measurement in Science",
                "https://plato.stanford.edu/entries/prediction-accommodation/": "Prediction vs. Accommodation",
                "https://plato.stanford.edu/entries/natural-kinds/": "Natural Kinds",
                "https://plato.stanford.edu/entries/laws-of-nature/": "Laws of Nature",
                "https://plato.stanford.edu/entries/causation-science/": "Causation in Science",
                "https://plato.stanford.edu/entries/mechanism/": "Mechanisms in Science",
                "https://plato.stanford.edu/entries/probability-interpret/": "Interpretations of Probability",
                "https://plato.stanford.edu/entries/statistics-philosophy/": "Philosophy of Statistics",
                "https://plato.stanford.edu/entries/bayesian-epistemology/": "Bayesian Epistemology",
                "https://plato.stanford.edu/entries/simplicity/": "Simplicity",
                "https://plato.stanford.edu/entries/parsimony/": "Parsimony",
                "https://plato.stanford.edu/entries/demarcation-science/": "Science and Pseudo-Science",
                "https://plato.stanford.edu/entries/pseudo-science/": "Pseudo-Science",
                "https://plato.stanford.edu/entries/values-science/": "Values in Science",
                "https://plato.stanford.edu/entries/science-theory-observation/": "Theory and Observation in Science",
                "https://plato.stanford.edu/entries/physics-experiment/": "Experiment in Physics",
                "https://plato.stanford.edu/entries/quantum-mechanics/": "Quantum Mechanics",
                "https://plato.stanford.edu/entries/quantum-field-theory/": "Quantum Field Theory",
                "https://plato.stanford.edu/entries/spacetime-theories/": "Spacetime Theories",
                "https://plato.stanford.edu/entries/cosmology/": "Philosophy of Cosmology",
                "https://plato.stanford.edu/entries/cosmology-theology/": "Cosmology and Theology",
                "https://plato.stanford.edu/entries/evolution/": "Evolution",
                "https://plato.stanford.edu/entries/natural-selection/": "Natural Selection",
                "https://plato.stanford.edu/entries/adaptationism/": "Adaptationism",
                "https://plato.stanford.edu/entries/species/": "Species",
                "https://plato.stanford.edu/entries/biology-philosophy/": "Philosophy of Biology",
                "https://plato.stanford.edu/entries/ecology/": "Ecology",
                "https://plato.stanford.edu/entries/genetics-history/": "The History of Genetics",
                "https://plato.stanford.edu/entries/genetics-molecular/": "Molecular Genetics",
                "https://plato.stanford.edu/entries/neuroscience-philosophy/": "Philosophy of Neuroscience",
                "https://plato.stanford.edu/entries/cognitive-science/": "Cognitive Science",
                "https://plato.stanford.edu/entries/social-science-philosophy/": "Philosophy of Social Science",
                "https://plato.stanford.edu/entries/economics-philosophy/": "Philosophy of Economics",
            },
        },
        "philosophy-of-language": {
            "pages": {
                "https://plato.stanford.edu/entries/meaning/": "Meaning",
                "https://plato.stanford.edu/entries/reference/": "Reference",
                "https://plato.stanford.edu/entries/sense-reference/": "Sense and Reference",
                "https://plato.stanford.edu/entries/descriptions/": "Descriptions",
                "https://plato.stanford.edu/entries/names/": "Names",
                "https://plato.stanford.edu/entries/rigid-designators/": "Rigid Designators",
                "https://plato.stanford.edu/entries/indexicals/": "Indexicals",
                "https://plato.stanford.edu/entries/pragmatics/": "Pragmatics",
                "https://plato.stanford.edu/entries/speech-acts/": "Speech Acts",
                "https://plato.stanford.edu/entries/implicature/": "Implicature",
                "https://plato.stanford.edu/entries/presupposition/": "Presupposition",
                "https://plato.stanford.edu/entries/metaphor/": "Metaphor",
                "https://plato.stanford.edu/entries/vagueness/": "Vagueness",
                "https://plato.stanford.edu/entries/ambiguity/": "Ambiguity",
                "https://plato.stanford.edu/entries/compositionality/": "Compositionality",
                "https://plato.stanford.edu/entries/analytic-synthetic/": "The Analytic/Synthetic Distinction",
                "https://plato.stanford.edu/entries/propositions/": "Propositions",
                "https://plato.stanford.edu/entries/truth-correspondence/": "The Correspondence Theory of Truth",
                "https://plato.stanford.edu/entries/truth-deflationary/": "The Deflationary Theory of Truth",
                "https://plato.stanford.edu/entries/truth-coherence/": "The Coherence Theory of Truth",
                "https://plato.stanford.edu/entries/language-thought/": "The Language of Thought Hypothesis",
                "https://plato.stanford.edu/entries/private-language/": "Private Language",
                "https://plato.stanford.edu/entries/rule-following/": "Rule-Following and Intentionality",
                "https://plato.stanford.edu/entries/translation-indeterminacy/": "Indeterminacy of Translation",
                "https://plato.stanford.edu/entries/radical-interpretation/": "Radical Interpretation",
                "https://plato.stanford.edu/entries/convention/": "Convention",
                "https://plato.stanford.edu/entries/communication/": "Communication",
                "https://plato.stanford.edu/entries/assertion/": "Assertion",
                "https://plato.stanford.edu/entries/lying-definition/": "The Definition of Lying",
                "https://plato.stanford.edu/entries/slurs/": "Slurs",
                "https://plato.stanford.edu/entries/pornography-censorship/": "Pornography and Censorship",
                "https://plato.stanford.edu/entries/language-cognition/": "Language and Cognition",
                "https://plato.stanford.edu/entries/semantics-conceptual-role/": "Conceptual Role Semantics",
                "https://plato.stanford.edu/entries/possible-worlds-semantics/": "Possible Worlds Semantics",
                "https://plato.stanford.edu/entries/situation-semantics/": "Situation Semantics",
                "https://plato.stanford.edu/entries/dynamic-semantics/": "Dynamic Semantics",
                "https://plato.stanford.edu/entries/game-theoretic-semantics/": "Game-Theoretic Semantics",
                "https://plato.stanford.edu/entries/truth-values/": "Truth Values",
                "https://plato.stanford.edu/entries/logical-form/": "Logical Form",
                "https://plato.stanford.edu/entries/quantifiers-substitutional/": "Substitutional Quantifiers",
            },
        },
        "political-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/political-obligation/": "Political Obligation",
                "https://plato.stanford.edu/entries/authority/": "Authority",
                "https://plato.stanford.edu/entries/legitimacy/": "Political Legitimacy",
                "https://plato.stanford.edu/entries/sovereignty/": "Sovereignty",
                "https://plato.stanford.edu/entries/democracy/": "Democracy",
                "https://plato.stanford.edu/entries/liberalism/": "Liberalism",
                "https://plato.stanford.edu/entries/libertarianism/": "Libertarianism",
                "https://plato.stanford.edu/entries/conservatism/": "Conservatism",
                "https://plato.stanford.edu/entries/socialism/": "Socialism",
                "https://plato.stanford.edu/entries/anarchism/": "Anarchism",
                "https://plato.stanford.edu/entries/communitarianism/": "Communitarianism",
                "https://plato.stanford.edu/entries/multiculturalism/": "Multiculturalism",
                "https://plato.stanford.edu/entries/feminism-political/": "Feminist Political Philosophy",
                "https://plato.stanford.edu/entries/cosmopolitanism/": "Cosmopolitanism",
                "https://plato.stanford.edu/entries/nationalism/": "Nationalism",
                "https://plato.stanford.edu/entries/self-determination/": "Self-Determination",
                "https://plato.stanford.edu/entries/secession/": "Secession",
                "https://plato.stanford.edu/entries/colonialism/": "Colonialism",
                "https://plato.stanford.edu/entries/exploitation/": "Exploitation",
                "https://plato.stanford.edu/entries/freedom-speech/": "Freedom of Speech",
                "https://plato.stanford.edu/entries/freedom-association/": "Freedom of Association",
                "https://plato.stanford.edu/entries/toleration/": "Toleration",
                "https://plato.stanford.edu/entries/civil-disobedience/": "Civil Disobedience",
                "https://plato.stanford.edu/entries/revolution/": "Revolution",
                "https://plato.stanford.edu/entries/political-representation/": "Political Representation",
                "https://plato.stanford.edu/entries/voting/": "Voting",
                "https://plato.stanford.edu/entries/public-reason/": "Public Reason",
                "https://plato.stanford.edu/entries/rawls/": "John Rawls",
                "https://plato.stanford.edu/entries/original-position/": "Original Position",
                "https://plato.stanford.edu/entries/reflective-equilibrium/": "Reflective Equilibrium",
                "https://plato.stanford.edu/entries/social-contract/": "Social Contract Theory",
                "https://plato.stanford.edu/entries/property/": "Property and Ownership",
                "https://plato.stanford.edu/entries/markets/": "Markets",
                "https://plato.stanford.edu/entries/redistribution/": "Redistribution",
                "https://plato.stanford.edu/entries/poverty-relief/": "Poverty and Global Justice",
                "https://plato.stanford.edu/entries/immigration/": "Immigration",
                "https://plato.stanford.edu/entries/globalization/": "Globalization",
                "https://plato.stanford.edu/entries/just-war/": "Just War Theory",
                "https://plato.stanford.edu/entries/terrorism/": "Terrorism",
                "https://plato.stanford.edu/entries/human-rights/": "Human Rights",
                "https://plato.stanford.edu/entries/reparations/": "Reparations",
                "https://plato.stanford.edu/entries/affirmative-action/": "Affirmative Action",
                "https://plato.stanford.edu/entries/domination/": "Domination",
                "https://plato.stanford.edu/entries/republicanism/": "Republicanism",
                "https://plato.stanford.edu/entries/populism/": "Populism",
            },
        },
        "aesthetics": {
            "pages": {
                "https://plato.stanford.edu/entries/aesthetics/": "Aesthetics",
                "https://plato.stanford.edu/entries/beauty/": "Beauty",
                "https://plato.stanford.edu/entries/aesthetic-judgment/": "Aesthetic Judgment",
                "https://plato.stanford.edu/entries/art-definition/": "The Definition of Art",
                "https://plato.stanford.edu/entries/artistic-expression/": "Artistic Expression",
                "https://plato.stanford.edu/entries/artistic-creation/": "Artistic Creation",
                "https://plato.stanford.edu/entries/fiction/": "Fiction",
                "https://plato.stanford.edu/entries/narrative/": "Narrative",
                "https://plato.stanford.edu/entries/tragedy/": "Tragedy",
                "https://plato.stanford.edu/entries/humor/": "Humor",
                "https://plato.stanford.edu/entries/sublime/": "The Sublime",
                "https://plato.stanford.edu/entries/taste/": "Taste",
                "https://plato.stanford.edu/entries/aesthetic-experience/": "Aesthetic Experience",
                "https://plato.stanford.edu/entries/environmental-aesthetics/": "Environmental Aesthetics",
                "https://plato.stanford.edu/entries/music/": "Philosophy of Music",
                "https://plato.stanford.edu/entries/film-philosophy/": "Philosophy of Film",
                "https://plato.stanford.edu/entries/photography-aesthetics/": "Aesthetics of Photography",
                "https://plato.stanford.edu/entries/dance/": "Philosophy of Dance",
                "https://plato.stanford.edu/entries/architecture-philosophy/": "Philosophy of Architecture",
                "https://plato.stanford.edu/entries/food-aesthetics/": "Aesthetics of Food",
                "https://plato.stanford.edu/entries/forgery-art/": "Forgery in Art",
                "https://plato.stanford.edu/entries/moral-aesthetic/": "Moral and Aesthetic Judgments",
                "https://plato.stanford.edu/entries/pictorial-representation/": "Pictorial Representation",
                "https://plato.stanford.edu/entries/depiction/": "Depiction",
                "https://plato.stanford.edu/entries/imagination-aesthetics/": "Imagination and Aesthetics",
                "https://plato.stanford.edu/entries/art-ontology/": "The Ontology of Art",
                "https://plato.stanford.edu/entries/art-value/": "The Value of Art",
                "https://plato.stanford.edu/entries/art-criticism/": "Art Criticism",
                "https://plato.stanford.edu/entries/creativity/": "Creativity",
                "https://plato.stanford.edu/entries/aesthetic-concept/": "Aesthetic Concepts",
            },
        },
        "philosophy-of-religion": {
            "pages": {
                "https://plato.stanford.edu/entries/philosophy-religion/": "Philosophy of Religion",
                "https://plato.stanford.edu/entries/god-necessary-being/": "God as a Necessary Being",
                "https://plato.stanford.edu/entries/divine-simplicity/": "Divine Simplicity",
                "https://plato.stanford.edu/entries/divine-omniscience/": "Omniscience",
                "https://plato.stanford.edu/entries/divine-omnipotence/": "Omnipotence",
                "https://plato.stanford.edu/entries/divine-freedom/": "Divine Freedom",
                "https://plato.stanford.edu/entries/divine-providence/": "Divine Providence",
                "https://plato.stanford.edu/entries/creation-conservation/": "Creation and Conservation",
                "https://plato.stanford.edu/entries/miracles/": "Miracles",
                "https://plato.stanford.edu/entries/prayer/": "Philosophy of Prayer",
                "https://plato.stanford.edu/entries/heaven-hell/": "Heaven and Hell in Christian Thought",
                "https://plato.stanford.edu/entries/trinity/": "The Trinity",
                "https://plato.stanford.edu/entries/incarnation/": "The Incarnation",
                "https://plato.stanford.edu/entries/atonement/": "Atonement",
                "https://plato.stanford.edu/entries/resurrection/": "Resurrection",
                "https://plato.stanford.edu/entries/afterlife/": "Afterlife",
                "https://plato.stanford.edu/entries/soul/": "The Soul",
                "https://plato.stanford.edu/entries/immortality/": "Immortality",
                "https://plato.stanford.edu/entries/mysticism/": "Mysticism",
                "https://plato.stanford.edu/entries/religious-pluralism/": "Religious Pluralism",
                "https://plato.stanford.edu/entries/religion-science/": "Religion and Science",
                "https://plato.stanford.edu/entries/religion-morality/": "Religion and Morality",
                "https://plato.stanford.edu/entries/divine-command/": "Divine Command Theory",
                "https://plato.stanford.edu/entries/natural-theology/": "Natural Theology",
                "https://plato.stanford.edu/entries/negative-theology/": "Negative Theology",
                "https://plato.stanford.edu/entries/phenomenology-religion/": "Phenomenology of Religion",
                "https://plato.stanford.edu/entries/process-theism/": "Process Theism",
                "https://plato.stanford.edu/entries/open-theism/": "Open Theism",
                "https://plato.stanford.edu/entries/pantheism/": "Pantheism",
                "https://plato.stanford.edu/entries/panentheism/": "Panentheism",
            },
        },
        "history-of-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/plato/": "Plato",
                "https://plato.stanford.edu/entries/aristotle/": "Aristotle",
                "https://plato.stanford.edu/entries/socrates/": "Socrates",
                "https://plato.stanford.edu/entries/presocratics/": "Presocratic Philosophy",
                "https://plato.stanford.edu/entries/atomism-ancient/": "Ancient Atomism",
                "https://plato.stanford.edu/entries/stoicism/": "Stoicism",
                "https://plato.stanford.edu/entries/epicurus/": "Epicurus",
                "https://plato.stanford.edu/entries/skepticism-ancient/": "Ancient Skepticism",
                "https://plato.stanford.edu/entries/neoplatonism/": "Neoplatonism",
                "https://plato.stanford.edu/entries/augustine/": "Augustine",
                "https://plato.stanford.edu/entries/aquinas/": "Thomas Aquinas",
                "https://plato.stanford.edu/entries/anselm/": "Anselm of Canterbury",
                "https://plato.stanford.edu/entries/abelard/": "Peter Abelard",
                "https://plato.stanford.edu/entries/duns-scotus/": "John Duns Scotus",
                "https://plato.stanford.edu/entries/ockham/": "William of Ockham",
                "https://plato.stanford.edu/entries/medieval-political/": "Medieval Political Philosophy",
                "https://plato.stanford.edu/entries/descartes/": "Rene Descartes",
                "https://plato.stanford.edu/entries/spinoza/": "Baruch Spinoza",
                "https://plato.stanford.edu/entries/leibniz/": "Gottfried Wilhelm Leibniz",
                "https://plato.stanford.edu/entries/locke/": "John Locke",
                "https://plato.stanford.edu/entries/hume/": "David Hume",
                "https://plato.stanford.edu/entries/berkeley/": "George Berkeley",
                "https://plato.stanford.edu/entries/kant/": "Immanuel Kant",
                "https://plato.stanford.edu/entries/hegel/": "Georg Wilhelm Friedrich Hegel",
                "https://plato.stanford.edu/entries/marx/": "Karl Marx",
                "https://plato.stanford.edu/entries/nietzsche/": "Friedrich Nietzsche",
                "https://plato.stanford.edu/entries/kierkegaard/": "Soren Kierkegaard",
                "https://plato.stanford.edu/entries/schopenhauer/": "Arthur Schopenhauer",
                "https://plato.stanford.edu/entries/mill/": "John Stuart Mill",
                "https://plato.stanford.edu/entries/bentham/": "Jeremy Bentham",
                "https://plato.stanford.edu/entries/hobbes/": "Thomas Hobbes",
                "https://plato.stanford.edu/entries/rousseau/": "Jean-Jacques Rousseau",
                "https://plato.stanford.edu/entries/montesquieu/": "Montesquieu",
                "https://plato.stanford.edu/entries/machiavelli/": "Niccolo Machiavelli",
                "https://plato.stanford.edu/entries/bacon-francis/": "Francis Bacon",
                "https://plato.stanford.edu/entries/galileo/": "Galileo Galilei",
                "https://plato.stanford.edu/entries/newton-philosophy/": "Newton's Philosophy",
                "https://plato.stanford.edu/entries/peirce/": "Charles Sanders Peirce",
                "https://plato.stanford.edu/entries/james/": "William James",
                "https://plato.stanford.edu/entries/dewey/": "John Dewey",
                "https://plato.stanford.edu/entries/whitehead/": "Alfred North Whitehead",
                "https://plato.stanford.edu/entries/russell/": "Bertrand Russell",
                "https://plato.stanford.edu/entries/wittgenstein/": "Ludwig Wittgenstein",
                "https://plato.stanford.edu/entries/frege/": "Gottlob Frege",
                "https://plato.stanford.edu/entries/husserl/": "Edmund Husserl",
                "https://plato.stanford.edu/entries/heidegger/": "Martin Heidegger",
                "https://plato.stanford.edu/entries/sartre/": "Jean-Paul Sartre",
                "https://plato.stanford.edu/entries/beauvoir/": "Simone de Beauvoir",
                "https://plato.stanford.edu/entries/foucault/": "Michel Foucault",
                "https://plato.stanford.edu/entries/derrida/": "Jacques Derrida",
            },
        },
        "ancient-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/ancient-soul/": "Ancient Theories of Soul",
                "https://plato.stanford.edu/entries/ancient-ethics/": "Ancient Ethics",
                "https://plato.stanford.edu/entries/ancient-political/": "Ancient Political Philosophy",
                "https://plato.stanford.edu/entries/ancient-rhetoric/": "Ancient Rhetoric",
                "https://plato.stanford.edu/entries/ancient-epistemology/": "Ancient Epistemology",
                "https://plato.stanford.edu/entries/ancient-medicine/": "Ancient Medicine",
                "https://plato.stanford.edu/entries/ancient-atomism/": "Ancient Atomism",
                "https://plato.stanford.edu/entries/presocratic-politics/": "Presocratic Political Philosophy",
                "https://plato.stanford.edu/entries/presocratics/": "Presocratic Philosophy",
                "https://plato.stanford.edu/entries/thales/": "Thales of Miletus",
                "https://plato.stanford.edu/entries/anaximander/": "Anaximander",
                "https://plato.stanford.edu/entries/anaximenes/": "Anaximenes",
                "https://plato.stanford.edu/entries/heraclitus/": "Heraclitus",
                "https://plato.stanford.edu/entries/parmenides/": "Parmenides",
                "https://plato.stanford.edu/entries/zeno-elea/": "Zeno of Elea",
                "https://plato.stanford.edu/entries/empedocles/": "Empedocles",
                "https://plato.stanford.edu/entries/anaxagoras/": "Anaxagoras",
                "https://plato.stanford.edu/entries/democritus/": "Democritus",
                "https://plato.stanford.edu/entries/protagoras/": "Protagoras",
                "https://plato.stanford.edu/entries/gorgias/": "Gorgias",
                "https://plato.stanford.edu/entries/plato-metaphysics/": "Plato's Metaphysics",
                "https://plato.stanford.edu/entries/plato-ethics/": "Plato's Ethics",
                "https://plato.stanford.edu/entries/plato-epistemology/": "Plato's Epistemology",
                "https://plato.stanford.edu/entries/plato-rhetoric/": "Plato on Rhetoric",
                "https://plato.stanford.edu/entries/plato-utopia/": "Plato's Utopia",
                "https://plato.stanford.edu/entries/aristotle-metaphysics/": "Aristotle's Metaphysics",
                "https://plato.stanford.edu/entries/aristotle-ethics/": "Aristotle's Ethics",
                "https://plato.stanford.edu/entries/aristotle-politics/": "Aristotle's Political Theory",
                "https://plato.stanford.edu/entries/aristotle-logic/": "Aristotle's Logic",
                "https://plato.stanford.edu/entries/aristotle-biology/": "Aristotle's Biology",
                "https://plato.stanford.edu/entries/aristotle-rhetoric/": "Aristotle's Rhetoric",
                "https://plato.stanford.edu/entries/cyrenaics/": "Cyrenaics",
                "https://plato.stanford.edu/entries/megarians/": "Megarian School",
                "https://plato.stanford.edu/entries/diogenes-sinope/": "Diogenes of Sinope",
                "https://plato.stanford.edu/entries/pyrrho/": "Pyrrho",
            },
        },
        "medieval-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/medieval-philosophy/": "Medieval Philosophy",
                "https://plato.stanford.edu/entries/arabic-islamic-metaphysics/": "Arabic and Islamic Metaphysics",
                "https://plato.stanford.edu/entries/arabic-islamic-natural/": "Arabic and Islamic Philosophy of Nature",
                "https://plato.stanford.edu/entries/arabic-islamic-language/": "Arabic and Islamic Philosophy of Language",
                "https://plato.stanford.edu/entries/arabic-islamic-mind/": "Arabic and Islamic Philosophy of Mind",
                "https://plato.stanford.edu/entries/arabic-islamic-ethics/": "Arabic and Islamic Ethics",
                "https://plato.stanford.edu/entries/arabic-islamic-political/": "Arabic and Islamic Political Philosophy",
                "https://plato.stanford.edu/entries/al-farabi/": "Al-Farabi",
                "https://plato.stanford.edu/entries/al-farabi-logic/": "Al-Farabi's Logic",
                "https://plato.stanford.edu/entries/avicenna/": "Avicenna (Ibn Sina)",
                "https://plato.stanford.edu/entries/avicenna-metaphysics/": "Avicenna's Metaphysics",
                "https://plato.stanford.edu/entries/averroes/": "Averroes (Ibn Rushd)",
                "https://plato.stanford.edu/entries/maimonides/": "Maimonides",
                "https://plato.stanford.edu/entries/gersonides/": "Gersonides",
                "https://plato.stanford.edu/entries/crescas/": "Hasdai Crescas",
                "https://plato.stanford.edu/entries/aquinas-moral-political/": "Aquinas' Moral, Political, and Legal Philosophy",
                "https://plato.stanford.edu/entries/scotus-ethics/": "Duns Scotus' Ethics",
                "https://plato.stanford.edu/entries/ockham-political/": "Ockham's Political Philosophy",
                "https://plato.stanford.edu/entries/buridan/": "John Buridan",
                "https://plato.stanford.edu/entries/medieval-terms/": "Medieval Theories of the Term",
                "https://plato.stanford.edu/entries/medieval-categories/": "Medieval Theories of Categories",
                "https://plato.stanford.edu/entries/universals-medieval/": "Medieval Theories of Universals",
                "https://plato.stanford.edu/entries/medieval-literary/": "Medieval Literary Theory",
                "https://plato.stanford.edu/entries/medieval-mereology/": "Medieval Mereology",
                "https://plato.stanford.edu/entries/medieval-obligationes/": "Medieval Theories of Obligationes",
                "https://plato.stanford.edu/entries/medieval-syllogism/": "Medieval Theories of the Syllogism",
                "https://plato.stanford.edu/entries/medieval-modality/": "Medieval Theories of Modality",
                "https://plato.stanford.edu/entries/boethius/": "Boethius",
                "https://plato.stanford.edu/entries/bonaventure/": "Bonaventure",
                "https://plato.stanford.edu/entries/henry-ghent/": "Henry of Ghent",
                "https://plato.stanford.edu/entries/albert-great/": "Albert the Great",
                "https://plato.stanford.edu/entries/peter-lombard/": "Peter Lombard",
                "https://plato.stanford.edu/entries/nicholas-cusa/": "Nicholas of Cusa",
                "https://plato.stanford.edu/entries/roger-bacon/": "Roger Bacon",
                "https://plato.stanford.edu/entries/william-auxerre/": "William of Auxerre",
            },
        },
        "modern-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/descartes-epistemology/": "Descartes' Epistemology",
                "https://plato.stanford.edu/entries/descartes-modal/": "Descartes' Modal Metaphysics",
                "https://plato.stanford.edu/entries/descartes-ideas/": "Descartes' Theory of Ideas",
                "https://plato.stanford.edu/entries/descartes-physics/": "Descartes' Physics",
                "https://plato.stanford.edu/entries/spinoza-modal/": "Spinoza's Modal Metaphysics",
                "https://plato.stanford.edu/entries/spinoza-political/": "Spinoza's Political Philosophy",
                "https://plato.stanford.edu/entries/leibniz-modal/": "Leibniz's Modal Metaphysics",
                "https://plato.stanford.edu/entries/leibniz-mind-body/": "Leibniz on the Mind-Body Problem",
                "https://plato.stanford.edu/entries/leibniz-ethics/": "Leibniz's Ethics",
                "https://plato.stanford.edu/entries/leibniz-physics/": "Leibniz's Philosophy of Physics",
                "https://plato.stanford.edu/entries/locke-political/": "Locke's Political Philosophy",
                "https://plato.stanford.edu/entries/locke-freedom/": "Locke on Freedom",
                "https://plato.stanford.edu/entries/hume-moral/": "Hume's Moral Philosophy",
                "https://plato.stanford.edu/entries/hume-religion/": "Hume on Religion",
                "https://plato.stanford.edu/entries/hume-causation/": "Hume on Causation",
                "https://plato.stanford.edu/entries/hume-epistemology/": "Hume's Epistemology",
                "https://plato.stanford.edu/entries/berkeley-ideas/": "Berkeley's Theory of Ideas",
                "https://plato.stanford.edu/entries/kant-moral/": "Kant's Moral Philosophy",
                "https://plato.stanford.edu/entries/kant-aesthetics/": "Kant's Aesthetics",
                "https://plato.stanford.edu/entries/kant-judgment/": "Kant's Theory of Judgment",
                "https://plato.stanford.edu/entries/kant-science/": "Kant's Philosophy of Science",
                "https://plato.stanford.edu/entries/kant-hume-morality/": "Kant and Hume on Morality",
                "https://plato.stanford.edu/entries/kant-religion/": "Kant's Philosophy of Religion",
                "https://plato.stanford.edu/entries/kant-transcendental-idealism/": "Kant's Transcendental Idealism",
                "https://plato.stanford.edu/entries/reid/": "Thomas Reid",
                "https://plato.stanford.edu/entries/cudworth/": "Ralph Cudworth",
                "https://plato.stanford.edu/entries/shaftesbury/": "Lord Shaftesbury",
                "https://plato.stanford.edu/entries/hutcheson/": "Francis Hutcheson",
                "https://plato.stanford.edu/entries/smith-moral-political/": "Adam Smith's Moral and Political Philosophy",
                "https://plato.stanford.edu/entries/wolff-christian/": "Christian Wolff",
            },
        },
        "continental-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/phenomenology/": "Phenomenology",
                "https://plato.stanford.edu/entries/existentialism/": "Existentialism",
                "https://plato.stanford.edu/entries/hermeneutics/": "Hermeneutics",
                "https://plato.stanford.edu/entries/critical-theory/": "Critical Theory",
                "https://plato.stanford.edu/entries/structuralism/": "Structuralism",
                "https://plato.stanford.edu/entries/postmodernism/": "Postmodernism",
                "https://plato.stanford.edu/entries/deconstruction/": "Deconstruction",
                "https://plato.stanford.edu/entries/frankfurt-school/": "Frankfurt School",
                "https://plato.stanford.edu/entries/habermas/": "Juergen Habermas",
                "https://plato.stanford.edu/entries/adorno/": "Theodor W. Adorno",
                "https://plato.stanford.edu/entries/benjamin/": "Walter Benjamin",
                "https://plato.stanford.edu/entries/marcuse/": "Herbert Marcuse",
                "https://plato.stanford.edu/entries/horkheimer/": "Max Horkheimer",
                "https://plato.stanford.edu/entries/levinas/": "Emmanuel Levinas",
                "https://plato.stanford.edu/entries/merleau-ponty/": "Maurice Merleau-Ponty",
                "https://plato.stanford.edu/entries/ricoeur/": "Paul Ricoeur",
                "https://plato.stanford.edu/entries/gadamer/": "Hans-Georg Gadamer",
                "https://plato.stanford.edu/entries/arendt/": "Hannah Arendt",
                "https://plato.stanford.edu/entries/simone-weil/": "Simone Weil",
                "https://plato.stanford.edu/entries/camus/": "Albert Camus",
                "https://plato.stanford.edu/entries/deleuze/": "Gilles Deleuze",
                "https://plato.stanford.edu/entries/guattari/": "Felix Guattari",
                "https://plato.stanford.edu/entries/baudrillard/": "Jean Baudrillard",
                "https://plato.stanford.edu/entries/lyotard/": "Jean-Francois Lyotard",
                "https://plato.stanford.edu/entries/irigaray/": "Luce Irigaray",
                "https://plato.stanford.edu/entries/kristeva/": "Julia Kristeva",
                "https://plato.stanford.edu/entries/butler-judith/": "Judith Butler",
                "https://plato.stanford.edu/entries/zizek/": "Slavoj Zizek",
                "https://plato.stanford.edu/entries/agamben/": "Giorgio Agamben",
                "https://plato.stanford.edu/entries/badiou/": "Alain Badiou",
            },
        },
        "analytic-philosophy": {
            "pages": {
                "https://plato.stanford.edu/entries/analysis/": "Analysis",
                "https://plato.stanford.edu/entries/logical-positivism/": "Logical Positivism",
                "https://plato.stanford.edu/entries/logical-atomism/": "Logical Atomism",
                "https://plato.stanford.edu/entries/ordinary-language/": "Ordinary Language Philosophy",
                "https://plato.stanford.edu/entries/vienna-circle/": "Vienna Circle",
                "https://plato.stanford.edu/entries/quine/": "Willard Van Orman Quine",
                "https://plato.stanford.edu/entries/kripke/": "Saul Kripke",
                "https://plato.stanford.edu/entries/davidson/": "Donald Davidson",
                "https://plato.stanford.edu/entries/dummett/": "Michael Dummett",
                "https://plato.stanford.edu/entries/putnam/": "Hilary Putnam",
                "https://plato.stanford.edu/entries/lewis-david/": "David Lewis",
                "https://plato.stanford.edu/entries/rawls/": "John Rawls",
                "https://plato.stanford.edu/entries/nozick/": "Robert Nozick",
                "https://plato.stanford.edu/entries/rorty/": "Richard Rorty",
                "https://plato.stanford.edu/entries/sellars/": "Wilfrid Sellars",
                "https://plato.stanford.edu/entries/strawson/": "Peter Frederick Strawson",
                "https://plato.stanford.edu/entries/anscombe/": "G.E.M. Anscombe",
                "https://plato.stanford.edu/entries/foot/": "Philippa Foot",
                "https://plato.stanford.edu/entries/williams-bernard/": "Bernard Williams",
                "https://plato.stanford.edu/entries/parfit/": "Derek Parfit",
                "https://plato.stanford.edu/entries/nagel/": "Thomas Nagel",
                "https://plato.stanford.edu/entries/searle/": "John Searle",
                "https://plato.stanford.edu/entries/dennett/": "Daniel Dennett",
                "https://plato.stanford.edu/entries/chalmers/": "David Chalmers",
                "https://plato.stanford.edu/entries/jackson-frank/": "Frank Jackson",
                "https://plato.stanford.edu/entries/lewis-convention/": "David Lewis' Convention",
                "https://plato.stanford.edu/entries/carnap/": "Rudolf Carnap",
                "https://plato.stanford.edu/entries/ayer/": "A.J. Ayer",
                "https://plato.stanford.edu/entries/ryle/": "Gilbert Ryle",
                "https://plato.stanford.edu/entries/austin-john/": "J.L. Austin",
            },
        },
    }

    def __init__(self, base_dir, source_key=None):
        name = f"sep-{source_key}" if source_key else "sep"
        super().__init__(name, base_dir, interval_seconds=3600)
        self.source_key = source_key

    def _strip_html(self, html_content):
        """Remove HTML tags, scripts, styles and normalize whitespace."""
        text = html_content
        text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
        text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL)
        text = re.sub(r'<nav[^>]*>.*?</nav>', '', text, flags=re.DOTALL)
        text = re.sub(r'<footer[^>]*>.*?</footer>', '', text, flags=re.DOTALL)
        text = re.sub(r'<[^>]+>', ' ', text)
        text = html_mod.unescape(text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    def _extract_title(self, html_content, fallback):
        """Extract page title from HTML."""
        match = re.search(r'<title>([^<]+)</title>', html_content, re.IGNORECASE)
        if match:
            title = match.group(1).strip()
            for suffix in [
                ' (Stanford Encyclopedia of Philosophy)',
                ' - Stanford Encyclopedia of Philosophy',
                ' | Stanford Encyclopedia of Philosophy',
            ]:
                if title.endswith(suffix):
                    title = title[:-len(suffix)].strip()
            return title
        return fallback

    def _scrape_source(self, source_key, config):
        """Scrape all pages for a given source section."""
        count = 0
        pages = config.get("pages", {})

        for url, title in pages.items():
            if not self.running:
                break

            item_id = self.make_id(url)
            content = self.fetch_url(url)

            if content and len(content) > 500:
                text = self._strip_html(content)
                if len(text) > 100:
                    page_title = self._extract_title(content, title)

                    if self.save_item(item_id, {
                        "title": page_title,
                        "content": text[:50000],
                        "url": url,
                        "category": f"sep-{source_key}",
                        "type": "documentation",
                    }):
                        count += 1
                        self.log.info(f"  {source_key}: {title}")

            time.sleep(2.0)

        return count

    def scrape(self):
        """Run scrape across all or a specific source."""
        total = 0

        if self.source_key:
            if self.source_key not in self.SOURCES:
                self.log.error(
                    f"Unknown source key: {self.source_key}. "
                    f"Available: {list(self.SOURCES.keys())}"
                )
                return 0
            sources = {self.source_key: self.SOURCES[self.source_key]}
        else:
            sources = self.SOURCES

        for key, config in sources.items():
            if not self.running:
                break
            self.log.info(f"=== Scraping sep/{key} ===")
            total += self._scrape_source(key, config)

        return total


if __name__ == "__main__":
    import os
    import sys

    base = os.path.expanduser("~")
    source_key = sys.argv[1] if len(sys.argv) > 1 else None
    SEPScraper(base, source_key).run()
