#!/usr/bin/env python3
"""Epicurious scraper.

Covers:
  - Recipes (breakfast, lunch, dinner, desserts, drinks)
  - Cooking techniques and expert advice
  - Ingredient guides
  - Holiday and seasonal content
"""
import re
import time
import html as html_mod
from scraper_base import BaseScraper


class EpicuriousScraper(BaseScraper):
    """Scrape Epicurious recipes, techniques, ingredients, and expert advice."""

    SOURCES = {
        "recipes": {
            "pages": {
                "https://www.epicurious.com/recipes/food/views/buttermilk-pancakes": "Buttermilk Pancakes",
                "https://www.epicurious.com/recipes/food/views/classic-beef-stew": "Classic Beef Stew",
                "https://www.epicurious.com/recipes/food/views/roast-chicken-with-lemon-and-herbs": "Roast Chicken with Lemon and Herbs",
                "https://www.epicurious.com/recipes/food/views/chocolate-mousse": "Chocolate Mousse",
                "https://www.epicurious.com/recipes/food/views/caesar-salad": "Caesar Salad",
                "https://www.epicurious.com/recipes/food/views/french-onion-soup": "French Onion Soup",
                "https://www.epicurious.com/recipes/food/views/spaghetti-carbonara": "Spaghetti Carbonara",
                "https://www.epicurious.com/recipes/food/views/chicken-tikka-masala": "Chicken Tikka Masala",
                "https://www.epicurious.com/recipes/food/views/beef-bourguignon": "Beef Bourguignon",
                "https://www.epicurious.com/recipes/food/views/classic-margherita-pizza": "Classic Margherita Pizza",
                "https://www.epicurious.com/recipes/food/views/eggs-benedict": "Eggs Benedict",
                "https://www.epicurious.com/recipes/food/views/banana-bread": "Banana Bread",
                "https://www.epicurious.com/recipes/food/views/blueberry-muffins": "Blueberry Muffins",
                "https://www.epicurious.com/recipes/food/views/quiche-lorraine": "Quiche Lorraine",
                "https://www.epicurious.com/recipes/food/views/avocado-toast": "Avocado Toast",
                "https://www.epicurious.com/recipes/food/views/granola": "Granola",
                "https://www.epicurious.com/recipes/food/views/chicken-noodle-soup": "Chicken Noodle Soup",
                "https://www.epicurious.com/recipes/food/views/tomato-bisque": "Tomato Bisque",
                "https://www.epicurious.com/recipes/food/views/grilled-cheese-sandwich": "Grilled Cheese Sandwich",
                "https://www.epicurious.com/recipes/food/views/club-sandwich": "Club Sandwich",
                "https://www.epicurious.com/recipes/food/views/cobb-salad": "Cobb Salad",
                "https://www.epicurious.com/recipes/food/views/greek-salad": "Greek Salad",
                "https://www.epicurious.com/recipes/food/views/pasta-primavera": "Pasta Primavera",
                "https://www.epicurious.com/recipes/food/views/fettuccine-alfredo": "Fettuccine Alfredo",
                "https://www.epicurious.com/recipes/food/views/pad-thai": "Pad Thai",
                "https://www.epicurious.com/recipes/food/views/chicken-curry": "Chicken Curry",
                "https://www.epicurious.com/recipes/food/views/lamb-chops": "Lamb Chops",
                "https://www.epicurious.com/recipes/food/views/pan-seared-salmon": "Pan-Seared Salmon",
                "https://www.epicurious.com/recipes/food/views/shrimp-scampi": "Shrimp Scampi",
                "https://www.epicurious.com/recipes/food/views/beef-tacos": "Beef Tacos",
                "https://www.epicurious.com/recipes/food/views/fish-tacos": "Fish Tacos",
                "https://www.epicurious.com/recipes/food/views/pulled-pork-sandwich": "Pulled Pork Sandwich",
                "https://www.epicurious.com/recipes/food/views/meatloaf": "Meatloaf",
                "https://www.epicurious.com/recipes/food/views/pot-roast": "Pot Roast",
                "https://www.epicurious.com/recipes/food/views/braised-short-ribs": "Braised Short Ribs",
                "https://www.epicurious.com/recipes/food/views/roasted-vegetables": "Roasted Vegetables",
                "https://www.epicurious.com/recipes/food/views/mashed-potatoes": "Mashed Potatoes",
                "https://www.epicurious.com/recipes/food/views/mac-and-cheese": "Mac and Cheese",
                "https://www.epicurious.com/recipes/food/views/cornbread": "Cornbread",
                "https://www.epicurious.com/recipes/food/views/biscuits": "Biscuits",
                "https://www.epicurious.com/recipes/food/views/dinner-rolls": "Dinner Rolls",
                "https://www.epicurious.com/recipes/food/views/garlic-bread": "Garlic Bread",
                "https://www.epicurious.com/recipes/food/views/bruschetta": "Bruschetta",
                "https://www.epicurious.com/recipes/food/views/deviled-eggs": "Deviled Eggs",
                "https://www.epicurious.com/recipes/food/views/shrimp-cocktail": "Shrimp Cocktail",
                "https://www.epicurious.com/recipes/food/views/spinach-artichoke-dip": "Spinach Artichoke Dip",
                "https://www.epicurious.com/recipes/food/views/guacamole": "Guacamole",
                "https://www.epicurious.com/recipes/food/views/hummus": "Hummus",
                "https://www.epicurious.com/recipes/food/views/chocolate-cake": "Chocolate Cake",
                "https://www.epicurious.com/recipes/food/views/carrot-cake": "Carrot Cake",
                "https://www.epicurious.com/recipes/food/views/cheesecake": "Cheesecake",
                "https://www.epicurious.com/recipes/food/views/tiramisu": "Tiramisu",
                "https://www.epicurious.com/recipes/food/views/creme-brulee": "Creme Brulee",
                "https://www.epicurious.com/recipes/food/views/panna-cotta": "Panna Cotta",
                "https://www.epicurious.com/recipes/food/views/apple-pie": "Apple Pie",
                "https://www.epicurious.com/recipes/food/views/pecan-pie": "Pecan Pie",
                "https://www.epicurious.com/recipes/food/views/key-lime-pie": "Key Lime Pie",
                "https://www.epicurious.com/recipes/food/views/brownies": "Brownies",
                "https://www.epicurious.com/recipes/food/views/chocolate-chip-cookies": "Chocolate Chip Cookies",
                "https://www.epicurious.com/recipes/food/views/sugar-cookies": "Sugar Cookies",
                "https://www.epicurious.com/recipes/food/views/lemon-bars": "Lemon Bars",
                "https://www.epicurious.com/recipes/food/views/berry-crumble": "Berry Crumble",
                "https://www.epicurious.com/recipes/food/views/peach-cobbler": "Peach Cobbler",
                "https://www.epicurious.com/recipes/food/views/english-trifle": "English Trifle",
                "https://www.epicurious.com/recipes/food/views/classic-margarita": "Classic Margarita",
                "https://www.epicurious.com/recipes/food/views/mojito": "Mojito",
                "https://www.epicurious.com/recipes/food/views/old-fashioned-cocktail": "Old Fashioned Cocktail",
                "https://www.epicurious.com/recipes/food/views/manhattan-cocktail": "Manhattan Cocktail",
                "https://www.epicurious.com/recipes/food/views/negroni": "Negroni",
                "https://www.epicurious.com/recipes/food/views/cosmopolitan": "Cosmopolitan",
                "https://www.epicurious.com/recipes/food/views/red-sangria": "Red Sangria",
                "https://www.epicurious.com/recipes/food/views/fresh-lemonade": "Fresh Lemonade",
                "https://www.epicurious.com/recipes/food/views/sweet-iced-tea": "Sweet Iced Tea",
                "https://www.epicurious.com/recipes/food/views/lasagna": "Lasagna",
                "https://www.epicurious.com/recipes/food/views/risotto": "Risotto",
                "https://www.epicurious.com/recipes/food/views/chicken-parmesan": "Chicken Parmesan",
                "https://www.epicurious.com/recipes/food/views/beef-stroganoff": "Beef Stroganoff",
                "https://www.epicurious.com/recipes/food/views/shepherds-pie": "Shepherds Pie",
                "https://www.epicurious.com/recipes/food/views/fish-and-chips": "Fish and Chips",
                "https://www.epicurious.com/recipes/food/views/enchiladas": "Enchiladas",
                "https://www.epicurious.com/recipes/food/views/bbq-ribs": "BBQ Ribs",
                "https://www.epicurious.com/recipes/food/views/grilled-salmon": "Grilled Salmon",
                "https://www.epicurious.com/recipes/food/views/chicken-pot-pie": "Chicken Pot Pie",
                "https://www.epicurious.com/recipes/food/views/beef-wellington": "Beef Wellington",
                "https://www.epicurious.com/recipes/food/views/pork-tenderloin": "Pork Tenderloin",
                "https://www.epicurious.com/recipes/food/views/honey-glazed-ham": "Honey Glazed Ham",
                "https://www.epicurious.com/recipes/food/views/teriyaki-chicken": "Teriyaki Chicken",
                "https://www.epicurious.com/recipes/food/views/kung-pao-chicken": "Kung Pao Chicken",
                "https://www.epicurious.com/recipes/food/views/fried-rice": "Fried Rice",
                "https://www.epicurious.com/recipes/food/views/lo-mein": "Lo Mein",
                "https://www.epicurious.com/recipes/food/views/ramen": "Ramen",
                "https://www.epicurious.com/recipes/food/views/pho": "Pho",
                "https://www.epicurious.com/recipes/food/views/green-curry": "Green Curry",
                "https://www.epicurious.com/recipes/food/views/biryani": "Biryani",
                "https://www.epicurious.com/recipes/food/views/falafel": "Falafel",
                "https://www.epicurious.com/recipes/food/views/paella": "Paella",
                "https://www.epicurious.com/recipes/food/views/jambalaya": "Jambalaya",
                "https://www.epicurious.com/recipes/food/views/gumbo": "Gumbo",
                "https://www.epicurious.com/recipes/food/views/crab-cakes": "Crab Cakes",
                "https://www.epicurious.com/recipes/food/views/lobster-bisque": "Lobster Bisque",
                "https://www.epicurious.com/recipes/food/views/ceviche": "Ceviche",
                "https://www.epicurious.com/recipes/food/views/poke-bowl": "Poke Bowl",
                "https://www.epicurious.com/recipes/food/views/sushi-rolls": "Sushi Rolls",
                "https://www.epicurious.com/recipes/food/views/tempura": "Tempura",
                "https://www.epicurious.com/recipes/food/views/spring-rolls": "Spring Rolls",
                "https://www.epicurious.com/recipes/food/views/dumplings": "Dumplings",
                "https://www.epicurious.com/recipes/food/views/samosas": "Samosas",
                "https://www.epicurious.com/recipes/food/views/empanadas": "Empanadas",
                "https://www.epicurious.com/recipes/food/views/gnocchi": "Gnocchi",
                "https://www.epicurious.com/recipes/food/views/ravioli": "Ravioli",
                "https://www.epicurious.com/recipes/food/views/pesto-pasta": "Pesto Pasta",
                "https://www.epicurious.com/recipes/food/views/marinara-sauce": "Marinara Sauce",
                "https://www.epicurious.com/recipes/food/views/bechamel-sauce": "Bechamel Sauce",
                "https://www.epicurious.com/recipes/food/views/hollandaise": "Hollandaise",
                "https://www.epicurious.com/recipes/food/views/chimichurri": "Chimichurri",
                "https://www.epicurious.com/recipes/food/views/tzatziki": "Tzatziki",
                "https://www.epicurious.com/recipes/food/views/focaccia": "Focaccia",
                "https://www.epicurious.com/recipes/food/views/sourdough-bread": "Sourdough Bread",
                "https://www.epicurious.com/recipes/food/views/challah": "Challah",
                "https://www.epicurious.com/recipes/food/views/brioche": "Brioche",
                "https://www.epicurious.com/recipes/food/views/croissants": "Croissants",
                "https://www.epicurious.com/recipes/food/views/pretzels": "Pretzels",
                "https://www.epicurious.com/recipes/food/views/cinnamon-rolls": "Cinnamon Rolls",
                "https://www.epicurious.com/recipes/food/views/scones": "Scones",
                "https://www.epicurious.com/recipes/food/views/waffles": "Waffles",
                "https://www.epicurious.com/recipes/food/views/french-toast": "French Toast",
                "https://www.epicurious.com/recipes/food/views/shakshuka": "Shakshuka",
                "https://www.epicurious.com/recipes/food/views/frittata": "Frittata",
                "https://www.epicurious.com/recipes/food/views/croque-monsieur": "Croque Monsieur",
                "https://www.epicurious.com/recipes/food/views/nicoise-salad": "Nicoise Salad",
                "https://www.epicurious.com/recipes/food/views/caprese-salad": "Caprese Salad",
                "https://www.epicurious.com/recipes/food/views/waldorf-salad": "Waldorf Salad",
                "https://www.epicurious.com/recipes/food/views/minestrone-soup": "Minestrone Soup",
                "https://www.epicurious.com/recipes/food/views/clam-chowder": "Clam Chowder",
                "https://www.epicurious.com/recipes/food/views/gazpacho": "Gazpacho",
                "https://www.epicurious.com/recipes/food/views/vichyssoise": "Vichyssoise",
                "https://www.epicurious.com/recipes/food/views/potato-leek-soup": "Potato Leek Soup",
                "https://www.epicurious.com/recipes/food/views/butternut-squash-soup": "Butternut Squash Soup",
                "https://www.epicurious.com/recipes/food/views/coq-au-vin": "Coq au Vin",
                "https://www.epicurious.com/recipes/food/views/duck-confit": "Duck Confit",
                "https://www.epicurious.com/recipes/food/views/osso-buco": "Osso Buco",
                "https://www.epicurious.com/recipes/food/views/chicken-marsala": "Chicken Marsala",
                "https://www.epicurious.com/recipes/food/views/piccata": "Piccata",
                "https://www.epicurious.com/recipes/food/views/saltimbocca": "Saltimbocca",
                "https://www.epicurious.com/recipes/food/views/chicken-cacciatore": "Chicken Cacciatore",
                "https://www.epicurious.com/recipes/food/views/eggplant-parmesan": "Eggplant Parmesan",
                "https://www.epicurious.com/recipes/food/views/ratatouille": "Ratatouille",
                "https://www.epicurious.com/recipes/food/views/moussaka": "Moussaka",
                "https://www.epicurious.com/recipes/food/views/stuffed-peppers": "Stuffed Peppers",
                "https://www.epicurious.com/recipes/food/views/cabbage-rolls": "Cabbage Rolls",
                "https://www.epicurious.com/recipes/food/views/beef-chili": "Beef Chili",
                "https://www.epicurious.com/recipes/food/views/white-chicken-chili": "White Chicken Chili",
                "https://www.epicurious.com/recipes/food/views/black-bean-soup": "Black Bean Soup",
                "https://www.epicurious.com/recipes/food/views/split-pea-soup": "Split Pea Soup",
                "https://www.epicurious.com/recipes/food/views/lentil-soup": "Lentil Soup",
                "https://www.epicurious.com/recipes/food/views/tortilla-soup": "Tortilla Soup",
                "https://www.epicurious.com/recipes/food/views/corn-chowder": "Corn Chowder",
                "https://www.epicurious.com/recipes/food/views/mushroom-risotto": "Mushroom Risotto",
                "https://www.epicurious.com/recipes/food/views/seafood-risotto": "Seafood Risotto",
                "https://www.epicurious.com/recipes/food/views/baked-ziti": "Baked Ziti",
                "https://www.epicurious.com/recipes/food/views/stuffed-shells": "Stuffed Shells",
                "https://www.epicurious.com/recipes/food/views/manicotti": "Manicotti",
                "https://www.epicurious.com/recipes/food/views/bolognese-sauce": "Bolognese Sauce",
                "https://www.epicurious.com/recipes/food/views/puttanesca": "Puttanesca",
                "https://www.epicurious.com/recipes/food/views/aglio-e-olio": "Aglio e Olio",
                "https://www.epicurious.com/recipes/food/views/cacio-e-pepe": "Cacio e Pepe",
                "https://www.epicurious.com/recipes/food/views/chicken-shawarma": "Chicken Shawarma",
                "https://www.epicurious.com/recipes/food/views/lamb-gyros": "Lamb Gyros",
                "https://www.epicurious.com/recipes/food/views/beef-kebabs": "Beef Kebabs",
                "https://www.epicurious.com/recipes/food/views/tandoori-chicken": "Tandoori Chicken",
                "https://www.epicurious.com/recipes/food/views/butter-chicken": "Butter Chicken",
                "https://www.epicurious.com/recipes/food/views/palak-paneer": "Palak Paneer",
                "https://www.epicurious.com/recipes/food/views/chana-masala": "Chana Masala",
                "https://www.epicurious.com/recipes/food/views/dal-tadka": "Dal Tadka",
                "https://www.epicurious.com/recipes/food/views/thai-basil-chicken": "Thai Basil Chicken",
                "https://www.epicurious.com/recipes/food/views/massaman-curry": "Massaman Curry",
                "https://www.epicurious.com/recipes/food/views/tom-yum-soup": "Tom Yum Soup",
                "https://www.epicurious.com/recipes/food/views/larb": "Larb",
                "https://www.epicurious.com/recipes/food/views/bibimbap": "Bibimbap",
                "https://www.epicurious.com/recipes/food/views/bulgogi": "Bulgogi",
                "https://www.epicurious.com/recipes/food/views/japchae": "Japchae",
                "https://www.epicurious.com/recipes/food/views/kimchi-jjigae": "Kimchi Jjigae",
                "https://www.epicurious.com/recipes/food/views/mapo-tofu": "Mapo Tofu",
                "https://www.epicurious.com/recipes/food/views/general-tsos-chicken": "General Tsos Chicken",
                "https://www.epicurious.com/recipes/food/views/orange-chicken": "Orange Chicken",
                "https://www.epicurious.com/recipes/food/views/dan-dan-noodles": "Dan Dan Noodles",
                "https://www.epicurious.com/recipes/food/views/char-siu-pork": "Char Siu Pork",
                "https://www.epicurious.com/recipes/food/views/banh-mi": "Banh Mi",
                "https://www.epicurious.com/recipes/food/views/carnitas": "Carnitas",
                "https://www.epicurious.com/recipes/food/views/al-pastor": "Al Pastor",
                "https://www.epicurious.com/recipes/food/views/chilaquiles": "Chilaquiles",
                "https://www.epicurious.com/recipes/food/views/tamales": "Tamales",
                "https://www.epicurious.com/recipes/food/views/pozole": "Pozole",
                "https://www.epicurious.com/recipes/food/views/mole-poblano": "Mole Poblano",
                "https://www.epicurious.com/recipes/food/views/elote": "Elote",
                "https://www.epicurious.com/recipes/food/views/arroz-con-pollo": "Arroz con Pollo",
                "https://www.epicurious.com/recipes/food/views/black-beans-and-rice": "Black Beans and Rice",
                "https://www.epicurious.com/recipes/food/views/coconut-shrimp": "Coconut Shrimp",
                "https://www.epicurious.com/recipes/food/views/stuffed-mushrooms": "Stuffed Mushrooms",
                "https://www.epicurious.com/recipes/food/views/potato-gratin": "Potato Gratin",
                "https://www.epicurious.com/recipes/food/views/green-bean-casserole": "Green Bean Casserole",
                "https://www.epicurious.com/recipes/food/views/sweet-potato-casserole": "Sweet Potato Casserole",
                "https://www.epicurious.com/recipes/food/views/coleslaw": "Coleslaw",
                "https://www.epicurious.com/recipes/food/views/potato-salad": "Potato Salad",
                "https://www.epicurious.com/recipes/food/views/tabbouleh": "Tabbouleh",
                "https://www.epicurious.com/recipes/food/views/fattoush": "Fattoush",
                "https://www.epicurious.com/recipes/food/views/baba-ganoush": "Baba Ganoush",
                "https://www.epicurious.com/recipes/food/views/pumpkin-pie": "Pumpkin Pie",
                "https://www.epicurious.com/recipes/food/views/banana-pudding": "Banana Pudding",
                "https://www.epicurious.com/recipes/food/views/bread-pudding": "Bread Pudding",
                "https://www.epicurious.com/recipes/food/views/rice-pudding": "Rice Pudding",
                "https://www.epicurious.com/recipes/food/views/pavlova": "Pavlova",
                "https://www.epicurious.com/recipes/food/views/baklava": "Baklava",
                "https://www.epicurious.com/recipes/food/views/churros": "Churros",
                "https://www.epicurious.com/recipes/food/views/crepes": "Crepes",
                "https://www.epicurious.com/recipes/food/views/macarons": "Macarons",
                "https://www.epicurious.com/recipes/food/views/pound-cake": "Pound Cake",
                "https://www.epicurious.com/recipes/food/views/red-velvet-cake": "Red Velvet Cake",
                "https://www.epicurious.com/recipes/food/views/german-chocolate-cake": "German Chocolate Cake",
                "https://www.epicurious.com/recipes/food/views/angel-food-cake": "Angel Food Cake",
                "https://www.epicurious.com/recipes/food/views/tres-leches-cake": "Tres Leches Cake",
            },
        },
        "techniques": {
            "pages": {
                "https://www.epicurious.com/expert-advice/how-to-grill-steak-perfectly-article": "How to Grill Steak Perfectly",
                "https://www.epicurious.com/expert-advice/how-to-braise-meat-article": "How to Braise Meat",
                "https://www.epicurious.com/expert-advice/complete-guide-to-roasting-article": "Complete Guide to Roasting",
                "https://www.epicurious.com/expert-advice/sous-vide-basics-article": "Sous Vide Basics",
                "https://www.epicurious.com/expert-advice/how-to-make-sourdough-starter-article": "How to Make Sourdough Starter",
                "https://www.epicurious.com/expert-advice/guide-to-fermentation-article": "Guide to Fermentation",
                "https://www.epicurious.com/expert-advice/how-to-saute-article": "How to Saute",
                "https://www.epicurious.com/expert-advice/how-to-poach-article": "How to Poach",
                "https://www.epicurious.com/expert-advice/how-to-steam-article": "How to Steam",
                "https://www.epicurious.com/expert-advice/how-to-blanch-article": "How to Blanch",
                "https://www.epicurious.com/expert-advice/how-to-deep-fry-article": "How to Deep Fry",
                "https://www.epicurious.com/expert-advice/how-to-pan-fry-article": "How to Pan Fry",
                "https://www.epicurious.com/expert-advice/how-to-stir-fry-article": "How to Stir Fry",
                "https://www.epicurious.com/expert-advice/baking-basics-article": "Baking Basics",
                "https://www.epicurious.com/expert-advice/bread-baking-guide-article": "Bread Baking Guide",
                "https://www.epicurious.com/expert-advice/pastry-making-guide-article": "Pastry Making Guide",
                "https://www.epicurious.com/expert-advice/cake-decorating-basics-article": "Cake Decorating Basics",
                "https://www.epicurious.com/expert-advice/how-to-temper-chocolate-article": "How to Temper Chocolate",
                "https://www.epicurious.com/expert-advice/how-to-make-caramel-article": "How to Make Caramel",
                "https://www.epicurious.com/expert-advice/candy-making-guide-article": "Candy Making Guide",
                "https://www.epicurious.com/expert-advice/how-to-make-stock-article": "How to Make Stock",
                "https://www.epicurious.com/expert-advice/how-to-reduce-sauces-article": "How to Reduce Sauces",
                "https://www.epicurious.com/expert-advice/how-to-deglaze-article": "How to Deglaze",
                "https://www.epicurious.com/expert-advice/how-to-emulsify-article": "How to Emulsify",
                "https://www.epicurious.com/expert-advice/how-to-whip-cream-article": "How to Whip Cream",
                "https://www.epicurious.com/expert-advice/how-to-beat-egg-whites-article": "How to Beat Egg Whites",
                "https://www.epicurious.com/expert-advice/folding-techniques-article": "Folding Techniques",
                "https://www.epicurious.com/expert-advice/how-to-knead-dough-article": "How to Knead Dough",
                "https://www.epicurious.com/expert-advice/how-to-proof-yeast-article": "How to Proof Yeast",
                "https://www.epicurious.com/expert-advice/how-to-laminate-dough-article": "How to Laminate Dough",
                "https://www.epicurious.com/expert-advice/pie-crust-making-guide-article": "Pie Crust Making Guide",
                "https://www.epicurious.com/expert-advice/making-pasta-from-scratch-article": "Making Pasta from Scratch",
                "https://www.epicurious.com/expert-advice/how-to-smoke-meat-article": "How to Smoke Meat",
                "https://www.epicurious.com/expert-advice/how-to-cure-meat-article": "How to Cure Meat",
                "https://www.epicurious.com/expert-advice/how-to-pickle-vegetables-article": "How to Pickle Vegetables",
                "https://www.epicurious.com/expert-advice/how-to-make-jam-article": "How to Make Jam",
                "https://www.epicurious.com/expert-advice/canning-basics-article": "Canning Basics",
                "https://www.epicurious.com/expert-advice/how-to-dehydrate-food-article": "How to Dehydrate Food",
                "https://www.epicurious.com/expert-advice/knife-skills-guide-article": "Knife Skills Guide",
                "https://www.epicurious.com/expert-advice/how-to-julienne-cut-article": "How to Julienne Cut",
                "https://www.epicurious.com/expert-advice/how-to-chiffonade-cut-article": "How to Chiffonade Cut",
                "https://www.epicurious.com/expert-advice/how-to-brunoise-cut-article": "How to Brunoise Cut",
                "https://www.epicurious.com/expert-advice/mise-en-place-guide-article": "Mise en Place Guide",
                "https://www.epicurious.com/expert-advice/food-plating-tips-article": "Food Plating Tips",
                "https://www.epicurious.com/expert-advice/garnishing-techniques-article": "Garnishing Techniques",
                "https://www.epicurious.com/expert-advice/how-to-season-cast-iron-article": "How to Season Cast Iron",
                "https://www.epicurious.com/expert-advice/wok-cooking-guide-article": "Wok Cooking Guide",
                "https://www.epicurious.com/expert-advice/clay-pot-cooking-guide-article": "Clay Pot Cooking Guide",
                "https://www.epicurious.com/expert-advice/dutch-oven-cooking-guide-article": "Dutch Oven Cooking Guide",
                "https://www.epicurious.com/expert-advice/pressure-cooking-guide-article": "Pressure Cooking Guide",
                "https://www.epicurious.com/expert-advice/slow-cooking-guide-article": "Slow Cooking Guide",
                "https://www.epicurious.com/expert-advice/grilling-vegetables-guide-article": "Grilling Vegetables Guide",
                "https://www.epicurious.com/expert-advice/grilling-seafood-guide-article": "Grilling Seafood Guide",
                "https://www.epicurious.com/expert-advice/how-to-make-sushi-article": "How to Make Sushi",
                "https://www.epicurious.com/expert-advice/how-to-make-ramen-noodles-article": "How to Make Ramen Noodles",
                "https://www.epicurious.com/expert-advice/how-to-make-fresh-pasta-article": "How to Make Fresh Pasta",
                "https://www.epicurious.com/expert-advice/how-to-make-gnocchi-article": "How to Make Gnocchi",
                "https://www.epicurious.com/expert-advice/how-to-make-ravioli-article": "How to Make Ravioli",
                "https://www.epicurious.com/expert-advice/how-to-make-dumplings-article": "How to Make Dumplings",
                "https://www.epicurious.com/expert-advice/how-to-make-spring-rolls-article": "How to Make Spring Rolls",
                "https://www.epicurious.com/expert-advice/how-to-make-crepes-article": "How to Make Crepes",
                "https://www.epicurious.com/expert-advice/how-to-make-tortillas-article": "How to Make Tortillas",
                "https://www.epicurious.com/expert-advice/how-to-make-pizza-dough-article": "How to Make Pizza Dough",
                "https://www.epicurious.com/expert-advice/how-to-make-flatbread-article": "How to Make Flatbread",
                "https://www.epicurious.com/expert-advice/how-to-make-naan-article": "How to Make Naan",
                "https://www.epicurious.com/expert-advice/fermented-hot-sauce-guide-article": "Fermented Hot Sauce Guide",
                "https://www.epicurious.com/expert-advice/how-to-make-vinegar-article": "How to Make Vinegar",
                "https://www.epicurious.com/expert-advice/how-to-make-cheese-article": "How to Make Cheese",
                "https://www.epicurious.com/expert-advice/how-to-make-butter-article": "How to Make Butter",
                "https://www.epicurious.com/expert-advice/how-to-make-yogurt-article": "How to Make Yogurt",
                "https://www.epicurious.com/expert-advice/how-to-make-ice-cream-article": "How to Make Ice Cream",
                "https://www.epicurious.com/expert-advice/how-to-make-sorbet-article": "How to Make Sorbet",
                "https://www.epicurious.com/expert-advice/how-to-temper-eggs-article": "How to Temper Eggs",
                "https://www.epicurious.com/expert-advice/how-to-clarify-butter-article": "How to Clarify Butter",
                "https://www.epicurious.com/expert-advice/how-to-render-fat-article": "How to Render Fat",
                "https://www.epicurious.com/expert-advice/how-to-make-roux-article": "How to Make Roux",
                "https://www.epicurious.com/expert-advice/how-to-make-bechamel-article": "How to Make Bechamel",
                "https://www.epicurious.com/expert-advice/how-to-make-hollandaise-article": "How to Make Hollandaise",
                "https://www.epicurious.com/expert-advice/how-to-make-mayonnaise-article": "How to Make Mayonnaise",
                "https://www.epicurious.com/expert-advice/how-to-make-aioli-article": "How to Make Aioli",
            },
        },
        "ingredients": {
            "pages": {
                "https://www.epicurious.com/ingredients/guide-to-seasonal-produce-article": "Guide to Seasonal Produce",
                "https://www.epicurious.com/ingredients/best-olive-oils-article": "Best Olive Oils",
                "https://www.epicurious.com/ingredients/how-to-store-herbs-article": "How to Store Herbs",
                "https://www.epicurious.com/ingredients/ingredient-substitution-guide-article": "Ingredient Substitution Guide",
                "https://www.epicurious.com/ingredients/guide-to-cooking-oils-article": "Guide to Cooking Oils",
                "https://www.epicurious.com/ingredients/understanding-salt-types-article": "Understanding Salt Types",
                "https://www.epicurious.com/ingredients/guide-to-vinegars-article": "Guide to Vinegars",
                "https://www.epicurious.com/ingredients/types-of-flour-article": "Types of Flour",
                "https://www.epicurious.com/ingredients/guide-to-sugar-types-article": "Guide to Sugar Types",
                "https://www.epicurious.com/ingredients/guide-to-rice-varieties-article": "Guide to Rice Varieties",
                "https://www.epicurious.com/ingredients/guide-to-pasta-shapes-article": "Guide to Pasta Shapes",
                "https://www.epicurious.com/ingredients/guide-to-chili-peppers-article": "Guide to Chili Peppers",
                "https://www.epicurious.com/ingredients/guide-to-mushrooms-article": "Guide to Mushrooms",
                "https://www.epicurious.com/ingredients/guide-to-cheese-types-article": "Guide to Cheese Types",
                "https://www.epicurious.com/ingredients/guide-to-fresh-herbs-article": "Guide to Fresh Herbs",
                "https://www.epicurious.com/ingredients/guide-to-dried-spices-article": "Guide to Dried Spices",
                "https://www.epicurious.com/ingredients/guide-to-chocolate-types-article": "Guide to Chocolate Types",
                "https://www.epicurious.com/ingredients/guide-to-cuts-of-beef-article": "Guide to Cuts of Beef",
                "https://www.epicurious.com/ingredients/guide-to-cuts-of-pork-article": "Guide to Cuts of Pork",
                "https://www.epicurious.com/ingredients/guide-to-poultry-cuts-article": "Guide to Poultry Cuts",
                "https://www.epicurious.com/ingredients/guide-to-seafood-article": "Guide to Seafood",
                "https://www.epicurious.com/ingredients/guide-to-shellfish-article": "Guide to Shellfish",
                "https://www.epicurious.com/ingredients/seasonal-spring-produce-article": "Seasonal Spring Produce",
                "https://www.epicurious.com/ingredients/seasonal-summer-produce-article": "Seasonal Summer Produce",
                "https://www.epicurious.com/ingredients/seasonal-fall-produce-article": "Seasonal Fall Produce",
                "https://www.epicurious.com/ingredients/seasonal-winter-produce-article": "Seasonal Winter Produce",
                "https://www.epicurious.com/ingredients/guide-to-citrus-fruits-article": "Guide to Citrus Fruits",
                "https://www.epicurious.com/ingredients/guide-to-stone-fruits-article": "Guide to Stone Fruits",
                "https://www.epicurious.com/ingredients/guide-to-berries-article": "Guide to Berries",
                "https://www.epicurious.com/ingredients/guide-to-tropical-fruits-article": "Guide to Tropical Fruits",
                "https://www.epicurious.com/ingredients/guide-to-root-vegetables-article": "Guide to Root Vegetables",
                "https://www.epicurious.com/ingredients/guide-to-leafy-greens-article": "Guide to Leafy Greens",
                "https://www.epicurious.com/ingredients/guide-to-cruciferous-vegetables-article": "Guide to Cruciferous Vegetables",
                "https://www.epicurious.com/ingredients/guide-to-alliums-article": "Guide to Alliums",
                "https://www.epicurious.com/ingredients/guide-to-legumes-article": "Guide to Legumes",
                "https://www.epicurious.com/ingredients/guide-to-dried-beans-article": "Guide to Dried Beans",
                "https://www.epicurious.com/ingredients/guide-to-lentils-article": "Guide to Lentils",
                "https://www.epicurious.com/ingredients/guide-to-nuts-article": "Guide to Nuts",
                "https://www.epicurious.com/ingredients/guide-to-seeds-article": "Guide to Seeds",
                "https://www.epicurious.com/ingredients/guide-to-grains-article": "Guide to Grains",
                "https://www.epicurious.com/ingredients/guide-to-ancient-grains-article": "Guide to Ancient Grains",
                "https://www.epicurious.com/ingredients/guide-to-quinoa-article": "Guide to Quinoa",
                "https://www.epicurious.com/ingredients/guide-to-tofu-and-tempeh-article": "Guide to Tofu and Tempeh",
                "https://www.epicurious.com/ingredients/guide-to-miso-article": "Guide to Miso",
                "https://www.epicurious.com/ingredients/guide-to-soy-sauce-article": "Guide to Soy Sauce",
                "https://www.epicurious.com/ingredients/guide-to-fish-sauce-article": "Guide to Fish Sauce",
                "https://www.epicurious.com/ingredients/guide-to-coconut-milk-article": "Guide to Coconut Milk",
                "https://www.epicurious.com/ingredients/guide-to-stocks-and-broths-article": "Guide to Stocks and Broths",
                "https://www.epicurious.com/ingredients/guide-to-canned-tomatoes-article": "Guide to Canned Tomatoes",
                "https://www.epicurious.com/ingredients/guide-to-dried-pasta-article": "Guide to Dried Pasta",
                "https://www.epicurious.com/ingredients/guide-to-fresh-pasta-article": "Guide to Fresh Pasta",
                "https://www.epicurious.com/ingredients/guide-to-bread-flour-article": "Guide to Bread Flour",
                "https://www.epicurious.com/ingredients/guide-to-butter-types-article": "Guide to Butter Types",
                "https://www.epicurious.com/ingredients/guide-to-cream-types-article": "Guide to Cream Types",
                "https://www.epicurious.com/ingredients/guide-to-yogurt-article": "Guide to Yogurt",
                "https://www.epicurious.com/ingredients/guide-to-honey-article": "Guide to Honey",
                "https://www.epicurious.com/ingredients/guide-to-maple-syrup-article": "Guide to Maple Syrup",
                "https://www.epicurious.com/ingredients/guide-to-vanilla-article": "Guide to Vanilla",
                "https://www.epicurious.com/ingredients/guide-to-cinnamon-article": "Guide to Cinnamon",
                "https://www.epicurious.com/ingredients/guide-to-peppers-article": "Guide to Peppers",
                "https://www.epicurious.com/ingredients/guide-to-garlic-article": "Guide to Garlic",
                "https://www.epicurious.com/ingredients/guide-to-ginger-article": "Guide to Ginger",
                "https://www.epicurious.com/ingredients/guide-to-turmeric-article": "Guide to Turmeric",
                "https://www.epicurious.com/ingredients/guide-to-saffron-article": "Guide to Saffron",
                "https://www.epicurious.com/ingredients/guide-to-cardamom-article": "Guide to Cardamom",
                "https://www.epicurious.com/ingredients/guide-to-cumin-article": "Guide to Cumin",
                "https://www.epicurious.com/ingredients/guide-to-coriander-article": "Guide to Coriander",
                "https://www.epicurious.com/ingredients/guide-to-paprika-article": "Guide to Paprika",
                "https://www.epicurious.com/ingredients/guide-to-chili-flakes-article": "Guide to Chili Flakes",
                "https://www.epicurious.com/ingredients/how-to-buy-fresh-fish-article": "How to Buy Fresh Fish",
            },
        },
        "expert-advice": {
            "pages": {
                "https://www.epicurious.com/expert-advice/kitchen-organization-tips-article": "Kitchen Organization Tips",
                "https://www.epicurious.com/expert-advice/dinner-party-planning-guide-article": "Dinner Party Planning Guide",
                "https://www.epicurious.com/expert-advice/weekly-meal-prep-tips-article": "Weekly Meal Prep Tips",
                "https://www.epicurious.com/expert-advice/batch-cooking-for-beginners-article": "Batch Cooking for Beginners",
                "https://www.epicurious.com/expert-advice/freezer-meal-strategies-article": "Freezer Meal Strategies",
                "https://www.epicurious.com/expert-advice/pantry-staples-guide-article": "Pantry Staples Guide",
                "https://www.epicurious.com/expert-advice/essential-kitchen-tools-article": "Essential Kitchen Tools",
                "https://www.epicurious.com/expert-advice/budget-cooking-tips-article": "Budget Cooking Tips",
                "https://www.epicurious.com/expert-advice/cooking-for-one-article": "Cooking for One",
                "https://www.epicurious.com/expert-advice/cooking-for-a-crowd-article": "Cooking for a Crowd",
                "https://www.epicurious.com/expert-advice/wine-pairing-basics-article": "Wine Pairing Basics",
                "https://www.epicurious.com/expert-advice/beer-and-food-pairing-article": "Beer and Food Pairing",
                "https://www.epicurious.com/expert-advice/cocktail-party-essentials-article": "Cocktail Party Essentials",
                "https://www.epicurious.com/expert-advice/brunch-hosting-guide-article": "Brunch Hosting Guide",
                "https://www.epicurious.com/expert-advice/outdoor-entertaining-tips-article": "Outdoor Entertaining Tips",
                "https://www.epicurious.com/expert-advice/potluck-dish-ideas-article": "Potluck Dish Ideas",
                "https://www.epicurious.com/expert-advice/food-gift-ideas-article": "Food Gift Ideas",
                "https://www.epicurious.com/expert-advice/kitchen-gadgets-worth-buying-article": "Kitchen Gadgets Worth Buying",
                "https://www.epicurious.com/expert-advice/cast-iron-care-guide-article": "Cast Iron Care Guide",
                "https://www.epicurious.com/expert-advice/knife-buying-guide-article": "Knife Buying Guide",
                "https://www.epicurious.com/expert-advice/cutting-board-care-article": "Cutting Board Care",
                "https://www.epicurious.com/expert-advice/food-storage-best-practices-article": "Food Storage Best Practices",
                "https://www.epicurious.com/expert-advice/how-to-read-recipes-article": "How to Read Recipes",
                "https://www.epicurious.com/expert-advice/how-to-substitute-ingredients-article": "How to Substitute Ingredients",
                "https://www.epicurious.com/expert-advice/cooking-with-kids-article": "Cooking with Kids",
                "https://www.epicurious.com/expert-advice/beginner-baking-tips-article": "Beginner Baking Tips",
                "https://www.epicurious.com/expert-advice/how-to-season-food-article": "How to Season Food",
                "https://www.epicurious.com/expert-advice/building-flavor-layers-article": "Building Flavor Layers",
                "https://www.epicurious.com/expert-advice/umami-explained-article": "Umami Explained",
                "https://www.epicurious.com/expert-advice/acid-in-cooking-article": "Acid in Cooking",
                "https://www.epicurious.com/expert-advice/fat-in-cooking-article": "Fat in Cooking",
                "https://www.epicurious.com/expert-advice/salt-in-cooking-article": "Salt in Cooking",
                "https://www.epicurious.com/expert-advice/heat-control-tips-article": "Heat Control Tips",
                "https://www.epicurious.com/expert-advice/how-to-taste-as-you-cook-article": "How to Taste as You Cook",
                "https://www.epicurious.com/expert-advice/leftover-transformation-ideas-article": "Leftover Transformation Ideas",
                "https://www.epicurious.com/expert-advice/zero-waste-cooking-article": "Zero Waste Cooking",
                "https://www.epicurious.com/expert-advice/composting-kitchen-scraps-article": "Composting Kitchen Scraps",
                "https://www.epicurious.com/expert-advice/sustainable-cooking-practices-article": "Sustainable Cooking Practices",
                "https://www.epicurious.com/expert-advice/farm-to-table-guide-article": "Farm to Table Guide",
                "https://www.epicurious.com/expert-advice/how-to-shop-farmers-market-article": "How to Shop Farmers Market",
                "https://www.epicurious.com/expert-advice/csa-box-cooking-tips-article": "CSA Box Cooking Tips",
                "https://www.epicurious.com/expert-advice/how-to-meal-plan-article": "How to Meal Plan",
                "https://www.epicurious.com/expert-advice/grocery-shopping-strategies-article": "Grocery Shopping Strategies",
                "https://www.epicurious.com/expert-advice/stocking-a-first-kitchen-article": "Stocking a First Kitchen",
                "https://www.epicurious.com/expert-advice/cooking-in-small-spaces-article": "Cooking in Small Spaces",
                "https://www.epicurious.com/expert-advice/one-pot-meal-strategies-article": "One Pot Meal Strategies",
                "https://www.epicurious.com/expert-advice/sheet-pan-dinner-tips-article": "Sheet Pan Dinner Tips",
                "https://www.epicurious.com/expert-advice/instant-pot-tips-and-tricks-article": "Instant Pot Tips and Tricks",
                "https://www.epicurious.com/expert-advice/air-fryer-cooking-guide-article": "Air Fryer Cooking Guide",
                "https://www.epicurious.com/expert-advice/slow-cooker-tips-article": "Slow Cooker Tips",
                "https://www.epicurious.com/expert-advice/dutch-oven-recipes-guide-article": "Dutch Oven Recipes Guide",
                "https://www.epicurious.com/expert-advice/wok-cooking-for-beginners-article": "Wok Cooking for Beginners",
                "https://www.epicurious.com/expert-advice/grill-setup-and-maintenance-article": "Grill Setup and Maintenance",
                "https://www.epicurious.com/expert-advice/smoker-buying-guide-article": "Smoker Buying Guide",
                "https://www.epicurious.com/expert-advice/food-photography-tips-article": "Food Photography Tips",
                "https://www.epicurious.com/expert-advice/recipe-writing-guide-article": "Recipe Writing Guide",
                "https://www.epicurious.com/expert-advice/how-to-develop-recipes-article": "How to Develop Recipes",
                "https://www.epicurious.com/expert-advice/food-trend-predictions-article": "Food Trend Predictions",
                "https://www.epicurious.com/expert-advice/global-cuisine-exploration-article": "Global Cuisine Exploration",
                "https://www.epicurious.com/expert-advice/plant-based-cooking-tips-article": "Plant Based Cooking Tips",
            },
        },
        "holidays": {
            "pages": {
                "https://www.epicurious.com/holidays-events/thanksgiving-turkey-guide-article": "Thanksgiving Turkey Guide",
                "https://www.epicurious.com/holidays-events/christmas-cookie-recipes-article": "Christmas Cookie Recipes",
                "https://www.epicurious.com/holidays-events/easter-brunch-ideas-article": "Easter Brunch Ideas",
                "https://www.epicurious.com/holidays-events/fourth-of-july-grilling-article": "Fourth of July Grilling",
                "https://www.epicurious.com/holidays-events/halloween-treats-article": "Halloween Treats",
                "https://www.epicurious.com/holidays-events/valentines-day-dinner-article": "Valentines Day Dinner",
                "https://www.epicurious.com/holidays-events/thanksgiving-side-dishes-article": "Thanksgiving Side Dishes",
                "https://www.epicurious.com/holidays-events/thanksgiving-pie-recipes-article": "Thanksgiving Pie Recipes",
                "https://www.epicurious.com/holidays-events/thanksgiving-stuffing-guide-article": "Thanksgiving Stuffing Guide",
                "https://www.epicurious.com/holidays-events/thanksgiving-gravy-guide-article": "Thanksgiving Gravy Guide",
                "https://www.epicurious.com/holidays-events/thanksgiving-cranberry-sauce-article": "Thanksgiving Cranberry Sauce",
                "https://www.epicurious.com/holidays-events/thanksgiving-leftover-ideas-article": "Thanksgiving Leftover Ideas",
                "https://www.epicurious.com/holidays-events/thanksgiving-menu-planning-article": "Thanksgiving Menu Planning",
                "https://www.epicurious.com/holidays-events/christmas-ham-recipes-article": "Christmas Ham Recipes",
                "https://www.epicurious.com/holidays-events/christmas-roast-beef-article": "Christmas Roast Beef",
                "https://www.epicurious.com/holidays-events/christmas-appetizers-article": "Christmas Appetizers",
                "https://www.epicurious.com/holidays-events/christmas-desserts-article": "Christmas Desserts",
                "https://www.epicurious.com/holidays-events/christmas-cocktails-article": "Christmas Cocktails",
                "https://www.epicurious.com/holidays-events/christmas-brunch-menu-article": "Christmas Brunch Menu",
                "https://www.epicurious.com/holidays-events/holiday-gift-baskets-article": "Holiday Gift Baskets",
                "https://www.epicurious.com/holidays-events/new-years-eve-appetizers-article": "New Years Eve Appetizers",
                "https://www.epicurious.com/holidays-events/new-years-eve-cocktails-article": "New Years Eve Cocktails",
                "https://www.epicurious.com/holidays-events/new-years-day-brunch-article": "New Years Day Brunch",
                "https://www.epicurious.com/holidays-events/super-bowl-snacks-article": "Super Bowl Snacks",
                "https://www.epicurious.com/holidays-events/super-bowl-chili-recipes-article": "Super Bowl Chili Recipes",
                "https://www.epicurious.com/holidays-events/lunar-new-year-recipes-article": "Lunar New Year Recipes",
                "https://www.epicurious.com/holidays-events/mardi-gras-recipes-article": "Mardi Gras Recipes",
                "https://www.epicurious.com/holidays-events/st-patricks-day-recipes-article": "St Patricks Day Recipes",
                "https://www.epicurious.com/holidays-events/passover-recipes-article": "Passover Recipes",
                "https://www.epicurious.com/holidays-events/easter-ham-recipes-article": "Easter Ham Recipes",
                "https://www.epicurious.com/holidays-events/easter-desserts-article": "Easter Desserts",
                "https://www.epicurious.com/holidays-events/cinco-de-mayo-recipes-article": "Cinco de Mayo Recipes",
                "https://www.epicurious.com/holidays-events/mothers-day-brunch-article": "Mothers Day Brunch",
                "https://www.epicurious.com/holidays-events/fathers-day-grilling-article": "Fathers Day Grilling",
                "https://www.epicurious.com/holidays-events/memorial-day-bbq-article": "Memorial Day BBQ",
                "https://www.epicurious.com/holidays-events/fourth-of-july-sides-article": "Fourth of July Sides",
                "https://www.epicurious.com/holidays-events/fourth-of-july-desserts-article": "Fourth of July Desserts",
                "https://www.epicurious.com/holidays-events/labor-day-cookout-article": "Labor Day Cookout",
                "https://www.epicurious.com/holidays-events/rosh-hashanah-recipes-article": "Rosh Hashanah Recipes",
                "https://www.epicurious.com/holidays-events/yom-kippur-break-fast-article": "Yom Kippur Break Fast",
                "https://www.epicurious.com/holidays-events/diwali-recipes-article": "Diwali Recipes",
                "https://www.epicurious.com/holidays-events/hanukkah-recipes-article": "Hanukkah Recipes",
                "https://www.epicurious.com/holidays-events/halloween-party-food-article": "Halloween Party Food",
                "https://www.epicurious.com/holidays-events/halloween-cocktails-article": "Halloween Cocktails",
                "https://www.epicurious.com/holidays-events/friendsgiving-menu-article": "Friendsgiving Menu",
                "https://www.epicurious.com/holidays-events/holiday-cookie-exchange-article": "Holiday Cookie Exchange",
                "https://www.epicurious.com/holidays-events/holiday-potluck-ideas-article": "Holiday Potluck Ideas",
                "https://www.epicurious.com/holidays-events/winter-comfort-food-article": "Winter Comfort Food",
                "https://www.epicurious.com/holidays-events/summer-entertaining-guide-article": "Summer Entertaining Guide",
                "https://www.epicurious.com/holidays-events/spring-garden-party-article": "Spring Garden Party",
            },
        },
    }

    def __init__(self, base_dir, source_key=None):
        name = f"epicurious-{source_key}" if source_key else "epicurious"
        super().__init__(name, base_dir, interval_seconds=3600)
        self.source_key = source_key

    def _strip_html(self, html_content):
        """Remove HTML tags, scripts, styles and normalize whitespace."""
        text = html_content
        text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
        text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL)
        text = re.sub(r'<nav[^>]*>.*?</nav>', '', text, flags=re.DOTALL)
        text = re.sub(r'<footer[^>]*>.*?</footer>', '', text, flags=re.DOTALL)
        text = re.sub(r'<[^>]+>', ' ', text)
        text = html_mod.unescape(text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    def _extract_title(self, html_content, fallback):
        """Extract page title from HTML."""
        match = re.search(r'<title>([^<]+)</title>', html_content, re.IGNORECASE)
        if match:
            title = match.group(1).strip()
            for suffix in [' | Epicurious', ' - Epicurious', ' Recipe | Epicurious']:
                if title.endswith(suffix):
                    title = title[:-len(suffix)].strip()
            return title
        return fallback

    def _scrape_source(self, source_key, config):
        """Scrape all pages for a given source section."""
        count = 0
        pages = config.get("pages", {})

        for url, title in pages.items():
            if not self.running:
                break

            item_id = self.make_id(url)
            content = self.fetch_url(url)

            if content and len(content) > 500:
                text = self._strip_html(content)
                if len(text) > 100:
                    page_title = self._extract_title(content, title)

                    if self.save_item(item_id, {
                        "title": page_title,
                        "content": text[:50000],
                        "url": url,
                        "category": f"epicurious-{source_key}",
                        "type": "documentation",
                    }):
                        count += 1
                        self.log.info(f"  {source_key}: {title}")

            time.sleep(2.0)

        return count

    def scrape(self):
        """Run scrape across all or a specific source."""
        total = 0

        if self.source_key:
            if self.source_key not in self.SOURCES:
                self.log.error(
                    f"Unknown source key: {self.source_key}. "
                    f"Available: {list(self.SOURCES.keys())}"
                )
                return 0
            sources = {self.source_key: self.SOURCES[self.source_key]}
        else:
            sources = self.SOURCES

        for key, config in sources.items():
            if not self.running:
                break
            self.log.info(f"=== Scraping epicurious/{key} ===")
            total += self._scrape_source(key, config)

        return total


if __name__ == "__main__":
    import os
    import sys

    base = os.path.expanduser("~")
    source_key = sys.argv[1] if len(sys.argv) > 1 else None
    EpicuriousScraper(base, source_key).run()
